### ISSUE TITLE
GUI: Allow users to name/label their wallet keys

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain-gui#1000]
Design:

https://www.figma.com/file/uCI6CTQ1W4uElMtmN6P4Qv/1.5-Updates?node-id=3%3A2

Preliminary support:

https://github.com/Chia-Network/chia-blockchain-gui/tree/paninaro.key_labelling_exploration/

**Comment by paninaro** [comment]
![Image](https://user-images.githubusercontent.com/339312/188249393-8a2bfe28-73c0-4d65-ad86-a04a2c486a99.png)

**Comment by paninaro** [comment]
We can also name a key when importing/generating a key

**Comment by seeden** [comment]
Already merged. Closing it
