### ISSUE TITLE
GUI: Unable to switch back to original mode within the same session

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain-gui#1005]
After making a mode switch, the UI prevents you from switching back tot he original mode if the app is in the same launch session. It works properly if the app quits between switching modes.

Steps to repro:

1. Launch in farmer mode
2. Switch to wallet mode
3. Without quitting the app, attempt to switch back to farmer mode

Observe:

1. When attempting to click the farmer button, the selection doesn't stick -- mode is not changed

This also happens when starting in wallet mode -- can't switch back to wallet mode after switching to farmer mode in the same session.

**Comment by jfawChia** [comment]
Given I have a full wallet available
1. Navigate to a Wallet 
2. Click > Settings > Wallet 
3. Notice: Wallet is change to wallet mode only
4. Verify that user only has access to Tokens, NFTs, Offers and Settings page
5. Click > Farming 
6. Notice: Wallet is converted back to Farming mode 
7. Verify that user has access to Tokens, NFTs, Offers, Full Node, Plots, Farming, Pooling tabs and Settings pages
