### ISSUE TITLE
GUI: When naming a stray CAT wallet, don't add wallet until switch is turned on

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain-gui#1010]
Users who have many CAT wallets may want to give those wallets proper names without actually adding the wallet.

Currently, the UI will create the wallet with the provided name, even if the user hasn't turned the wallet's visibility toggle on.

Proposed solution is to have the UI track the names of those CAT wallets that haven't been added yet. This would allow us to display the user-provided name without actually adding the wallet in the backend (which incurs sync/resource overhead). If the user later decides to show the wallet, the wallet would be created as needed.

**Comment by seeden** [comment]
Created PR https://github.com/Chia-Network/chia-blockchain-gui/pull/1044

**Comment by seeden** [comment]
PR merged. Closing
