### ISSUE TITLE
Parallel plot creation hung in "Plotting" status 

### ISSUE THREAD

**Issue by StogieC** [Chia-Network/chia-blockchain-gui#102]
Created plot in Queued mode without issue.

Created three new plots in Parallel.  

Upon completion of the new plots the **.plot.2.tmp files copied to the UNC path to the destination drive but did not delete the source files from the Temp drive or rename/complete the destination files.  GUI shows the plots in "Plotting" status and view log shows:

```
	Finished writing C1 and C3 tables
	Writing C2 table
	Finished writing C2 table
	Final table pointers:
	P1: 0x10c
	P2: 0x37482233e
	P3: 0x6b5f5d4b6
	P4: 0x9fdc2dd95
	P5: 0xd55c6759e
	P6: 0x10d99486ce
	P7: 0x14ea39dca0
	C1: 0x190a3f46a0
	C2: 0x190a597dac
	C3: 0x190a597e5c
Time for phase 4 = 1048.529 seconds. CPU (83.540%) Thu Feb 25 20:50:20 2021
Approximate working space used (without final file): 286.649 GiB
Final File size: 101.362 GiB
```

**Comment by StogieC** [comment]
Hung chia.exe thread for each stalled plot.  Wait chain reports "waiting to finish network I/O"

**Comment by hoffmang9** [comment]
Network copies to a SAN or such can take forever...?

**Comment by StogieC** [comment]
Over two hours since completion on at 10Gbase-T network and same bite size as the temp.
Stopping and force killing the hung PIDs, manually removing ".2.temp" from the plot file names, and restarting the GUI caused all plots to be recognized.

**Comment by StogieC** [comment]
Ran more plots overnight.  The "Copied final file" entry is not in the plotter log but the file is copied over.  Again, manually renaming the final file and deleting the temp files worked fine.  While the file write time was fine, the manual rename did take longer than expected, about 30 to 40 sec.  I'm digging into NAS performance but this may be a timeout/retry issue.

**Comment by StogieC** [comment]
The "Total time =" log entry is also not present.
