### ISSUE TITLE
GUI: Key labeling follow-up fixes

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain-gui#1025]
1. When renaming/creating/importing a key, we should cap the wallet name to 64 characters. If the label is too long, the GUI shows the error:

![Image](https://user-images.githubusercontent.com/339312/191384257-bd928db1-c0df-422f-9252-ce5703aedc50.png)

Also, it would be ideal if we showed the `error_details` if available in the response.
```> {"command":"set_label","data":{"fingerprint":"4056096778", "label":"asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf"},"origin":"wallet_ui","destination":"daemon","ack":false,"request_id":"fa066606c625b35cf678556b9aacebb4e7d0a6915405c11454c13f769239ae3e"}```
```< {"ack": true, "command": "set_label", "data": {"error": "malformed request", "error_details": {"message": "label exceeds max length: 80/65"}, "success": false}, "destination": "wallet_ui", "origin": "daemon", "request_id": "fa066606c625b35cf678556b9aacebb4e7d0a6915405c11454c13f769239ae3e"}```

2. Typo when deleting a key (error originally appears in Figma):

![Image](https://user-images.githubusercontent.com/339312/191384543-8342d2bd-020d-4c61-9632-891bf81eaf5a.png)

We can just delete the "name" occurrence in the string so that it reads:
"Are you sure you want to continue? Type in the fingerprint of this wallet key to confirm deletion."

**Comment by paninaro** [comment]
Also, if you try to name your wallet " " you'll see a malformed error as above, but the `error_details` will indicate "label can't be empty or whitespace only"

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/1033

**Comment by paninaro** [comment]
Original key labeling task: https://github.com/Chia-Network/chia-blockchain-gui/issues/1000
