### ISSUE TITLE
[Bug] Common naming of `DataLayer` vs `Data Layer`

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain-gui#1028]
### What happened?

In all of our docs, and according to the DL team, the proper naming for all things DL is precisely `DataLayer`. In our GUI, it shows all references as `Data Layer`

### Version

1.6.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Updated the Settings screen as well as the service starting/stopping screens

**Comment by paninaro** [comment]
Updated naming:

![Image](https://user-images.githubusercontent.com/339312/193091039-7eaccbfb-6916-42f9-97d1-7ac7f17aaeb3.png)
