### ISSUE TITLE
Plot failed but still listed as "Plotting" on Plots tab.

### ISSUE THREAD

**Issue by StogieC** [Chia-Network/chia-blockchain-gui#104]
```
Starting plotting progress into temporary dirs: D:\ChiaTemp and D:\ChiaTemp
ID: ca751014d3d84089b71af569a6101468a56052c3d078fe5148f62f2759d8ec7a
Plot size is: 32
Buffer size is: 102400MiB
Using 128 buckets
Using 12 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Fri Feb 26 06:48:49 2021
Computing table 1
F1 complete, time: 162.92 seconds. CPU (173.8%) Fri Feb 26 06:51:31 2021
Computing table 2
Caught plotting error: bad allocation
```

Two other parallel plots appear to be running normally.

![image](https://user-images.githubusercontent.com/34588931/109299123-9a5d3700-7802-11eb-8caa-4ab0f78b1849.png)

**Comment by StogieC** [comment]
Likely forced error by over allocating memory.  100GB on a 64 GB system.  But GUI should show error status.

**Comment by hoffmang9** [comment]
Unfortunately the various kernels don't tell the application anything when they stop it for OOM.

**Comment by StogieC** [comment]
repeated state without exceeding memory today...  Still an issue.

![image](https://user-images.githubusercontent.com/34588931/109400837-fdd98880-7918-11eb-8c76-c57112a7bf01.png)
