### ISSUE TITLE
Cannot build gui on RPi4 Ubuntu 20.04 RCS>=0.2.3

### ISSUE THREAD

**Issue by wrosko** [Chia-Network/chia-blockchain-gui#105]
Raspberry pi 4, 8GB RAM running Arm64 and Ubuntu 20.04

Having a lot of trouble trying to get the `electron` build to work. 

I have tried nuking my nodejs libs, which included reinstalling various versions of  Nodejs v12. As well as nuking the directory and recloning, resetting to master/origin etc. Any suggestions?

Full log/stack trace from `debug.log`:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.8
3 info using node@v12.18.2
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@
6 info lifecycle chia-blockchain@~electron: chia-blockchain@
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/home/user/chia-blockchain/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle chia-blockchain@~electron: CWD: /home/user/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]
11 silly lifecycle chia-blockchain@~electron: Returned: code: 1  signal: null
12 info lifecycle chia-blockchain@~electron: Failed to exec electron script
13 verbose stack Error: chia-blockchain@ electron: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid chia-blockchain@
15 verbose cwd /home/user/chia-blockchain/chia-blockchain-gui
16 verbose Linux 5.8.0-1016-raspi
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
18 verbose node v12.18.2
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error chia-blockchain@ electron: `electron .`
22 error Exit status 1
23 error Failed at the chia-blockchain@ electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

CLI display:
```
(venv) user@user-pi4:~/chia-blockchain/chia-blockchain-gui$ npm run electron &
[2] 172590
(venv) user@user-pi4:~/chia-blockchain/chia-blockchain-gui$
> chia-blockchain@ electron /home/user/chia-blockchain/chia-blockchain-gui
> electron .

The futex facility returned an unexpected error code.
/home/user/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron exited with signal SIGABRT
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-02-26T23_24_31_264Z-debug.log
```

**Comment by wrosko** [comment]
to note: I have tried MANY different solutions. First of which were of course the `rm -rf node_modules package-lock.json` , a reinstall of the gui, then running electron. But I continuously get this failed build error.

**Comment by hoffmang9** [comment]
I just upgraded my Pi 4 8GB RAM Ubuntu 20.04 - and though slow - it works for me...

I did need to delete my .chia directory and manually chia init'ed but that's because I set $CHIA_ROOT.

Not sure where to go next for you since I can't replicate.

**Comment by hoffmang9** [comment]
Relevent packages from my Pi:

uname -a = Linux ubuntu 5.4-01029-rspi #32-Ubuntu SMP PREEMPT Thu Feb 4 23:00:55 UTC 2021 aarch64 aarch64 GNU/Linux
lsb_release -d = Ubuntu 20.04.2 LTS
node --version = v10.19.0
npm --version = 6.14.4
python --version = 3.8.5
`git status` inside chia-blockchain-gui is `HEAD detached at 55a5221`

**Comment by wrosko** [comment]
Hmm interesting, I'll try digging into it deeper tomorrow. Thanks for giving it a try

**Comment by wrosko** [comment]
I got it working.
So I guess there was some weird things happening with my Nodejs install. I decided to download and install `nvm` and then installed Node.js 12. Then wiped the `node_modules` and `packages-lock.json`, and ran the gui scripts. It works now, so env build on my end was funky. Thanks for the help.

**Comment by krtpowa** [comment]
> I got it working.
> So I guess there was some weird things happening with my Nodejs install. I decided to download and install `nvm` and then installed Node.js 12. Then wiped the `node_modules` and `packages-lock.json`, and ran the gui scripts. It works now, so env build on my end was funky. Thanks for the help.

how i do this? i have a rpi with raspbian base, and i get the same error.electron doesn't works.. 
my npm version is v16

thanks!!

**Comment by wrosko** [comment]
Look up nvm and install nodejs v12 (sorry on mobile right now won't be by
computer for a while). There are some guides out there. I look dup Ubuntu
stuff, but this may help you cause it's rpi related
https://linuxize.com/post/how-to-install-node-js-on-raspberry-pi/
