### ISSUE TITLE
[Bug] When I rename two wallets with the same name, I get a cryptic message. 

### ISSUE THREAD

**Issue by sethjenks** [Chia-Network/chia-blockchain-gui#1061]
### What happened?

When I rename two wallets with the same name, I get a cryptic message. "Error malformed request"

I am also getting the same error when I am in the edit mode and don't make any changes to the text and try to save. 

<img width="719" alt="CleanShot 2022-10-17 at 14 53 33@2x" src="https://user-images.githubusercontent.com/663017/196281095-911e89cb-682a-4907-b0ca-d075763c4c99.png">

It would be best if we just allowed people to make duplicate names.

It could also say, "Hold up! Wallets must have unique names". This would be annoying in the case above though where I have a unique name already and I can't save it. 

### Version

1.6.1b4-dev16

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Fixed in 1.6.1
