### ISSUE TITLE
Wrong graph for CH21, Spacebucks and some other CATs

### ISSUE THREAD

**Issue by korolevsv** [Chia-Network/chia-blockchain-gui#1068]
### What happened?

Graph for CH21, Spacebucks and some other CATs look not like a line but as a unit impulse (delta-function)

### Version

1.6.1b3
<img width="1232" alt="Wrong graph for CH21" src="https://user-images.githubusercontent.com/8134234/195174386-d4a3cf80-2e95-45e1-ac0c-de6cf1accc48.png">

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by korolevsv** [comment]
The bug still remained in the 1.6.1-rc1 :-(

**Comment by seeden** [comment]
I also fixed spike graph in https://github.com/Chia-Network/chia-blockchain-gui/pull/1089
