### ISSUE TITLE
[Bug] UI Fixes for Offer Builder

### ISSUE THREAD

**Issue by sethjenks** [Chia-Network/chia-blockchain-gui#1091]
### What happened?

- [ ] #1154
<img width="1728" alt="CleanShot 2022-10-18 at 13 44 00@2x" src="https://user-images.githubusercontent.com/663017/197553314-46e16662-62b5-4c36-93f2-7a5a999420ad.png">

- [ ] When navigating away from an offer to select another NFT ID. The current offer is not saved, and I have to start over from scratch. It seems that it would be really painful to make a multi-NFT offer if this is the case.  

### Version

1.6.1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
First issue captured as issue #1154 

NFT search/autocomplete field will help address the second issue.

Closing
