### ISSUE TITLE
UI Fixes: Sticky Parameters, and Plot log rationalization

### ISSUE THREAD

**Issue by specracer35** [Chia-Network/chia-blockchain-gui#111]
The Windows GUI for plotting and the plot logs is in particular need attention.

1) It's a pain to repeatedly input all of the plotting parameters:  other than size, threads, and stripes, you have to specify number of plots, memory, stagger, bitfield, and temporary and final destinations.  These should be be sticky, prepopulated with whatever their last values were.  Given that once folks get a particular plot strategy in place they don't change it, it would seriously aid us if the params were sticky.

2) The plot logs are poorly designed. They have no consistent formatting and are both under-and over-inclusive in the data included.

a) Formatting. Ideally, the logs should be set up so they can be easily ingested into a database for analysis. This means consistent format in terms of fields and delimiters.   What we have are some fields separated by ":" others by tabs, others with spaces, others with "...." , others not at all.  The format <day><month><time><year> is entirely non-standard and requires custom code for parsing on ingest.  Some lines the logs are separated by 1 line break, others by 2 line breaks, in no consistent manner. Here is the start of a log:

Starting plotting progress into temporary dirs: F:\ChiaTempF and F:\ChiaTempF
ID: 847ed183e02f1feeaf7619d85fc6aa4364aacd872878892d23f4833e8df16d6e
Plot size is: 32
Buffer size is: 1000MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Mon Mar  1 18:42:34 2021
Computing table 1
F1 complete, time: 75.737 seconds. CPU (149.77%) Mon Mar  1 18:43:49 2021
Computing table 2

Notice the inconsistency:  "Plot size is:" and then "Using 128 buckets".   A normal design would be 
Plot size: 32
Buckets: 128

Why is .... used in "Starting phase 1/4 to separate the date and time, but in the "F1 complete, no such delimiter is used.

b) The logs are over-inclusive--every "bucket" sort or write is logged.  And bucket lines are basically the same 128 lines, over and over again:

              Bucket 127 QS. Ram: 0.917GiB, u_sort min: 1.125GiB, qs min: 0.562GiB. force_qs: 0

The only thing that changes is the bucket number. And I have yet to find resource that explains what this is information is useful for in terms of analytics or even real time monitoring.  

Remember: we look at the plot logs in real time to see actual progress. Having to scroll past hundreds and hundreds of lines of "Bucket..." details to find out what phase is going on it is waste of time and space.

Yet useful information--the actual plotting parameters (esp. number of parallel plots of which the current plot is included), as well as stagger, etc. are not included. If you are doing analysis, you need this and the only way to get it now it so manually add it after you ingest the data into a database. 

c) Plot logs names: I have yet to figure out what the log files names are based on--I'm sure there's an explanation--but regardless they are needlessly long and complicated, and really mean nothing to the user.  A rational name would be based on the date and time the plot was started, because that's what humans remember, not arbitrary strings. 
  

Recommendation.  
1) Adopt either a comma delimited, or tab delimited file format.
2a) Either each line should have the format <field name><delimiter><data value>.  Data values should not include any text of units.   We know what the units are.
2b) Alternatively, have a single line with all of the field names, delimited, and then a single line with all corresponding values, delimited.
3) We don't need the bucket information. If you think the bucket detail is important, the provide a -verbose option in the UI that folks can select.
4) What information should be there? Again thinking analytics, I want to know the following:
--Log file name. Here, give a plot log a serial number (the jth plot run) followed by start date and time.  The value J is the same for all plots in this run (whether serial or parallel). This enables all of the logs for each plot run J to be linked together in a database and the performance metrics (time, CPU) averaged over all plots in the run.  
-- Plot Run (again this is the J value)
-- Plot ID
-- Number of plots total in this run
--Plot size (and don't say "Plot size is:" "is"? Really?  
-- Instance number N of this plot in this run
-- Series or Parallel: S or P
-- Stagger time
-- Memory allocation
--Threads
--Bucket size
--Bitfield setting
--Stripe size (never changes, but whatever)
-- Overall Start time:  Use a conventional date time format, please. mm/dd/yyyy, hh:mm:ss.ssss or similar.  Ideally something that can be natively recognized by Excel or other database software as a date.
-- Phase 1 total time (we don't need start and end time if you provide this; start and end are just means to the end of computing total time. Just give us total time)
-- Phase 1 CPU
-- Phase 2 total time
-- Phase 3 CPU
-- Phase 4 total time
-- Phase 4 CPU
--Total time (again we don't need the end time if we have total time.
--Total CPU

(Just to be clear the "--" above are NOT to be included in the file).

3) Don't put the "View Log" RIGHT NEXT TO "Delete Plot"!  That's terrible design. That's like the Army putting "View Log" next to "Launch Nuclear Missile." Sure there's a confirmation screen ("Are you sure you want to launch a nuclear warhead? <Ok><Cancel>"), but why create needless anxiety?  Yes View Log and Delete Plot are both actions, but find a way to separate them.

4) Why does "View Log" disappear after the plot is complete.  Sure I can go fetch the log file from the plotter directory, but there's no reason to kill the link?

5) Why is the View Log window modal and you only can view one at time?  The windows should be independent and non-modal so you can view several simultaneously.    (Of course, ideally, you'd have a dashboard that shows the actual run time status per the above so you can monitor all plots, but I'm not asking for that. )

Fixing the plot log format and stickiness are trivially easy changes in the coding and shouldn't take more than a couple of hours. 

Thank you for your consideration.

**Comment by seeden** [comment]
Hi @specracer35 . Thank you for your comments. We will improve logs in the long run

**Comment by mariano54** [comment]
A lot of these changes are for the chiapos repo

**Comment by hoffmang9** [comment]
And are going to be a while before they're addressed. There are still fundamental changes to the plotting algorithm that mean that the best logging strategy isn't known yet.

This should be split into two issues and the logging moved to chiapos.
