### ISSUE TITLE
[Bug] - GUI doesn't show error when accepting an offer before the wallet has synced up

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#1128]
### What happened?

While running the 1.6.1 rc5 build on mac intel in wallet only mode, I tried accepting an offer I copied from Dexie and while the wallet sync status showed "orange", I tried accepting an offer. I didn't get an error message and after clicking on the accept button, nothing happened. I clicked on it twice thinking it didn't take the first time. Eventually the GUI errored out into a 500 second timeout issue.
<img width="1312" alt="Screen Shot 2022-11-01 at 10 48 40 AM" src="https://user-images.githubusercontent.com/93196638/199299993-43bae075-918a-4495-810f-2cece4886e39.png">

We should show an error message in the GUI if user can't accept an offer while the wallet is still syncing to prevent any confusion on the user's part.

### Version

1.6.1 rc5

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@rifeljm when clicking the "Accept Offer" button we should check if the wallet is synced, and if not, display an alert. We can use either the `useIsWalletSynced()` hook, or `useWalletState()` to determine if the wallet is synced. We can do something like:

```
    if (state !== SyncingStatus.SYNCED) {
      throw new Error(t`Please wait for wallet synchronization`);
    }
```
