### ISSUE TITLE
[Bug] can't switch from farming -> wallet -> farming in the same session

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#1142]
### What happened?

Starting in farming mode and then switching to wallet mode, the Chia app doesn't then let me switch back to farming mode until you restart the Chia client.

The expectation is that you should be able to switch back to farming mode since all the services are still running.

### Version

1.6.1 rc5

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by ChiaMineJP** [comment]
The same issue as
https://github.com/Chia-Network/chia-blockchain-gui/issues/1005

**Comment by ChiaMineJP** [comment]
Closed with https://github.com/Chia-Network/chia-blockchain-gui/issues/1005
