### ISSUE TITLE
Error message with trailing spaces in Wallet name

### ISSUE THREAD

**Issue by stewari5** [Chia-Network/chia-blockchain-gui#1143]
### What happened?

Got an error message when I created a new wallet and named it with trailing spaces in the name. The wallet was still created but name was the default name

![image](https://user-images.githubusercontent.com/107882139/199406238-b1836550-15e8-41e6-b1b3-cf7a3ef36b45.png)

### Version

1.6.1 RC5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
We should use the new `add_private_key` RPC added to the daemon for this. I've prepared a PR to make a necessary addition to that RPC: https://github.com/Chia-Network/chia-blockchain/pull/13814

**Comment by paninaro** [comment]
Fixed with https://github.com/Chia-Network/chia-blockchain-gui/pull/1157

**Comment by paninaro** [comment]
### Testing Notes

This affected both the creation of a newly generated key as well as importing from a 24-word mnemonic.

### Steps to repro
1. Click "Create a New Private Key" or "Import from Mnemonic (24 Words)"
2. If importing from a mnemonic, enter the mnemonic
3. Enter a name for the new wallet key, and include spaces at the end of the name
4. Click "Next"

### Observe
Prior to the fix, an error dialog would appear indicating that the key already existed.
