### ISSUE TITLE
[Bug] need a better error message when creating an offer for an NFT you don't own

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#1144]
### What happened?

I tried creating an offer and in the "Offering" section, I put in an NFT that I don't currently own in this wallet. when I try to create the offer, I get an error message that isn't user friendly.

<img width="1624" alt="Screen Shot 2022-11-02 at 7 01 49 AM" src="https://user-images.githubusercontent.com/93196638/199485436-9880e526-9bb1-4ed7-8d52-27c9e767786d.png">

We need to improve the content of the error message so that users's know why there's an error.

### Version

1.6.1 rc5

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Well I find the current error message quite easy to understand :)
