### ISSUE TITLE
If I paste an NFT ID into a field and then paste another into the field, the original name is still on the card.

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain-gui#1154]
The useNFTMetadata hook seems to be capturing a stale value in one of the nested functions. Here's an example where the NFT is showing the wrong metadata:

![image](https://user-images.githubusercontent.com/339312/199810597-5c394f0f-da5d-41d5-a4ba-378eac4836b8.png)

`nft1gqqr7a7n8926l06mr3wf467x6ah3u8d6dysgq7nhp5xqrjsgg8vsndfruc` is NFT shown in the screenshot

**Comment by esaung** [comment]
could this also be causing the issue we saw when sending an NFT to the burn address?

**Comment by paninaro** [comment]
> could this also be causing the issue we saw when sending an NFT to the burn address?

Yes, it's almost certainly the same issue

**Comment by paninaro** [comment]
Fixed by https://github.com/Chia-Network/chia-blockchain-gui/pull/1222
