### ISSUE TITLE
[Bug] custom fee input box doesn't limit zeros after decimal

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#1169]
### What happened?

on sending xch or cats, when using the custom fee entry, I can put unlimited number of zeros after the decimal which results in an invalid number of mojos if putting in too many 0's.

Need to limit to the right amount of 0's that can be inputed as a custom fee

![Screen Shot 2022-11-09 at 12 35 06 AM](https://user-images.githubusercontent.com/93196638/200757076-5f75c2dd-95f8-4789-9284-5300ce295227.png)

### Version

1.6.1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
PR: [1203](https://github.com/Chia-Network/chia-blockchain-gui/pull/1203)

**Comment by paninaro** [comment]
Fixed in 1.7.0
