### ISSUE TITLE
[Bug] Windows: Points Successful Chart X axis and Token Balance chart have mismatched X axis Origins.

### ISSUE THREAD

**Issue by rkroelin** [Chia-Network/chia-blockchain-gui#1170]
### What happened?

Points Successful Chart X axis and Token Balance chart have mismatched X axis Origins.  Pooling tab chart origin/Now is on the left, Token balance origin/now is on the right.

Quibble seen in second image - the P in points is hidden by the frame. 

![image](https://user-images.githubusercontent.com/53322426/200884339-c772d7e3-9824-46eb-b777-04e7638a904c.png)
![image](https://user-images.githubusercontent.com/53322426/200884518-648c0f0a-5f28-46f9-8ad6-b0b200cd8023.png)

### Version

1.6.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@seeden I think this has been fixed already in main, right?

**Comment by seeden** [comment]
Tooltip position fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/1228
