### ISSUE TITLE
[Bug] Editing and saving payout instruction for a pool isn't clear to the user

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#1171]
### What happened?

When updating the XCH address used for payouts in a pool, after updating the XCH address and hitting save, the prompt doesn't go away, but continues to say cancel or save. it makes it seem like hitting save didn't work even though it did.

we just need to make the prompt go away after user hits cancel or save.

<img width="902" alt="Screen Shot 2022-11-11 at 1 56 47 PM" src="https://user-images.githubusercontent.com/93196638/201422154-00488f03-bec8-4cbd-9b1a-0e6ec86f417f.png">

### Version

1.7.0. b1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@ChiaMineJP would you mind taking a look at this one?
