### ISSUE TITLE
[Bug] NFTs are not displayed in the wallet

### ISSUE THREAD

**Issue by timudjinka** [Chia-Network/chia-blockchain-gui#1199]
### What happened?

NFT are not displayed in the Chia wallet (1.7.0b1):

![ChiaSetup-1 7 0b1](https://user-images.githubusercontent.com/118344524/202136366-98fd21e2-a352-49f8-85e7-95d2d9eb84bf.jpg)

Creation of new NFTs by the MintGarden program (MintGarden-Studio_0.1.7) passes successfully:

![MintGarden-Studio_0 1 7](https://user-images.githubusercontent.com/118344524/202136468-7c2a7467-f8f5-4685-a01a-6f2647c9bf97.jpg)

On the MintGarden and Spacescan websites, NFTs are displayed successfully:

![spacescan](https://user-images.githubusercontent.com/118344524/202136547-2e66058a-f438-4a22-9be7-02e87cf54881.jpg)
![mintGarden](https://user-images.githubusercontent.com/118344524/202136583-d0f957ae-2bde-4c68-9959-b335a2715e1a.jpg)

An error appears when trying to update the NFT:

![error](https://user-images.githubusercontent.com/118344524/202136641-876a8fd3-cec8-4f05-88cf-985f2800cc78.jpg)

### Version

1.7.0b1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Please try again with 1.7.0. Closing for now.
