### ISSUE TITLE
[Bug] Creating A Plot does not recognize required fields 

### ISSUE THREAD

**Issue by jfawChia** [Chia-Network/chia-blockchain-gui#1258]
### What happened?

**ISSUE:** 
While creating a Plot we noticed that fields that should be required are not. A user is allowed to Create a plot specifically without selecting locations for Step 4 [Select Temporary Directory] and Step 5 [Select Final Directory] or step 6 [Join a Pool or Create a Plot NFT].

**STEPS TO REPRODUCE:** 
User Scenario 1
- Given I have a wallet created with TXCH
- When I navigate to Plots tab on left navigation bar
- Click > ADD A PLOT 
- Click > CREATE 
- EXPECTED RESULT: User should be instructed to complete all required fields. 
- ACTUAL RESULT: User is directed back to Plots main page

User Scenario 2
- If user completes step 6 without completing steps 4 and step 5 
- Click > CREATE 
- EXPECTED RESULT: User should be instructed to complete all required fields. 
- ACTUAL RESULT: User is directed back to Plots main page and status % never goes pass 0

<img width="1698" alt="Screen Shot 2022-12-19 at 2 11 04 PM" src="https://user-images.githubusercontent.com/105236411/208503784-866ddabf-125f-49ff-b3ae-c0ad65128636.png">

### Version

1.6.2rc1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@ChiaMineJP can you take a look at this as part of the plotting changes for the next release?
