### ISSUE TITLE
[Bug] not reading metadata for NFTs

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#1263]
### What happened?

NFT gallery and NFT details show "title not available" and description shows "not available" for NFTs for NFTs that does have metadata. this worked in the previous releases.

![Screenshot 2022-12-22 at 2 01 55 PM](https://user-images.githubusercontent.com/93196638/209218113-48044c59-9f80-4f55-aa5b-5b210dc096bc.png)

### Version

1.7.0b4

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
This has been fixed.
