### ISSUE TITLE
[Bug] NFT Royalties persist on Offer after removed

### ISSUE THREAD

**Issue by jfawChia** [Chia-Network/chia-blockchain-gui#1266]
### What happened?

While testing the following scenario Can you create an offer - your CAT for someone else's NFT and then switching NFT to TXCH we notice that the Royalties that display under Offering for CAT continue to display after user deletes NFT.

<img width="1750" alt="royalties" src="https://user-images.githubusercontent.com/105236411/209874830-9873e435-2e61-4597-8d26-758822477a90.png">

### Version

1.6.2

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by jfawChia** [comment]
User scenario was as expected. This doesn't appear to be a bug

**Comment by paninaro** [comment]
@jfawChia Can you clarify if this is a bug?

**Comment by jfawChia** [comment]
@paninaro I was just able to reproduce this minor issue on latest build 1.7.0rc5. 

ISSUE: User attempts to create an Offer TXCH for NFT and then removes/deletes the NFT

STEPS TO REPRODUCE: 
Given I have an NFT ID copied
When I navigate to a Wallet containing TXCH to create an offer for NFT
And I click > Offers > CREATE AN OFFER > TXCH + > 1 Amount 
And I click > NFT under Requesting > paste NFT 
NOTICE: That Total Amount with Royalties display 
When I click > NFT - [to remove NFT offer]
And I click > Tokens  + > Select Asset Type > 1 
NOTICE: That Total Amount with Royalties still displays even though NFT was remove from offer. 

E.R. Total Amount with Royalties should be remove from Offering since there is nolonger an NFT in the Requesting section.

**Comment by paninaro** [comment]
@jfawChia Thanks for the repro steps. @lipalong can you take a look at this bug?
