### ISSUE TITLE
More strings not available on Crowdin

### ISSUE THREAD

**Issue by ordtrogen** [Chia-Network/chia-blockchain-gui#127]
Bottom right "Rows per page" and the "of" in "1-3 of 3"

![image](https://user-images.githubusercontent.com/15184875/110090150-3f45ba00-7d97-11eb-8c1c-8ff67c6f034c.png)

**Comment by jespino** [comment]
This is not really a chia-blockchain-gui translation, this comes from `material-ui`, probably we need to do something like loading the localization for material ui during the app initialization. More info here: https://material-ui.com/guides/localization/

**Comment by jespino** [comment]
Fixed here: #137 :)
