### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by aiken1811** [Chia-Network/chia-blockchain-gui#1276]
### What happened?

I'm accidently mint Some nft without select collection
so I'm trying to burn NFT but chia gui is hang 
only showing 5 to 10 NFTs

### Version

1.6.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

<img width="423" alt="Chia error" src="https://user-images.githubusercontent.com/37618801/209438227-0d3b332c-fcbd-4b62-aeec-52d7d01e43df.PNG">

**Comment by paninaro** [comment]
This should be addressed in the release/1.7.0 and main branches.
