### ISSUE TITLE
[BUG] GUI: Problems connecting to wallet

### ISSUE THREAD

**Issue by originipad** [Chia-Network/chia-blockchain-gui#1278]
**Describe the bug**
I can't connect to wallet after restart computer

**Screenshots**
![image](https://user-images.githubusercontent.com/86886012/139542030-71ded1a0-b041-4426-8a85-a338d25b665a.png)

**Desktop**

- OS: windows 10 pro
- OS Version/Flavor: 20h2
- CPU: 11700 intel

**Additional context**

**Comment by emlowe** [comment]
This is almost certainly caused by Windows reserving the 55400 port the daemon uses by default.

You can either change the daemon port in config.yaml, or you can modify windows to not reserve this port:
```
dism.exe /Online /Disable-Feature:Microsoft-Hyper-V
reboot
netsh int ipv4 add excludedportrange protocol=tcp startport=55400 numberofports=1
reboot
dism.exe /Online /Disable-Feature:Microsoft-Hyper-V
reboot
```
