### ISSUE TITLE
[Bug] Unable to automatically start linux and winodws

### ISSUE THREAD

**Issue by Concord-us** [Chia-Network/chia-blockchain-gui#1287]
### What happened?

Almost all the methods have been tried and failed.

### Version

1.6.2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
There are insufficient details included here to make progress on this issue.

Please include some details on what you are trying to do and what error you are seeing. Also included log output would likely be needed.
