### ISSUE TITLE
[Bug] French interface, "Please enter a valid fee amount"

### ISSUE THREAD

**Issue by BenJ3D** [Chia-Network/chia-blockchain-gui#1293]
### What happened?

In the French interface (and others), I think that the use of ',' (0,0001) rather than a '.' (0.0001) in the proposal of auto fees causes the program to return an error "Please enter a valid fee amount".

![image](https://user-images.githubusercontent.com/49345674/211349800-045c14fb-c159-4929-a573-3a744178e7c9.png)

### Version

1.6.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
PR: https://github.com/Chia-Network/chia-blockchain-gui/pull/1309

**Comment by paninaro** [comment]
Closing since the fix has been merged into the release/1.7.0 and main branches
