### ISSUE TITLE
'CCWallet' object has no attribute 'cost_of_single_tx'

### ISSUE THREAD

**Issue by soulmerge** [Chia-Network/chia-blockchain-gui#130]
I was experimenting with colored coins and I seem to have done something unexpected: Whenever I open the key associated with the CC Wallet, I get this error message. ('CCWallet' object has no attribute 'cost_of_single_tx') The message pops up exactly twice after opening the key and doesn't appear again after that. Not even if I open the CC Wallet.

**Comment by jespino** [comment]
This should be fixed in the PR merged in the `dev` branch. @soulmerge could you check if now works? If not, would you be able to re-create the wallet (or create a new one) and see if that works?

**Comment by mariano54** [comment]
Let's close now unless we see the issue again
