### ISSUE TITLE
White screen issue

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain-gui#1321]
I encountered the white screen issue while hitting a conflict while rebasing some commits, while running the GUI. I'm not sure if the errors here are relevant, but maybe there's a clue that can help resolve this for other users.

**Comment by paninaro** [comment]
![image](https://user-images.githubusercontent.com/339312/213024907-82387f5b-4775-4a6f-a766-17b30801b7b6.png)

**Comment by paninaro** [comment]
Console log:
[whitescreen_console.log](https://github.com/Chia-Network/chia-blockchain-gui/files/10439827/whitescreen_console.log)

**Comment by seeden** [comment]
This issue happened because the build was broken during rebase.
I added better UI behavior. It will allow you to continue but fail when changing the theme.
Production will always work fine.

Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/1329/files
