### ISSUE TITLE
[Bug] Can't select another profile on Profile Settings screen

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#1365]
### What happened?

Selecting another profile when you have multiple profiles on the profile settings screen doesn't work. I was trying to rename another profile, but I can't select it to update it.

![Screenshot 2023-01-26 at 11 04 47 AM](https://user-images.githubusercontent.com/93196638/214901649-2729f7f4-9bc9-4fd5-ab00-14e7b75ba139.png)

### Version

1.7.0 rc4

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Fixed with PR https://github.com/Chia-Network/chia-blockchain-gui/pull/1383
