### ISSUE TITLE
[Bug] Offer Notifications are not shown in the GUI

### ISSUE THREAD

**Issue by greimela** [Chia-Network/chia-blockchain-gui#1369]
### What happened?

When receiving an offer notification, I see the transaction coming in in the `Transactions` list, but the notification itself doesn't appear.

The dropdown under the bell stays empty.

When opening the console and enabling debug logging, I see the following log message, one per notification. We tried both Dexie and Spacescan offers.

### Version

1.7.0-rc4

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
chia-gui:useNotifications Failed to prepare notification +0ms Error: URL is not valid: 7b2276223a312c2274223a312c2264223a7b2275223a2268747470733a2f2f64657869652e73706163652f6f66666572732f444c6f34544179647179594b446d397853535a6b343563704c4737394d436b7a515a61424c56584641455555222c227068223a2265643339306439396630386331633464383961303039656338613536333565393136623564303265383462613665633661653462343237633836623562303633227d7d
    at fetchOffer.ts:15:11
    at d (fetchOffer.ts:2:1)
    at Generator.<anonymous> (fetchOffer.ts:2:1)
    at Generator.next (fetchOffer.ts:2:1)
    at Wx (fetchOffer.ts:2:1)
    at i (fetchOffer.ts:2:1)
    at fetchOffer.ts:2:1
    at new Promise (<anonymous>)
    at fetchOffer.ts:2:1
    at Rx (fetchOffer.ts:79:2)
```

**Comment by SlowestTimelord** [comment]
Not sure if part of the same issue but message coins I receive do not have a memo displayed in the GUI whereas my outgoing message coins do have a memo.

**Comment by esaung** [comment]
the offer notifications not showing in the GUI on the receiving side is a known issue that we are working on.
the memo's not showing on the receiving side is as designed currently. we will be making a future feature enhancement to show the memo on the receiving side of the transaction.

**Comment by esaung** [comment]
fixed in RC5
