### ISSUE TITLE
Pool points graph is backwards

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain-gui#1373]
### What happened?

One would expect that the most recent activity would be rendered right-to-left, I think.
![2023-01-26_22-40](https://user-images.githubusercontent.com/8990544/215014848-b9173595-cf1e-4bcf-9f6b-561e770b267e.png)
![2023-01-26_22-40_1](https://user-images.githubusercontent.com/8990544/215014854-7c3f2c30-9152-4eb7-aaa0-43750904dae8.png)
![2023-01-26_22-41](https://user-images.githubusercontent.com/8990544/215014859-dabe332c-4903-47c2-b0ba-2d75307ab692.png)

### Version

1.7.0-rc4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@lipalong can you take a look at the graphing code? I would start with the wallet balance graph and see if there's some common issue that also applies to the pool points.
