### ISSUE TITLE
[Bug] XCH to mojo visual treatment needs to be adjusted

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#1374]
### What happened?

when using the multi-select option for NFTs, to try and transfer multiple NFTs, the confirmation dialog shows fee in XCH and mojo and can use an improvement to better show that the 5m mojos is related to the 0.00005 TXCH fee. (see screenshot). the font treatment of the mojos should be like when you are entering an XCH amount.

![Screenshot 2023-01-26 at 11 20 36 PM](https://user-images.githubusercontent.com/93196638/215015678-88662828-318d-4a0b-92a7-ed4cb69b0e40.png)

### Version

1.7.0 rc4

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@rifeljm I don't see the PR for this one. Can you update this issue with the PR?
