### ISSUE TITLE
[Bug] Offer notifications - delete incoming offer doesn't work

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#1375]
### What happened?

When in wallet only mode, clicking on delete for a incoming offer, the offer isn't removed from the GUI.
![Screenshot 2023-01-27 at 12 39 08 AM](https://user-images.githubusercontent.com/93196638/215135710-8f1217ba-a87d-473d-aa4b-dd479af5acfd.png)

### Version

1.7.0 rc4

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
I believe this has been fixed. Need to re-test

**Comment by esaung** [comment]
fixed in RC5
