### ISSUE TITLE
[Bug] Error: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by jfawChia** [Chia-Network/chia-blockchain-gui#1396]
### What happened?

This error is displaying for the following wallet when navigating to Pooling Tab on Navigation bar. Before this error occurred I was completing a Claims Reward for a different wallet. Then navigated to a different wallet as listed in screen shot and encountered the following error. 

<img width="965" alt="Screen Shot 2023-01-31 at 2 39 06 PM" src="https://user-images.githubusercontent.com/105236411/215865524-47bcc804-6f62-4dec-a590-d6cc7e931050.png">

<img width="1301" alt="Screen Shot 2023-01-31 at 6 07 31 AM" src="https://user-images.githubusercontent.com/105236411/215865955-74dc6ab6-e517-4611-a396-d3fe38ee6eae.png">

### Version

1.7.0rc5

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Fixed with PR https://github.com/Chia-Network/chia-blockchain-gui/pull/1415
