### ISSUE TITLE
[Bug] Does a pre-existing plot nft from a previous version work, after version upgrade to newest build?

### ISSUE THREAD

**Issue by jfawChia** [Chia-Network/chia-blockchain-gui#1398]
### What happened?

Given I create an NFT plot on version 1.7.0-rc4 
And NFT plot displays on Plots page
When I upgrade to latest version 1.7.0-rc5 
And I navigate back to Plot page for wallet  
Then NFT Plot should display under Plotting section

A.R. NFT Plot is not available. 

### Version

1.7.0-rc5

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by jfawChia** [comment]
@paninaro was able to reproduce at least a part of the problem again. It appears that when I upgraded from the 1.7.0-rc4 the plot was not finish loading as seen in image. 
<img width="1868" alt="Screen Shot 2023-02-06 at 8 20 33 PM" src="https://user-images.githubusercontent.com/105236411/217124912-33393986-8b77-4f6c-863c-8d7ff37e2b83.png">

And when I upgraded to  1.7.0-rc5 that plot that I started didn't come over with the upgrade. see image below. So not totally sure if that is a bug or as designed. 

<img width="968" alt="Screen Shot 2023-02-06 at 8 27 27 PM" src="https://user-images.githubusercontent.com/105236411/217125111-bb870d34-c981-4671-baeb-e05ada9d7b1d.png">

**Comment by paninaro** [comment]
Ah ok, thanks for re-testing this. The behavior you've described is expected. Plotting isn't an operation that can be stopped and resumed, so the plot that you were creating in the old version was aborted and lost when you stopped the GUI and updated to the newer build. If the plotting job had completed successfully, I would expect that plot to included in the "Total Plots" count.

**Comment by paninaro** [comment]
Closing based on my last comment.
