### ISSUE TITLE
NFT Notification button appears on sell offer [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain-gui#1412]
### What happened?

Steps to reproduce:
1. Create an offer to sell an NFT you own
2. Share the offer on dexie
3. BUG: The button for "Notify Owner" appears. You are the owner; this button should not appear in this scenario.

Out of curiosity, I notified the owner and indeed received the notification in the same wallet. I accepted the offer and it was successful. So I sold an NFT to myself.

The main consequence of this (beyond end users being confused) is that if the offer is accepted, the royalty will be deducted.

### Version

release/1.7.0 branch

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
This issue has already been fixed and merged.
