### ISSUE TITLE
[Bug] error during create self pool

### ISSUE THREAD

**Issue by lipalong** [Chia-Network/chia-blockchain-gui#1423]
### What happened?

Steps:
1. On Pooling page, click "+ Add a Plot NFT"
2. Leave "Self pool" selected and click "Create"
3. Encounter this error:

<img width="762" alt="Screen Shot 2023-02-03 at 09 52 40" src="https://user-images.githubusercontent.com/13445722/216634458-b0402b1c-d9f1-4485-8868-80a0689fef40.png">

### Version

1.3.6-dev157

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by ChiaMineJP** [comment]
Are you sure the version is `1.3.6-dev157`?

**Comment by lipalong** [comment]
<img width="405" alt="Screen Shot 2023-02-03 at 10 57 10" src="https://user-images.githubusercontent.com/13445722/216648668-b1492736-01fb-4c05-9dc6-a42ef137f0e1.png">

**Comment by paninaro** [comment]
Thanks @lipalong, this was fixed by PR https://github.com/Chia-Network/chia-blockchain-gui/pull/1415
