### ISSUE TITLE
[Bug] Multi-select Icon is somehow thinner than what was designed. 

### ISSUE THREAD

**Issue by sethjenks** [Chia-Network/chia-blockchain-gui#1438]
### What happened?

Please Fix

![CleanShot 2023-02-03 at 21 55 44@2x](https://user-images.githubusercontent.com/663017/216749592-24425216-8bad-4ec4-8ff3-aca21ac78bc8.png)

### Version

1.7.0-rc5

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Fixed in main
