### ISSUE TITLE
scenario where counter offer cannot be accepted [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain-gui#1442]
### What happened?

The following scenario occurs with offer notifications in 1.7 due to the coinset model. To simplify this flow, let's assume Alice doesn't need to pay any blockchain fees, or fees for sending offer notifications.

- Alice has 1 coin in her wallet, worth 0.6 XCH
- Alice makes an offer to buy an NFT for 0.5 XCH
- Alice sends a notification to Bob, who owns the NFT
- Bob sees the offer and makes a counter-offer to sell his NFT for 0.6 XCH
- Alice attempts to accept the counter-offer

Alice has 0.6 XCH in her wallet, so the counter-offer should go through. However, her original offer is still valid, and it has already reserved the only coin in her wallet. She therefore receives an error that her balance is insufficient to accept the offer. One potential way to fix this would be to automatically cancel the original offer (off-chain) when a counter offer is accepted.

### Version

1.7.0rc6

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by danieljperry** [comment]
Keeping this issue open.

**Comment by paninaro** [comment]
Closing this. Fix is currently in the 1.7.1 RC builds. Conflicting offers will now be displayed in a new dialog when attempting to create a new offer.
