### ISSUE TITLE
[Bug] gui screen/window goes white after being open for several days

### ISSUE THREAD

**Issue by RightSexyOrc** [Chia-Network/chia-blockchain-gui#1472]
### What happened?

underlying node (chia-blockchain) still seems to be working but gui window is white and clicking/resizing/minimizing doesn't make a difference

i've reproduced this behavior on multiple ubuntu machines

feels like a memory leak kind of thing/behavior

### Version

1.6.2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Thanks for the report. We're tracking this with an existing bug https://github.com/Chia-Network/chia-blockchain-gui/issues/1275
