### ISSUE TITLE
Last proof attempted

### ISSUE THREAD

**Issue by loppefaaret** [Chia-Network/chia-blockchain-gui#149]
any chance of having the last attempted proof pane, under the farming tab having the option of showing more than the last 5 ?
its a wonderfull tool for reassuring how the farming has been over a period of time, and that period of time being currently less than a minute is short ?
![image](https://user-images.githubusercontent.com/32275244/110824053-fa3bef00-8292-11eb-93ea-796428d3a6c0.png)
if it could be expanded like the latest block challenges below it, rows per page, and pages - that would be an effective way for gui farmers to give an overview...

**Comment by mariano54** [comment]
Those two tables need to be merged since they show the same thing

**Comment by lvcivs** [comment]
Instead of making the table longer, I'd suggest to show some sort of summary statistic: 
```
In last 2h: 16 plots passed, 2 proofs found
In last 24h: 62 plots passed, 8 proofs found 
```
