### ISSUE TITLE
[Bug] Incorrectly Marked Objectionable NFTs

### ISSUE THREAD

**Issue by L4bb3rs** [Chia-Network/chia-blockchain-gui#1493]
### What happened?

NFTs are being marked objectionable that have no marking of objectionable in meta?

### Version

1.7.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
#14644

**Comment by MumfMeisterT** [comment]
#1510

**Comment by emlowe** [comment]
closing
