### ISSUE TITLE
[Bug] Error displayed when trying disconnect walletconnect from wallet

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#1497]
### What happened?

Tried the disconnect option after being connected to Dexie and Taichiadao, and both ways to disconnect result in an error.

![Screenshot 2023-02-23 at 4 18 54 PM](https://user-images.githubusercontent.com/93196638/221043914-4a74c41f-3d7a-4025-b8f8-b8c600b33043.png)

### Version

1.8.0 b1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
This issue is related to wallet connect relay server. We are not able to do anything
