### ISSUE TITLE
[Bug] Closing the GUI often logs out Ubuntu

### ISSUE THREAD

**Issue by racergoodwin** [Chia-Network/chia-blockchain-gui#1502]
### What happened?

Observed behaviour:
More often than not, while logged in via RDP, when shutting down the GUI using File>quit it appears to shut down perfectly. Ubuntu seems to be operating as expected for a few seconds and is still usable, then all of a sudden it logs out, closing the remote connection.
I am forced to then SSH into the machine and reboot it in order to be able to control it remotely again.
Logging back in again I am presented with the window that there has been an error and to report it to the devs, which I do.

It doesn't matter if I am using RDP via a local network or over the internet via WireGuard.

Expected behaviour:
Shut down the GUI using File>Quit, all aspects of Chia shutdown and Ubuntu keeps running without logging out.

### Version

1.7.0

### What platform are you using?

Linux - Ubuntu 22.04 though it also happens in several other versions

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
This sounds like the windows manager crashing/closing, but there is nothing that an application can do to close a windows manager. This sounds like an operating system or hardware issue. 
You could try using a different machine with different hardware and see if this persists.

**Comment by racergoodwin** [comment]
Thanks for your input.
This has been a persistent problem since Ubuntu 18.04 LTS, through Ubuntu 20.04 LTS and now into Ubuntu 22.04 LTS, with most of the major releases of the GUI. It hasn't mattered whether the OS has been updated from one version to another, or a clean install.
Hardware has been all Dell servers, R710, R620, R730. They have been dedicated to Chia, with nothing else running on them.
I have previously reported this issue and it was dismissed then too.
