### ISSUE TITLE
Missing question mark in dialog

### ISSUE THREAD

**Issue by ordtrogen** [Chia-Network/chia-blockchain-gui#153]
(sorry for reporting these pesky details as I know you're bogged down in big things like shipping mainnet :-) )

The "Are you sure ..." part should have a ?

![Skärmavbild 2021-03-12 kl  18 54 38](https://user-images.githubusercontent.com/15184875/110979171-8d912500-8364-11eb-96d7-7520ca5b2430.png)

**Comment by seeden** [comment]
changed via https://github.com/Chia-Network/chia-blockchain-gui/pull/171
thanks
