### ISSUE TITLE
Valid but process locked plot files marked as failed in GUI while being written.

### ISSUE THREAD

**Issue by StogieC** [Chia-Network/chia-blockchain-gui#159]
While transferring plots from a remote Plotter to their final, harvester accessible drive, the GUI marks the plot as "Failed to open (invalid plots)" and prompts: "These plots are invalid, you might want to delete them."

Clearing the failed list requires a GUI restart after the fire write has completed.  Please consider not marking plots as failed until they have failed access attempts/checks for some period of time (30 min), at least with enough time to write the file via LAN (~15 min. on a 1Gbps network with fast storage).

Alternatively, reevaluate the "Failed" state with a manual a re-check or the current "Refresh Plots" function.

![image](https://user-images.githubusercontent.com/34588931/111057356-ecce6280-8454-11eb-9898-4adaac4dd2e2.png)

**Comment by StogieC** [comment]
23:46:54.513  src.plotting.check_plots         : INFO     Summary
23:46:54.513  src.plotting.check_plots         : INFO     Found 1 valid plots, total size 0.09901 TiB
23:46:54.514  src.plotting.check_plots         : INFO     1 plots of size 32

**Comment by hoffmang9** [comment]
Harvester intentionally tries to both ignore files that are probably still copying by size but there is still a window where a valid plot is almost copied but not quite yet. If you wait a bit ~25 minutes - it will find it legit then and start farming it.

**Comment by StogieC** [comment]
The plot remains in the failed list until GUI restart.  Not 25 Min...

**Comment by StogieC** [comment]
![image](https://user-images.githubusercontent.com/34588931/111079890-7112fb00-84d2-11eb-8d8a-96a6cecee28a.png)

**Comment by wjblanke** [comment]
Its probably a GUI refresh issue. To help us debug, if you go to Keys and reselect your same key, is the GUI still showing incorrectly?

**Comment by StogieC** [comment]
The debug log shows the plot being found valid ~20 min later, but the GUI is not updating.

13:26:07.206 harvester src.plotting.plot_tools : ERROR    Failed to open file \\<server>\Chia\ChiaPlots\plot-k32-2021-03-14-05-30-ef51cf68ec53d4748ee39921199eaa7b2b652e437df1b60f10e44b8b7f1ddb65.plot. Invalid file \\Tabularium\Chia\ChiaPlots\plot-k32-2021-03-14-05-30-ef51cf68ec53d4748ee39921199eaa7b2b652e437df1b60f10e44b8b7f1ddb65.plot Traceback (most recent call last):
  File "src\plotting\plot_tools.py", line 182, in load_plots
ValueError: Invalid file \\<server>\Chia\ChiaPlots\plot-k32-2021-03-14-05-30-ef51cf68ec53d4748ee39921199eaa7b2b652e437df1b60f10e44b8b7f1ddb65.plot

13:47:13.719 harvester src.plotting.plot_tools : INFO     Found plot \\<server>\Chia\ChiaPlots\plot-k32-2021-03-14-05-30-ef51cf68ec53d4748ee39921199eaa7b2b652e437df1b60f10e44b8b7f1ddb65.plot of size 32

**Comment by StogieC** [comment]
Still there after reselecting key.

**Comment by wjblanke** [comment]
OK good info well check on it

**Comment by StogieC** [comment]
Noteworthy, the Synology NAS, and many others, immediately allocates drive space to the file at the start of a transfer, so it reports its full file size back to the OS rather than using a .part file or showing as under sized while the file is "in flight". This would negate the Harvester's file size check while the file is being actively written.

**Comment by StogieC** [comment]
While you're looking at this GUI section, The "Rows per page" and < > Left/Right Buttons are also not functioning.

![image](https://user-images.githubusercontent.com/34588931/111184676-9281ee80-8587-11eb-8803-c9df08245c51.png)

**Comment by kid26** [comment]
Works for me after waiting 25mins without restarting the GUI..
