### ISSUE TITLE
[Bug] 1.8.0b4-dev30 GUI continues to report invalid metadata URI for NFT after valid one added

### ISSUE THREAD

**Issue by andyharless** [Chia-Network/chia-blockchain-gui#1593]
### What happened?

I bought an NFT which turned out to have an invalid metadata URI. I found a correct URI and verified using curl and sha256sum that it hashes to the correct value. I added the new URI to the NFT. The GUI continues to report "Invalid metadata url" (on top of the NFT image) and "Title Not Available." (I'm not certain this is a bug, but that's what pyl in the Keybase support channel seemed to think, and I do think it would make sense to use the most recently added URI to ascertain validity and extract metadata to display, since there's always a risk of data at an old URI getting corrupted.)

I presume this can be reproduced by minting an NFT, changing the data at the original metadata URI, and adding a new URI that points to a good copy of the original metadata. But I haven't tried that yet.

### Version

1.8.0b4-dev30

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
Can you try with the latest 1.7.1 RC build?
https://github.com/Chia-Network/chia-blockchain/releases/tag/1.7.1-rc2

**Comment by andyharless** [comment]
This is a bit strange. The specific original problem seems to be gone in 1.7.1-rc2, but in the mean time, I had bought another NFT for which Chia also says "invalid metadata url" even though the link seems to generate the correct hash, and in this case RC2 is still complaining, even after clearing the cache.

**Comment by esaung** [comment]
if you hit the refresh metadata option, does it clear the "invalid metadata url" warning?

**Comment by andyharless** [comment]
I don't see a refresh metadata option

**Comment by blupino** [comment]
I saw this issue with one of the NFT in 1.7.0, and refreshing the NFT data few times can solve it

**Comment by blupino** [comment]
Ok I think 1.7.1rc2 fix this issue. I have been using 1.8.0b3 these few days buying nft like maybe 10, and all have this issue on 1.8.0b3. But just now I bought 1 using 1.7.1rc2 and without this issue

**Comment by seeden** [comment]
fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/1730 it will be part of 1.8.1
