### ISSUE TITLE
[BUG] Blocks farmed with pool contract puzzle hash cannot be displayed

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain-gui#167]
There are two types of plots in chia, pool public key and pool contract puzzle hash. Some blocks will not have pool public key at all. 
Users up to now have been using pool public keys plots, so we didn't notice this bug.
More info here: 
https://github.com/Chia-Network/chia-blockchain/wiki/Chia-Keys-Architecture

These blocks currently cannot displayed in the UI.
![Screenshot from 2021-03-15 20-35-18](https://user-images.githubusercontent.com/3069354/111147842-43ab7780-85ce-11eb-8edd-673562aab6ec.png)

**Comment by seeden** [comment]
fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/274
