### ISSUE TITLE
[Bug] Unable to Disconect WalletConnect dApp

### ISSUE THREAD

**Issue by Rigidity** [Chia-Network/chia-blockchain-gui#1681]
### What happened?

Often I've tried to disconnect a dApp linked using WalletConnect, and nothing happens. No error is reported, such as in #1497, rather it silently fails. I've noticed that this tends to happen if you keep the wallet open a while after linking the dApp.

The problem goes away after restarting the wallet GUI. I have no idea what causes this or how to reproduce it beyond the above.

### Version

1.7.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
There is a problem with broken WalletConnect JWT token after 24 hours. It should be fixed in next release

**Comment by paninaro** [comment]
Please retest with the 1.8.0rc2 build when it's available

**Comment by paninaro** [comment]
Closing this as the update to WC 2.6.0 seems to properly address this issue.
