### ISSUE TITLE
[Bug] Cannot sign with DID through walletconnect

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#1718]
### What happened?

In discord, using the DID verifier bot, the process of verifying the DID through walletconnect on 1.8.0rc3 is not working. Not getting the confirmation prompt in the wallet when trying to connect.

### Version

1.8.0rc3

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
RC3 uses version 2.7.0 of the walletconnect SDK. I found that versions > 2.6.0 don't handle any WC requests from a dapp. The linked PR downgrades the SDK to 2.6.0 which I've verified works with the test dapp (including signing via DID).
