### ISSUE TITLE
[Bug] Scrollbar only works via mouse wheel

### ISSUE THREAD

**Issue by bramv-chia** [Chia-Network/chia-blockchain-gui#1720]
### What happened?

![scrollbar_issue_GUI](https://user-images.githubusercontent.com/116583441/234676935-9ce51d89-b567-4fae-bb5e-02981cdaaf66.png)
The mouse can't grab the scrollbar.. mousewheel can still scroll the list up/down

### Version

1.8.0rc3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
I am not able to reproduce it in my latest version

**Comment by bramv-chia** [comment]
@seeden 
did you try to replicate when the [Manage Token List] is expanded?
