### ISSUE TITLE
[Bug] NFT displayed is incorrect

### ISSUE THREAD

**Issue by bramv-chia** [Chia-Network/chia-blockchain-gui#1721]
### What happened?

![wrong_nft_displayed](https://user-images.githubusercontent.com/116583441/234677190-81ff59bf-46a0-436b-8226-d564aa714647.png)
The NFT displayed is incorrect
once you click into the NFT properties, the correct image is shown
once you return to the NFT overview listing, the correct image is shown

### Version

1.8.0rc3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/1730 it will be part of 1.8.1
