### ISSUE TITLE
[Bug] The option to show "hidden" NFTs is reset to CHECKED 

### ISSUE THREAD

**Issue by bramv-chia** [Chia-Network/chia-blockchain-gui#1722]
### What happened?

![hidden_nfts](https://user-images.githubusercontent.com/116583441/234677578-01ffbad9-97cf-495b-a129-4390711d676b.png)
The option to show "hidden" NFTs is reset to CHECKED regardless if UNCHECKED before <-- state is not stored.

The result is that each time you visit the NFT overview, "hidden" NFTs are shown.

### Version

1.8.0rc3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/1730 it will be part of 1.8.1
