### ISSUE TITLE
Farming Page fees is wrong

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain-gui#18]
On the farming page, the breakdown between fees and farming rewards is not correct. 
There are two coins for each block: Pool coin and farmer coin. 

The pool coin is block_rewards(height) * 7/8. 
The farmer coin is block_rewards(height) * 1/8 + fees

The breakdown on the farmer page should probably show all three amounts:
pool amount
farmer amount
fees amount

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/56
