### ISSUE TITLE
Show some indicator of progress when plotting

### ISSUE THREAD

**Issue by mikeindustries** [Chia-Network/chia-blockchain-gui#187]
Just had a situation where after a day of plotting, nothing had finished yet, so I checked the logs. Bunch of errors and no progress since the first few minutes of the plotting. To eliminate this sort of thing, it would be great to have something like the following:

1. Status changes to "Plotting - Errors Occurring" if there hasn't been any progress for, say, 15 minutes.
2. Not sure if it's possible for the app to know what percentage complete a plot is, but if so, would be great to turn that Status bar into a progress indicator. Would probably Go with gray background and yellow/orange indicator bar.

**Comment by seeden** [comment]
PR already merged https://github.com/Chia-Network/chia-blockchain-gui/pull/197
