### ISSUE TITLE
Doesn't anyone think this is an issue?

### ISSUE THREAD

**Issue by nongyehezuoshe** [Chia-Network/chia-blockchain-gui#1873]
Doesn't anyone think this is an issue?

_Originally posted by @nongyehezuoshe in https://github.com/Chia-Network/chia-blockchain-gui/issues/1799#issuecomment-1606146149_

**Comment by seeden** [comment]
@nongyehezuoshe please describe what is wrong there. I trying hard, but I do not understand your point

**Comment by paninaro** [comment]
@nongyehezuoshe is the issue that the time isn't shown in 24-hour time? In your screenshot, you have the block time shown as "12:21 AM" and your local system time (in 24 hour time) shows 0:21.
