### ISSUE TITLE
When I run "npm run electron &" , I got a "Errno 99"

### ISSUE THREAD

**Issue by ZhangMing520** [Chia-Network/chia-blockchain-gui#188]
/home/ubuntu/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
/home/ubuntu/chia-blockchain/app.asar.unpacked/daemon
false
/home/ubuntu/chia-blockchain/app.asar.unpacked/daemon
false
Running python script
Script ../src/daemon/server.py
child process success
(node:7514) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Have cert
stderr: Traceback (most recent call last):
  File "../src/daemon/server.py", line 1003, in <module>
    main()
  File "../src/daemon/server.py", line 999, in main
    return run_daemon(DEFAULT_ROOT_PATH)
  File "../src/daemon/server.py", line 993, in run_daemon
    return asyncio.get_event_loop().run_until_complete(async_run_daemon(root_path))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "../src/daemon/server.py", line 985, in async_run_daemon
    await ws_server.start()
  File "../src/daemon/server.py", line 142, in start
    self.websocket_server = await serve(
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, error while attempting 
OSError: [Errno 99] error while attempting to bind on address (::1, 55400, 0, 0): cannot assign requested address
closing code: 1

**Comment by hoffmang9** [comment]
Did you run chia init and are you sure you don't have a version of the app already running?

**Comment by ZhangMing520** [comment]
At the beginning I run use root , and then I change to ubuntu user , I have run chia init

**Comment by ZhangMing520** [comment]
I deploy use this 
![Uploading image.png…]()

**Comment by ZhangMing520** [comment]
I  download src/daemon/server.py , I think "Error loading config - using defaults" is main reason

**Comment by hoffmang9** [comment]
Electron does not allow itself to be run as root. Your ~/.chia directory is probably in root and not in your ubuntu/user directory.

**Comment by ZhangMing520** [comment]
I have deployed another use ubuntu user , and remove root  "chia-blockchain"

**Comment by ZhangMing520** [comment]
I deployed totally use ubuntu user

**Comment by ZhangMing520** [comment]
I hava another question: If I don't have graphic interface， “run npm electron &” will run error or not ?

**Comment by hoffmang9** [comment]
Electron requires e.g. Ubuntu Desktop.

**Comment by ZhangMing520** [comment]
After run sudo apt install gnome-session gdm3  . Is this ok ?

**Comment by ZhangMing520** [comment]
I use "sudo apt install gnome-session gdm3 " install graphic interface

**Comment by hoffmang9** [comment]
OS support isn't here so dunno.

**Comment by ZhangMing520** [comment]
Your team have use this tutorial("https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian") to deploy successfully?

**Comment by ZhangMing520** [comment]
graphic interface has installed , Has nothing to do with os

> OS support isn't here so dunno.

**Comment by ZhangMing520** [comment]
In tutorial， “chia init” not contains, Does your team check the latest tutorial


> Did you run chia init and are you sure you don't have a version of the app already running?
