### ISSUE TITLE
Remove expected time to win from the GUI

### ISSUE THREAD

**Issue by shaneo257** [Chia-Network/chia-blockchain-gui#189]
Hi Chia Team,

Can we please remove the Expected Time to Win, as its causing much angst with the people on keybase, as they're expecting to get a block every x hours/days it says, when we know its a lottery and its a rough guesstimate

**Comment by justinengland** [comment]
Hey! We just discussed this on standup. 

We think that we should change the tool tip here to link to the wikipedia article https://en.wikipedia.org/wiki/Expected_value

as well as change the wording of the tooltip with the link 

"You have X% of space on the network, this is an estimated time to win, actual results may be 3x this estimate. https://en.wikipedia.org/wiki/Expected_value"

**Comment by shaneo257** [comment]
Hey Justin

Sounds good, also changing the wording on the GUI/CLI to Estimated Time to Win would be good to reiterate it as well

**Comment by O1O1O1O** [comment]
Surely "estimated" isn't right either, it's just average.  Really nothing short of a full blown simulation of binomial distribution and a run down of basically probability theory will work :-). Maybe a note specify the probability of not winning at 2x, 3x, 4x that average time will help get the message through?
