### ISSUE TITLE
[BUG] Missing dependencies with GUI

### ISSUE THREAD

**Issue by camp0** [Chia-Network/chia-blockchain-gui#190]
**Describe the bug**
While executing the command npm run electron some dependencies packages in python are missing, one is websocket that is easiliy solve by installing it "pip install websocket" but later there is a path dependencies that is failing.

Running python script
Script ../src/daemon/server.py
child process success
(node:2940) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
stderr: Traceback (most recent call last):
  File "/home/luis/repositories/chia-blockchain/chia-blockchain-gui/../src/daemon/server.py", line 18, in <module>
stderr:     from src.cmds.init import chia_init
ModuleNotFoundError: No module named 'src'
closing code: 1

**To Reproduce**

1. Go to 'cd chia-blockchain-gui'
2. Click on 'run npm run electron.'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Fedora33
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by seeden** [comment]
@camp0 there is no visible error. Can you share more information? Debug log or something else? Thank you
