### ISSUE TITLE
GUI Bitfield help text

### ISSUE THREAD

**Issue by shaneo257** [Chia-Network/chia-blockchain-gui#193]
In the GUI, Plotting screen, near Disable Bitfield plotting, it should have some help text ie If using SSD as Temp, tick to disable, if using HDD, leave unticked

![image](https://user-images.githubusercontent.com/36589806/110947896-72d2a680-838c-11eb-8b53-84647d5c15ea.png)

**Comment by hoffmang9** [comment]
![image](https://user-images.githubusercontent.com/30377676/112181818-fb85e980-8bb9-11eb-803b-00b99c0f817e.png)
Closing because already fixed?
