### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'emoji')

### ISSUE THREAD

**Issue by mikesmith2107** [Chia-Network/chia-blockchain-gui#1978]
### What happened?

Error: Cannot read properties of undefined (reading 'emoji')
at webpack://@chia-network/gui/src/components/addressbook/MyContact.tsx:41:66 emoji
at webpack://@chia-network/gui/src/components/addressbook/MyContact.tsx:39:17 forEach
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:262:358 fk
at webpack://node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:122:324 eg
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:261:307 ek
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:261:214 ek
at webpack://node_modules/scheduler/cjs/scheduler.production.min.js:16:223 V
at webpack://node_modules/scheduler/cjs/scheduler.production.min.js:12:345 k

### Version

latest

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'emoji')

URL
#/dashboard/addressbook

Stacktrace
at webpack://@chia-network/gui/src/components/addressbook/MyContact.tsx:41:66 emoji
at webpack://@chia-network/gui/src/components/addressbook/MyContact.tsx:39:17 forEach
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:262:358 fk
at webpack://node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:122:324 eg
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:261:307 ek
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:261:214 ek
at webpack://node_modules/scheduler/cjs/scheduler.production.min.js:16:223 V
at webpack://node_modules/scheduler/cjs/scheduler.production.min.js:12:345 k
```

**Comment by paninaro** [comment]
This should be fixed in 2.0.0-rc6
