### ISSUE TITLE
Wallet balances are not refreshed

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain-gui#20]
When making a transaction to myself (or farming a coin), sometimes the wallet balance is incorrect. It seems like it's not fully refreshed. When I refresh the page, it corrects itself. If this is a problem in the backend, let me know.

**Comment by seeden** [comment]
@mariano54 we are refreshing all values always when UI received state: pending_transaction, coin_added, or coin_removed
Do we have any other events? If not please verify it on the backend side.

**Comment by seeden** [comment]
This will be fixed with refactored RPC
