### ISSUE TITLE
[Bug] VCs - Rename "Coin ID" label to "Launcher ID"

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#2001]
### What happened?

After minting a VC, the GUI shows "Coin ID", but the value being shown is the launcher ID when comparing to the CLI output.

![Screenshot 2023-08-14 at 8 21 10 AM](https://github.com/Chia-Network/chia-blockchain-gui/assets/93196638/03329b79-27c6-4121-ba53-23583c7b8d31)

desired behavior is to show both the Coin ID and the Launcher ID

### Version

2.0.0rc4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@rifeljm Can you make sure that the launcher ID is labeled "Launcher ID". If it's not too difficult, we should also show the "Coin ID" representing the current coin for the VC.

**Comment by paninaro** [comment]
Didn't make it into 2.0.0. Targeting 2.1.0 now
