### ISSUE TITLE
[Bug] expiring offers - text for days, hours, minutes not showing up correctly

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#2092]
### What happened?

When showing Days, Hours, Minutes to set for expiring offers, the content is showing random characters.
<img width="1425" alt="Screenshot 2023-09-14 at 11 48 18 AM" src="https://github.com/Chia-Network/chia-blockchain-gui/assets/93196638/834033f9-5700-48ed-8f03-ce78a18a5ea9">

### Version

2.1.0rc1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Chris is fixing up the crowdin integration. This should be resolved by including the latest compiled strings.
