### ISSUE TITLE
npm run electron & error "no such file or directory, open '/home/user/chia-blockchain/package.json'" with Ubuntu 18/20

### ISSUE THREAD

**Issue by danix4u** [Chia-Network/chia-blockchain-gui#210]
I have installed Ubuntu 18 and also 20 and still have the below error, I used non root username and installed GUI before I did the npm run command and still not going through, I have tried CENTOS the same issue but different error. What GUI we shouls use with this? I used Xubuntu and xfce4, I I burned more than 2 days and I installed Linux with different version more than 10 times.

Error:

(venv)user@ns529:~/chia-blockchain$ npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/user/chia-blockchain/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/user/chia-blockchain/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-03-28T16_27_58_202Z-debug.log

[1]+  Exit 254                npm run electron
(venv) user@ns5329:~/chia-blockchain$

log for /home/user/.npm/_logs/2021-03-28T16_27_58_202Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose stack Error: ENOENT: no such file or directory, open '/home/user/chia-blockchain/package.json'
5 verbose cwd /home/user/chia-blockchain
6 verbose Linux 4.15.0-140-generic
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "electron"
8 verbose node v14.16.0
9 verbose npm  v6.14.11
10 error code ENOENT
11 error syscall open
12 error path /home/user/chia-blockchain/package.json
13 error errno -2
14 error enoent ENOENT: no such file or directory, open '/home/user/chia-blockchain/package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -2, true ]

**Comment by hoffmang9** [comment]
It appears this is only working in Unity.

**Comment by danix4u** [comment]
I tried Unity also, below is the error:

(venv) user@ns511329:~/chia-blockchain/chia-blockchain-gui$ npm run electron &
[1] 10802
(venv) user@ns511329:~/chia-blockchain/chia-blockchain-gui$
> chia-blockchain@ electron /home/user/chia-blockchain/chia-blockchain-gui
> electron .

/home/user/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
The futex facility returned an unexpected error code./home/user/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron exited wi                                          th signal SIGABRT
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-03-29T02_57_29_905Z-debug.log

[1]+  Exit 1                  npm run electron

**Comment by seeden** [comment]
There is no package.json in the chia-blockchain directory. GUI is inside chia-blockchain-gui directory.

**Comment by danix4u** [comment]
Here you go:

 nano 2021-03-29T02_57_29_905Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@
6 info lifecycle chia-blockchain@~electron: chia-blockchain@
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/chia-$
9 verbose lifecycle chia-blockchain@~electron: CWD: /home/user/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]
11 silly lifecycle chia-blockchain@~electron: Returned: code: 1  signal: null
12 info lifecycle chia-blockchain@~electron: Failed to exec electron script
13 verbose stack Error: chia-blockchain@ electron: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid chia-blockchain@
15 verbose cwd /home/user/chia-blockchain/chia-blockchain-gui
16 verbose Linux 4.15.0-140-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "electron"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE


I am installing ubuntu on a remote server with no GUI, if Chia team can tell us what are the exact commands to install the right GUI they use, and XDRP, that will solve the issue.

**Comment by danix4u** [comment]
> 
> 
> There is no package.json in the chia-blockchain directory. GUI is inside chia-blockchain-gui directory. (it is related to [#210 (comment)](https://github.com/Chia-Network/chia-blockchain-gui/issues/210#issue-842775335))
> 
> Can you share your 2021-03-29T02_57_29_905Z-debug.log?

See my reply.

**Comment by danix4u** [comment]
@seeden Do you have a solution for my npm run electron & errors ?

**Comment by seeden** [comment]
@danix4u  can you check the latest version? whole starting script of electron application was changed
