### ISSUE TITLE
Button dedicated to Kiwi in the GUI [Enhancement]

### ISSUE THREAD

**Issue by shaneo257** [Chia-Network/chia-blockchain-gui#2115]
### What happened?

User Cookie has made a suggestion in the Chia discord `Question for Chia Team. Can there be a button in Chia GUI dedicated to kiwi?` https://discord.com/channels/1034523881404370984/1034523882268401676/1151729281915961395

Submitting a Git request so that it doesn't get lost

### Version

2.0.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by xchguideofficial** [comment]
I second this !!

**Comment by xchguideofficial** [comment]
I'm thinking like a wiki style page achievements work etc..
