### ISSUE TITLE
Title bar UI Changes [Bug] 

### ISSUE THREAD

**Issue by sethjenks** [Chia-Network/chia-blockchain-gui#2127]
- [x] #2130
- [x] #2132
- [ ] #2133
- [x] #2134
### Change the shape of the logout hover item to be a rounded rectangle instead of a circle to fit the other items. 

<img width="132" alt="CleanShot 2023-09-18 at 15 36 01@2x" src="https://github.com/Chia-Network/chia-blockchain-gui/assets/663017/1ddbe6c4-7391-4d56-af8c-79579bf30df6">
<img width="156" alt="CleanShot 2023-09-18 at 15 36 07@2x" src="https://github.com/Chia-Network/chia-blockchain-gui/assets/663017/4c07fbb4-8602-4a4f-950b-bcf1cc67f6be">

---

### Icon Does not show the current wallet theme color when hovered. It also shows the wrong kind of cursor. Text input cursor instead of the gloved hand.

<img width="278" alt="CleanShot 2023-09-18 at 15 40 22@2x" src="https://github.com/Chia-Network/chia-blockchain-gui/assets/663017/9aae4ce3-31bf-4380-998f-c7bf07514781">

---

### The color selection values do not reflect the actual color values. They are set separately. It would be great if they were set based on the same constant value. 

<img width="417" alt="CleanShot 2023-09-18 at 15 43 04@2x" src="https://github.com/Chia-Network/chia-blockchain-gui/assets/663017/70c75f4f-7fb8-4fd7-9d3d-231fb9f48c1f">

---

### The height of the Node and Wallet buttons should be the same. 

<img width="1166" alt="CleanShot 2023-09-18 at 15 47 47@2x" src="https://github.com/Chia-Network/chia-blockchain-gui/assets/663017/04f2e668-aae6-466a-86db-8c64d9e2c63b">

---

### Version

2.1.0-RC1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
- [ ] Update logout button
- [ ] Update emoji hover state
- [ ] Update color/emoji picker drop shadow
- [ ] Update height of full node / wallet status buttons

**Comment by paninaro** [comment]
Closing with the exception of the #2133
