### ISSUE TITLE
Error viewing expiring Offer notification [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain-gui#2175]
### What happened?

I created an NFT-NFT offer with a standard 7-day expiration. Here is the Offer file:

[1_nft1j3rjeyqcahhqjk5sv3ve5p62pcqvpf855tvfxqzhs43cmvnlkg5su0e5p9_x_1_nft19xkl7yrtth6anp55q8zwgpjqewfh556r7at6kxstx3r93vazwj6s9lvgmy.zip](https://github.com/Chia-Network/chia-blockchain-gui/files/12734372/1_nft1j3rjeyqcahhqjk5sv3ve5p62pcqvpf855tvfxqzhs43cmvnlkg5su0e5p9_x_1_nft19xkl7yrtth6anp55q8zwgpjqewfh556r7at6kxstx3r93vazwj6s9lvgmy.zip)

I posted this offer to Dexie, then sent a notification to the owner. From the potential taker's wallet (the wallet that owns nft19xkl7), the notification pops up, and when I click it to view the offer, the GUI crashes with the following error:

![notificationerror](https://github.com/Chia-Network/chia-blockchain-gui/assets/69756004/4c70b1c0-a27c-4eeb-a29f-305ea87c48f0)

### Version

2.1.0-rc3 on testnet10

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
I didn't see any errors in the log.
```

**Comment by danieljperry** [comment]
I get the same error on an XCH-for-NFT offer, so it seems likely this is happening because the offer has an expiration time.

**Comment by danieljperry** [comment]
Update: the error does not appear with a non-expiring offer notification.

**Comment by paninaro** [comment]
Thanks for reporting @danieljperry. This was happening because of an incorrect code path when viewing a counterable offer (which is limited to offer notifications).

**Comment by paninaro** [comment]
Fixed in 2.1.0-rc4
