### ISSUE TITLE
Offer is both expired and completed [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain-gui#2183]
### What happened?

When viewing an expired offer, the status is displayed as "completed successfully":

![expired_completed](https://github.com/Chia-Network/chia-blockchain-gui/assets/69756004/1ff1d507-8b58-4a17-b932-07ff2e2e312a)

### Version

2.1.0rc3 (binary installation)

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@lipalong Can you take a look at this issue? Seems like we can safely skip displaying the "Offer has expired" state if the offer has completed (either successfully or in failure).

**Comment by danieljperry** [comment]
In this case the offer was never completed. It was only expired.

**Comment by paninaro** [comment]
I'm not able to repro this. @danieljperry can you reopen it if you still see this issue?

**Comment by danieljperry** [comment]
I was unable to reproduce this on 2.1.0, so I'll leave the issue closed.
