### ISSUE TITLE
Browsing to open offer fails [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain-gui#2184]
### What happened?

When I attempt to view an offer by clicking `browse` in the GUI, I receive this error: `ENOENT: no such file or directory, stat ''`

However, when I drag and drop an offer file from an explorer window, it opens as expected. Both of these cases are shown in the following video:

https://github.com/Chia-Network/chia-blockchain-gui/assets/69756004/d0d82793-72fd-407e-9eb1-dff11c9c8562

### Version

2.1.0rc3 (binary installation)

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@lipalong Can you take a look at this one? I can repro in 2.1.0-rc4. We can apply a fix to `main`
