### ISSUE TITLE
[Bug] DFT  not found in pool overview

### ISSUE THREAD

**Issue by liyujcx** [Chia-Network/chia-blockchain-gui#2207]
### What happened?

**My dft not found in pool overview**

![image](https://github.com/Chia-Network/chia-blockchain/assets/129054818/15c4a209-6376-4143-86df-6c3abace4d84)

Find dft in cmdline

![image](https://github.com/Chia-Network/chia-blockchain/assets/129054818/8b986c68-6dd9-44f6-8ff3-d42469d86fb4)

plots are ok
![image](https://github.com/Chia-Network/chia-blockchain/assets/129054818/f2bf9316-110e-4f3b-8998-cc66feb47cda)

### Version

2.0.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@liyujcx can you try running `chia rpc farmer get_pool_state` from command line (powershell or command prompt)? I'm wondering if the plot nft will appear in that listing.

Also check your `config.yaml` file and look at the `pool_list` section, as I believe that's where the list of plot NFTs is coming from.

**Comment by emlowe** [comment]
closing
