### ISSUE TITLE
[Bug] Completed transactions are shown as "Pending Accept" 

### ISSUE THREAD

**Issue by Muffexx** [Chia-Network/chia-blockchain-gui#2223]
### What happened?

Hey.

I have several offers that are shown as "Pending Accept" although they have already been completed. Resyncing the wallet does not mitigate this issue.

Regards

### Version

2.1.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Can you try running `chia wallet get_offers` from the command line and see if the offers show as "PENDING_ACCEPT"?

Anything interesting to share about the offers and how they were created? Are these NFT offers, or CAT/XCH offers? NFT offers are a bit different because the coin isn't locked-up by the offer code, allowing you to create multiple offers for the same NFT(s). Token offers (CAT/XCH) *will* lock up the offered coins.

**Comment by Muffexx** [comment]
Running `chia wallet get_offers` produces the following output:

`Record with id: *...*
---------------
Created at: 2023-10-*...*
Confirmed at: Not confirmed
Accepted at: N/A
Status: PENDING_ACCEPT`

The offer was created using the GUI. XCH were offered and USDSC were requested.

**Comment by Quexington** [comment]
Can you check your logs for the string "Trade for this offer already exists"?

**Comment by Muffexx** [comment]
I took a look inside the _debug.log_ file. There was no occurence of "Trade for this offer already exists".

**Comment by Quexington** [comment]
Any other errors in there outside of what you would normally see?

**Comment by Muffexx** [comment]
There are several errors and warnings, but I don't know which might relate to this issue. This one occurs very often:

`2023-11-07T*...* wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: *...*, puzzle_hash: *...*, amount: *..*}, spent_height: Some(*...*), created_height: Some(*...*) }, error: list index out of range`

This does also occur (at least) four times:

`2023-11-08T*...* wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '*...*'}`

*...* -> removed values

**Comment by Muffexx** [comment]
These stale offers also can't be removed. Trying to "cancel" these offers results in the "Pending Cancel" state.

**Comment by wjblanke** [comment]
Can you give us the stack trace from the log where this happened: list index out of range

That seems not normal to me. But I think the exception is being thrown pretty deep in a function call

**Comment by Muffexx** [comment]
This error was logged 216 times within the past two weeks.

**foo** = 4451004 OR 4477586
`created_height: Some(foo) }, error: list index out of range
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 1453, in _add_coin_states
  File "chia\wallet\trade_manager.py", line 167, in coins_of_interest_farmed
IndexError: list index out of range`

**Comment by wjblanke** [comment]
Could you retry with version 2.4.1 to see if this is still an issue? The bug is pretty old so things may have changed

**Comment by Muffexx** [comment]
Yes this issue can probably be closed. If the error occurs again, it can be reopened.
