### ISSUE TITLE
[Bug] Offer expiration time automatically reverts to default

### ISSUE THREAD

**Issue by Muffexx** [Chia-Network/chia-blockchain-gui#2224]
### What happened?

Hey.

The offer expiration time does automatically switch back to the default (7 days) every time I start the application.

regards

### Version

2.1.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Fixed with PR https://github.com/Chia-Network/chia-blockchain-gui/pull/2214. The fix is currently in main and will be included in the next release.
