### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'version')

### ISSUE THREAD

**Issue by iAM40KaL** [Chia-Network/chia-blockchain-gui#2245]
### What happened?

I keep getting this error when i try to create a Plot:

Error: Cannot read properties of undefined (reading 'version')
at webpack://@chia-network/gui/src/components/plot/add/PlotAddForm.tsx:92:29 defaultsForPlotter
at webpack://@chia-network/gui/src/components/plot/add/PlotAddForm.tsx:101:19 plotters[plotterName].version.split
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:167:136 Xh
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:290:336 Wk
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:388 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:319 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:179 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:271:87 Ok
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:273:299 Dk
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:127:104 jg

### Version

Chia Application Version: 2.1.3

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'version')

URL
#/dashboard/plot/add

Stacktrace
at webpack://@chia-network/gui/src/components/plot/add/PlotAddForm.tsx:92:29 defaultsForPlotter
at webpack://@chia-network/gui/src/components/plot/add/PlotAddForm.tsx:101:19 plotters[plotterName].version.split
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:167:136 Xh
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:290:336 Wk
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:388 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:319 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:179 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:271:87 Ok
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:273:299 Dk
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:127:104 jg
```

**Comment by ChiaMineJP** [comment]
Hi, I'd like to reproduce this bug in my Linux environment.
Could you please provide me with the following info?
- Linux distro (Ubuntu 22.04, Fedora 35, etc...)
- Install type (source instlal, package (rpm, deb, etc) install, cli install (dpkg -i, rpm -i, etc)
- (If you know) Installed plotters and their versions. (More precisely, do you have bladebit >= 3.0.0 instlaled?)

**Comment by ChiaMineJP** [comment]
Your error message suggests that
- you might not have any versions of bladebit plotter installed
- you don't have bladebit >= 2.0.0 installed and you selected Bladebit(Disk plot) as a plotter
- you don't have bladebit >= 3.0.0 installed and you selected Bladebit(Cuda plot) as a plotter

**Comment by ChiaMineJP** [comment]
If you don't have Bladebit installed, you can still try to create a plot with `Chia Proof of Space` plotter

<img width="818" alt="Screenshot 2023-12-21 at 0 08 12" src="https://github.com/Chia-Network/chia-blockchain-gui/assets/84098616/1a7c2018-4cf6-49cc-8d83-facce73d3acd">
