### ISSUE TITLE
'Add Plot to Queue' with Windows GUI actually starts plotting in parallel

### ISSUE THREAD

**Issue by Eldaw** [Chia-Network/chia-blockchain-gui#225]
If you have a plot that's already in progress, with a custom queue name, and you try to use the Windows GUI to add a new plot to that custom queue, it starts plotting the new plot right away (i.e. in parallel, not queued). For example, I had a plot in progress in a queue named 'T', and I then tried to add another plot to that queue. I specified 'T' as the queue for the new plot and chose to 'Add Plot to Queue'. However, the new plot started right away, meaning I had two plots running simultaneously, which was not the intention for the chosen drive. Below is a screenshot of me adding the second plot, and then below that is a screenshot of the result. I'm using v1.0.3 on Windows 10.

![image](https://user-images.githubusercontent.com/3789849/113467588-ca1fe000-943b-11eb-8b36-b02c099db38a.png)

![image](https://user-images.githubusercontent.com/3789849/113467600-defc7380-943b-11eb-8965-51c8874999f6.png)

**Comment by StrikeNP** [comment]
Idk for sure how it works, but I'm thinking each time you "Add plot" it's creating a _new_ queue and that option simply asks if you want to run that queue in parallel or series. As someone who wants to run a queue of multiple plots in parallel I'd be curious to see if that's actually how it works.

**Comment by Eldaw** [comment]
I haven't plotted in a while, but I don't believe this issue was ever fixed.

**Comment by StrikeNP** [comment]
So did eventually figure it out. The key to running a queue of multiple plots in parallel on the GUI is to create multiple queues with different names. Each queue with a different name is ran in parallel. That said, I would've much preferred that I could just say "run x plots in parallel on this drive until you run out of space"

**Comment by hoffmang9** [comment]
I believe this is long fixed.
