### ISSUE TITLE
[Bug] h.filter is not a function

### ISSUE THREAD

**Issue by artempl88** [Chia-Network/chia-blockchain-gui#2258]
### What happened?

After deleting the wallet from the computer, the action is performed, but an error pops up: "h.filter is not a function".
![Снимок экрана от 2024-01-14 18-39-07](https://github.com/Chia-Network/chia-blockchain-gui/assets/25647852/deade6a2-14b2-4b6e-a7b0-23e881ba3d36)

### Version

2.1.4

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by ChiaMineJP** [comment]
This issue was already identified and fixed. The fix will be included in the next release.
https://github.com/Chia-Network/chia-blockchain-gui/pull/2260
