### ISSUE TITLE
Last height farmed is not correct

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain-gui#23]
I am seeing Last Height Farmed: 0 in the farming page. But I have farmed rewards

**Comment by seeden** [comment]
PR was merged

**Comment by mariano54** [comment]
This is not correct, it is counting incoming transactions as farming rewards.

**Comment by seeden** [comment]
fixed via https://github.com/Chia-Network/chia-blockchain-gui/tree/small-fixes3
