### ISSUE TITLE
Ability to save a profile for plotting for self or a different set of public pool and farmer key for plotting. (Feature Request)

### ISSUE THREAD

**Issue by N418** [Chia-Network/chia-blockchain-gui#232]
Ability to save a profile for plotting for another set of public pool and farmer key for plotting.

For Windows CHIA GUI, I propose :
User can enter both another set of Public pool and Farmer Key to plot for someone else in a name-customized plotting profile. (or 2nd farmer).
Such profile is good for plotting more after Windows reboot and whatnot, or even name for "Main/Default" plotting profile for main user.

Essentially replace the need to plot for someone else in CLI. This also produce the log for analysis.
Suggest to make a visible(coloured) background colour to remind user he/she is plotting for someone else.
Also suggest to let user know they're not plotting for their own private key, that user is responsible for their action.
Make it difficult for any user to enable the function with extra confirmations.
(say user has to enable this function from CHIA program menu on left top before sees this function from [Add a Plot])

It's a huge convenience for some but I don't think this needs to be heavily emphasized so the new users are not confused.

**Comment by mariano54** [comment]
Adding the flag would be pretty simple, it's just a new flag that can be sent in the request and added to the call to `chia plots create`.

**Comment by N418** [comment]
I am not a programmer. I am just a CHIA program daily user. :)

**Comment by mariano54** [comment]
I'm commenting for other chia developers that can add this feature :P

**Comment by N418** [comment]
ok, let me make my thought more clear.

What I am essentially saying is, Plotting Profile (last used, Saved, Save for plotting for others).

:)
