### ISSUE TITLE
[Bug] Create Signature UI

### ISSUE THREAD

**Issue by CassFairiesClub** [Chia-Network/chia-blockchain-gui#2394]
### What happened?

When signing with an NFT in the GUI, the user interfaces behaves poorly. In order to be able to sign a message, you must first fill in the message field, THEN the NFT field and press enter in order to sign. Clicking "Sign" has no effect otherwise.
If you fill in the NFT field first, it clears as soon as you want to fill in the message field...

### Version

2.3.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Thanks! Will fix

**Comment by markelrod** [comment]
Fixed by https://github.com/Chia-Network/chia-blockchain-gui/pull/2404
