### ISSUE TITLE
[Bug] "Create Signature with nft" GUI vs CLI diferent response

### ISSUE THREAD

**Issue by CassFairiesClub** [Chia-Network/chia-blockchain-gui#2395]
### What happened?

The GUI and the rpc does not return the same parameters when signing with an NFT.
The GUI is including the "address" field instead of the "latest_coin_id" field.

### GUI response 
{  "pubkey": "813feea25c9f7f259835dd6e09e4d9ec827615ce5dd5c0b1f2092d84f6cba58bcf57e45ecb8ec574bcb49a255216ba43",
  "signature": "a8af6f1aa38a727799592a1d9c7b26b35a1919850bce315a62997e44d40cec424ed9db8be73433ed551e3de046408ea4062415e0c50c6953f8ccf73f1a0c54232682a8b9f462535ebf0931eb0aecb849d001fcd634d9a87a7d11e57cbe7d870b",
  "signing_mode": "BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_AUG:CHIP-0002_",
  "message": "this is a test message",
  "**_address_**": "xch1c2qv2nc2vqll2kknfae3wsc6qadnwr4ruf8cga398vm4jf72p2xswc7m73"}
  
### RPC response 
{  "**_latest_coin_id_**": "7cc2fab1cfffcb24b62db913471a4425f6a0cb5108565dc1fb90f901e44fd57d",
  "pubkey": "813feea25c9f7f259835dd6e09e4d9ec827615ce5dd5c0b1f2092d84f6cba58bcf57e45ecb8ec574bcb49a255216ba43",
  "signature": "a8af6f1aa38a727799592a1d9c7b26b35a1919850bce315a62997e44d40cec424ed9db8be73433ed551e3de046408ea4062415e0c50c6953f8ccf73f1a0c54232682a8b9f462535ebf0931eb0aecb849d001fcd634d9a87a7d11e57cbe7d870b",
  "signing_mode": "BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_AUG:CHIP-0002_",
  "success": true}

### Version

2.3.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Thanks! We will add both
