### ISSUE TITLE
Make the "To" address in wallet history copiable

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain-gui#24]
A common use case of using a wallet is re-sending money to the same address. But I cannot copy the "To" address in the tooltip

**Comment by dkackman** [comment]
double click ctrl-c of the actual label copies the full address

**Comment by mariano54** [comment]
Oh. It's intuitive though. We can make the tool tip copiable with the mouse

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/59
