### ISSUE TITLE
Include Redirect Capability for NFT URLs

### ISSUE THREAD

**Issue by markelrod** [Chia-Network/chia-blockchain-gui#2432]
### Discussed in https://github.com/Chia-Network/chia-blockchain-gui/discussions/2431

<div type='discussions-op-text'>

<sup>Originally posted by **BrandtH22** July 23, 2024</sup>
With nft.storage changing their services a lot of users NFTs appear to be broken as the URLs no longer directly contain the data or metadata but rather those urls are redirecting to the new data location. As an example:
![image](https://github.com/user-attachments/assets/7d4f7bda-b6e4-43c2-873a-01833c584854)

Is this something where we would want to update the wallet code to allow for redirects so long as the correct hash is at the endpoint or should we be instructing users to update their urls with the rpc instead?</div>

**Comment by ChiaMineJP** [comment]
I've minted a sample NFT with the https://nftstorage.link/ipfs/bafybeic7ninaf22lnvusvzyjx6ehx72mxsq7ce7gvd26ptbzezjvpd2b2i/1.png (an url before redirection) and it works. It shows NFT image as expected.

Downloading NFT image is done by this code:
https://github.com/Chia-Network/chia-blockchain-gui/blob/main/packages/gui/src/electron/utils/downloadFile.ts#L72

```typescript
const request = net.request(url);
```

and the default redirection policy of `net.request` is `follow`, according to https://www.electronjs.org/docs/latest/api/client-request#new-clientrequestoptions

**Comment by wjblanke** [comment]
Redirects should be OK. Reopen if you still have issues/information
