### ISSUE TITLE
[Bug] “View NFT on X” links incorrect.

### ISSUE THREAD

**Issue by smwhite2** [Chia-Network/chia-blockchain-gui#2441]
### What happened?

NFT's "View on Spacescan.io" link and “View on MintGarden” link do not direct as intended.
 
@GUI > NFTs > Click an NFT > three dot hamburger icon > View on (spacescan.io or mintgarden)
 
Choosing “View on Spacescan.io” yields https://spacescan.io/txch10/nft/... While I am using testnet11.
 
  Manually using https://spacescan.io/txch11/nft/... Does direct to accurate NFT data.
 
Choosing “View on MintGarden” yields https://testnet.mintgarden.io/nfts/... NFT ownership data not showing as expected.

Imagine fix should be around:
 
  https://github.com/Chia-Network/chia-blockchain-gui/blob/main/packages/gui/src/hooks/useViewNFTOnExplorer.ts#L9
 
  https://github.com/Chia-Network/chia-blockchain-gui/blob/main/packages/gui/src/hooks/useViewNFTOnExplorer.ts#L14

Also verified issue on Ubuntu 22.04.

### Version

2.4.3-rc1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by markelrod** [comment]
This was fixed in https://github.com/Chia-Network/chia-blockchain-gui/commit/fd3e0174873c9f5ed6546456ad4da776c8716b60 and will be included in the next release.
