### ISSUE TITLE
[Bug] User Interface glitch

### ISSUE THREAD

**Issue by abwqr** [Chia-Network/chia-blockchain-gui#2444]
### What happened?

This glitch appears on settings > advanced > create signature

**Light Mode:**
<img width="1397" alt="ui-error-light-mode" src="https://github.com/user-attachments/assets/03172970-0af5-4906-98f0-8d7d8784af2d">

**Dark Mode:**
<img width="1397" alt="ui-error" src="https://github.com/user-attachments/assets/dfaf26f8-361a-4e0b-80fb-ea677ad68094">

### Version

2.4.3-rc2

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by ChiaMineJP** [comment]
Fixed in this PR https://github.com/Chia-Network/chia-blockchain-gui/pull/2447
