### ISSUE TITLE
Automatically add names to unknown CATs

### ISSUE THREAD

**Issue by shaneo257** [Chia-Network/chia-blockchain-gui#2458]
### What happened?

When resyncing a wallet from scratch, with allot of CAT's, it can take a long time to rename all the CAT's manually.

I feel that the wallet should have a function where it can search spacescan for the CAT ID and update the name in your wallet automatically, almost similar to how the Chia Wallet does Spacebucks, Marmot etc now

### Version

2.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by advlive** [comment]
I have 90 different tokens and any times want to full resync have to manually rename all of them from ID to actual name. Wallet should have a function where it can search for the CAT ID and update the name, as easy can get from dexie or tokens database.
