### ISSUE TITLE
Block search: error message unexpectedly repeating

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain-gui#25]
Using the “Search block by header hash” function at the bottom of Full Node in the UI throws up an error if the search query is not a valid block hash. The bug is the error message is repeated twice, requiring you to click “ok” twice to exit.

Copied from: 
https://github.com/Chia-Network/chia-blockchain/issues/675

**Comment by seeden** [comment]
fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/117
