### ISSUE TITLE
[Bug] [GUI] A long memo field impacts location of expand/collapse button while in "windowed" viewing mode

### ISSUE THREAD

**Issue by OverActiveBladderSystem** [Chia-Network/chia-blockchain-gui#2550]
### What happened?

Windows 10, Chia v2.4.4 GUI in "windowed" mode (minimized, windowed, full screen)

(1st photo) When expanding details on a transaction to view the memo field while in "windowed" mode...

<img width="555" alt="Screenshot (2387)" src="https://github.com/user-attachments/assets/3cdb9809-abca-48b7-9022-73b93001a903">

(2nd photo) a long memo field forces the expand/collapse button off screen while in "windowed" mode (the horizontal scroll bars seem to be at the bottom of the transaction list, so you have to scroll down to scroll across then scroll back up)

<img width="557" alt="Screenshot (2388)" src="https://github.com/user-attachments/assets/b53bbcf9-d261-4445-bf51-93be827bc81e">

(3rd photo) so I enter "full screen" mode to collapse the transaction details rather than scroll down/across/up.

<img width="933" alt="Screenshot (2389)" src="https://github.com/user-attachments/assets/8988c4e1-74b0-4b9f-baa8-d64d4875dcd8">

Short or no memo field works as expected with the expand/collapse button remaining in place during "windowed" mode.

### Version

2.4.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by ChiaMineJP** [comment]
Thanks for the report. I'll check.

**Comment by ChiaMineJP** [comment]
I'm going to fix this issu by moving expand icon button to the head of each transaction rows.

![image](https://github.com/user-attachments/assets/c24ec213-7d18-4fee-8910-09d7c4f05af7)

**Comment by ChiaMineJP** [comment]
@OverActiveBladderSystem One possible candidate is to collapse the left list of tokens horizontally in order to allocate more space for the right transaction list. I would try the idea in the near future.
