### ISSUE TITLE
Discrepancy between farming balance and wallet balance that consists only of farming rewards

### ISSUE THREAD

**Issue by LeonidShamis** [Chia-Network/chia-blockchain-gui#26]
"Total Chia Farmed" balance @ Farm page is different from the balance @ Wallet page. Wallet's balance consists of farming rewards and gets updated correctly. However Farm Overview summary is not updated. Reloading via View/Reload(Ctrl-R) or by selecting the key from Keys page does not fix it.

![image](https://user-images.githubusercontent.com/1818114/107841650-ad3e3780-6e10-11eb-82f7-848c3877def4.png)

![image](https://user-images.githubusercontent.com/1818114/107841662-ce068d00-6e10-11eb-972d-baa55ce3a878.png)

`(venv) ubuntu@pi401:~/chia-blockchain$ chia wallet show`
`Balances, fingerprint: <FINGERPRINT>`
`Wallet ID 1 type STANDARD_WALLET`
`   -Confirmed: 176000000000000 mojo (176.0 TXCH)`
`   -Unconfirmed: 176000000000000 mojo (176.0 TXCH)`
`   -Spendable: 176000000000000 mojo (176.0 TXCH)`
`   -Pending change: 0 mojo (0.0 TXCH)`
`(venv) ubuntu@pi401:~/chia-blockchain$`

**Comment by seeden** [comment]
It is related to https://github.com/Chia-Network/chia-blockchain-gui/issues/69. I am closing it. Please follow https://github.com/Chia-Network/chia-blockchain-gui/issues/69
