### ISSUE TITLE
Web Version Edition

### ISSUE THREAD

**Issue by jjhesk** [Chia-Network/chia-blockchain-gui#266]
how to build a web version that only serve to a specific port 8800 for example. Is that a website version for this?

**Comment by seeden** [comment]
We do not have support for it in this moment.

**Comment by jjhesk** [comment]
i think we can get it working..

**Comment by hoffmang9** [comment]
This is something we want to support so PRs very welcome.

**Comment by jjhesk** [comment]
are there much changes from using electron to using api?
