### ISSUE TITLE
Underlying plotter is choosing bad bucket values - default to 128 for now [BUG]

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-blockchain-gui#27]
Unfortunately the C++ plotting code is making poor choices in bucket values and running people out of RAM when GUI plotting. Until we can address the default RAM and buckets in chiapos let's set the GUI default to be 128 buckets and leave the RAM recommendation the same.

**Comment by seeden** [comment]
Default bucket value changed to 128
