### ISSUE TITLE
[FR] Please include the Queue name in the log file

### ISSUE THREAD

**Issue by salamanders** [Chia-Network/chia-blockchain-gui#270]
**Describe the bug**
It would be useful to differentiate logs by queue names

**To Reproduce**
Read the logs.  Look for the queue name somewhere near the top of the log.

**Expected behavior**
See the queue name mentioned.

**Comment by chrisyearsley** [comment]
This would be great. Perhaps a CLI parameter called maybe 'jobname' that the GUI could use, and of course standalone CLI plotting. The logfile output might look something like:
Plot size is: 32
Buffer size is: 3389MiB
Job name is: swap-limit-push                 <<------- The user entered text from this enhancement
Using 128 buckets
