### ISSUE TITLE
electron ERROR

### ISSUE THREAD

**Issue by c4399eagle** [Chia-Network/chia-blockchain-gui#278]
0 info it worked if it ends with ok                                                                                                                                                                                
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'electron' ]                                                                                                                                   
2 info using npm@6.14.12                                                                                                                                                                                           
3 info using node@v14.16.1                                                                                                                                                                                         
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]                                                                                                                                                 
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@                                                                                                                                                    
6 info lifecycle chia-blockchain@~electron: chia-blockchain@                                                                                                                                                       
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true                                                                                                                                       
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/chia-blockchain/venv/bin:/usr/
local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                                                                                                                            
9 verbose lifecycle chia-blockchain@~electron: CWD: /chia-blockchain/chia-blockchain-gui                                                                                                                           
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]                                                                                                                                         
11 silly lifecycle chia-blockchain@~electron: Returned: code: 1  signal: null                                                                                                                                      
12 info lifecycle chia-blockchain@~electron: Failed to exec electron script                                                                                                                                        
13 verbose stack Error: chia-blockchain@ electron: `electron .`                                                                                                                                                    
13 verbose stack Exit status 1                                                                                                                                                                                     
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)                                                                                      
13 verbose stack     at EventEmitter.emit (events.js:315:20)                                                                                                                                                       
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)                                                                                   
13 verbose stack     at ChildProcess.emit (events.js:315:20)                                                                                                                                                       
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)                                                                                                                                             
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)                                                                                                                      
14 verbose pkgid chia-blockchain@                                                                                                                                                                                  
15 verbose cwd /chia-blockchain/chia-blockchain-gui                                                                                                                                                                
16 verbose Linux 4.14.24-qnap                                                                                                                                                                                      
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "electron"                                                                                                                                        
18 verbose node v14.16.1                                                                                                                                                                                           
19 verbose npm  v6.14.12                                                                                                                                                                                           
20 error code ELIFECYCLE                                                                                                                                                                                           
21 error errno 1                                                                                                                                                                                                   
22 error chia-blockchain@ electron: `electron .`                                                                                                                                                                   
22 error Exit status 1                                                                                                                                                                                             
23 error Failed at the chia-blockchain@ electron script.                                                                                                                                                           
23 error This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                 
24 verbose exit [ 1, true ]

**Comment by alwayserik** [comment]
Having the same issue on RHEL8 with 1.1.2 April 30, 2021

`
(venv) [erik@slater02 chia-blockchain-gui]$ npm run electron

> chia-blockchain@ electron /home/erik/Git/chia-blockchain/chia-blockchain-gui
> electron .

/home/erik/Git/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
The futex facility returned an unexpected error code.
/home/erik/Git/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron exited with signal SIGABRT
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/erik/.npm/_logs/2021-04-30T23_59_16_316Z-debug.log
(venv) [erik@slater02 chia-blockchain-gui]$ cat /home/erik/.npm/_logs/2021-04-30T23_59_16_316Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.12
3 info using node@v10.24.1
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@
6 info lifecycle chia-blockchain@~electron: chia-blockchain@
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/erik/Git/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/home/erik/Git/chia-blockchain/venv/bin:/home/erik/.local/bin:/home/erik/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
9 verbose lifecycle chia-blockchain@~electron: CWD: /home/erik/Git/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]
11 silly lifecycle chia-blockchain@~electron: Returned: code: 1  signal: null
12 info lifecycle chia-blockchain@~electron: Failed to exec electron script
13 verbose stack Error: chia-blockchain@ electron: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid chia-blockchain@
15 verbose cwd /home/erik/Git/chia-blockchain/chia-blockchain-gui
16 verbose Linux 4.18.0-240.15.1.el8_3.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
18 verbose node v10.24.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error chia-blockchain@ electron: `electron .`
22 error Exit status 1
23 error Failed at the chia-blockchain@ electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`
