### ISSUE TITLE
Showing Pool and Harvester keys in the GUI

### ISSUE THREAD

**Issue by maran** [Chia-Network/chia-blockchain-gui#286]
It's currently a bit tricky to get your pool and harvester keys out of the GUI. You can use the bundled .exe or go through log files to get them out but for most normal Windows users this is a bit hard.

Would you be open to accepting a PR to add the keys to the GUI and if so where would you prefer them to be shown?

**Comment by hoffmang9** [comment]
Yea and they would most likely be best on the key selection page. Maybe an info "i" icon next to the show private key button?
