### ISSUE TITLE
GUI - blank screen 

### ISSUE THREAD

**Issue by farmingtonschia** [Chia-Network/chia-blockchain-gui#287]
[Hi I noticed Chia GUI was blank screen after an hour so of run. when tried reload and force reload I got a java script error. However i noticed from windows action manager that chia was running and that the plotter files were being updated (se images of screenshots at times T1 and T2. Please let me know if I need to do anything to fix this issue or this is a bug in chia gui s/w to be fixed. I have attached about 7 screen shots that may help understand the issues.

PS: this is my first time here. pardon me for any oversight. 
![chia gui blank screen](https://user-images.githubusercontent.com/82891356/115430785-aa760f00-a1d2-11eb-9aa9-92e0bfca5f6e.png)
![tried reload and force reload](https://user-images.githubusercontent.com/82891356/115431018-dabdad80-a1d2-11eb-9464-d09350487dd9.png)
![chia gui error message](https://user-images.githubusercontent.com/82891356/115432031-f4132980-a1d3-11eb-8a42-8ac1b80b55b4.png)
![Inkedplotter file at T1_LI](https://user-images.githubusercontent.com/82891356/115434071-435a5980-a1d6-11eb-88a5-bed553248336.jpg)
![Inkedplotter file at T2_LI](https://user-images.githubusercontent.com/82891356/115434082-46554a00-a1d6-11eb-82fe-78a0a3effbe7.jpg)
![Windows Task Manager ](https://user-images.githubusercontent.com/82891356/115432196-1b69f680-a1d4-11eb-9042-5966b5a976a1.png)
![Windows Task Manager -cpu - ssd ### **performance](https://user-images.githubusercontent.com/82891356/115432210-1efd7d80-a1d4-11eb-94a1-d801b08b6ad9.png)**

](url)

**Comment by seeden** [comment]
Issue with undefined windows variable will be fixed via https://github.com/Chia-Network/chia-blockchain-gui/tree/fullscreen
