### ISSUE TITLE
WIN GUI 1.0.5 Wallet Connection problem

### ISSUE THREAD

**Issue by russ-tolman** [Chia-Network/chia-blockchain-gui#290]
![image](https://user-images.githubusercontent.com/80480662/115588584-c2f23200-a283-11eb-8ad1-0aacb32336ec.png)
The "Connecting to Wallet" justs spins, but when I do a reload or force reload, the developer view shows the message "already connected, not reconnecting." And temp drive activity indicates that plotting is still occurring, so I am hesitant to restart/reboot. Is this a bug? Is there a workaround? Please advise.

**Comment by seeden** [comment]
I already fixed it. It will be part of RPC refactoring

**Comment by russ-tolman** [comment]
Awesome! Thanks.


New single: "life"

| See the video: RUSS TOLMAN I LOVE LIGHTNING (FEAT. JAWBO)
Catch my radio show, "My Kinda Country," every Thursday, 2pm Pac on GimmeCountry.com

 |

 

    On Wednesday, April 21, 2021, 10:17:06 AM PDT, Zlatko Fedor ***@***.***> wrote:  
 
 


I already fixed it. It will be part of RPC refactoring

**Comment by farmingtonschia** [comment]
> I already fixed it. It will be part of RPC refactoring

Hi I read  under windows tip[s & tricks wiki" Sometimes your wallet database can get corrupted. If you get stuck on the "Connecting to wallet" spinner for more than 60 seconds, you will probably want to exit the app, delete your wallet database with Powershell, and then start the app again.

For version 1.0.x:
    cd ~\.chia\mainnet\wallet\db
    del *.sqlite" 

if I do that what happens - do I lose all my plots
