### ISSUE TITLE
Centos Install blank screen localhost:3000

### ISSUE THREAD

**Issue by marsnels** [Chia-Network/chia-blockchain-gui#299]
I have installed and am running the chia script however I am getting a blank page.

**Comment by seeden** [comment]
Do you see any errors in the developer console? (View => Developer => Developer Console)

**Comment by marsnels** [comment]
Uncaught ReferenceError: global is not defined
    <anonymous> http://localhost:3000/js/vendors-node_modules_lingui_core_esm_index_js-node_modules_lingui_core_index_js-node_modules_-41d054.js:1
vendors-node_modules_lingui_core_esm_index_js-node_modules_lingui_core_index_js-node_modules_-41d054.js:1:2
Uncaught ReferenceError: global is not defined
    <anonymous> jsonp chunk loading:41
    <anonymous> main.js:62586
    <anonymous> main.js:62600

**Comment by seeden** [comment]
What is your node version? node --version

**Comment by abiaqiou** [comment]
> What is your node version? node --version. The minimum node version is 10.14.2

Same issue. My node version is 14.16.0

The whole process is:
1 clone this repo
2 npm i
3 npm start
4. open localhost:3000
5. Developer Console shows
```javascript
Uncaught ReferenceError: global is not defined
    at vendors-node_modules_lingui_core_esm_index_js-node_modules_lingui_react_esm_index_js-node_mod-52e34b.js:1
Uncaught ReferenceError: global is not defined
    at main.js:68244
    at main.js:68738
    at main.js:68752
```

**Comment by abiaqiou** [comment]
> Uncaught ReferenceError: global is not defined
> http://localhost:3000/js/vendors-node_modules_lingui_core_esm_index_js-node_modules_lingui_core_index_js-node_modules_-41d054.js:1
> vendors-node_modules_lingui_core_esm_index_js-node_modules_lingui_core_index_js-node_modules_-41d054.js:1:2
> Uncaught ReferenceError: global is not defined
> jsonp chunk loading:41
> main.js:62586
> main.js:62600

Have you solved this problem?

**Comment by McFlown** [comment]
I guess this is the same issue as #361

**Comment by seeden** [comment]
I created PR for it. Can you try https://github.com/Chia-Network/chia-blockchain-gui/pull/365 ?

**Comment by abiaqiou** [comment]
> I created PR for it. Can you try #365 ?

After i pulled the code, and do these process:
  1. rm -rf node_modules
  2. npm cache clear -f
  3. npm i
  4. npm start

The screen on localhost:3000 is still blank. The error in console is changed.
```javascript
Uncaught ReferenceError: require is not defined
    at querystring (main.js:67563)
    at Object.options.factory (main.js:68168)
    at __webpack_require__ (main.js:67603)
    at fn (main.js:67848)
    at ./node_modules/native-url/dist/index.mjs (vendors-node_modules_lingui_core_esm_index_js-node_modules_lingui_react_esm_index_js-node_mod-52e34b.js:81839)
    at Module.options.factory (main.js:68168)
    at __webpack_require__ (main.js:67603)
    at fn (main.js:67848)
    at ./node_modules/@pmmmwh/react-refresh-webpack-plugin/sockets/WDSSocket.js (vendors-node_modules_lingui_core_esm_index_js-node_modules_lingui_react_esm_index_js-node_mod-52e34b.js:35039)
    at Object.options.factory (main.js:68168)
```

**Comment by maybeTomorrow** [comment]
> > I created PR for it. Can you try #365 ?
> 
> After i pulled the code, and do these process:
> 
> 1. rm -rf node_modules
> 2. npm cache clear -f
> 3. npm i
> 4. npm start
> 
> The screen on localhost:3000 is still blank. The error in console is changed.
> 
> ```js
> Uncaught ReferenceError: require is not defined
>     at querystring (main.js:67563)
>     at Object.options.factory (main.js:68168)
>     at __webpack_require__ (main.js:67603)
>     at fn (main.js:67848)
>     at ./node_modules/native-url/dist/index.mjs (vendors-node_modules_lingui_core_esm_index_js-node_modules_lingui_react_esm_index_js-node_mod-52e34b.js:81839)
>     at Module.options.factory (main.js:68168)
>     at __webpack_require__ (main.js:67603)
>     at fn (main.js:67848)
>     at ./node_modules/@pmmmwh/react-refresh-webpack-plugin/sockets/WDSSocket.js (vendors-node_modules_lingui_core_esm_index_js-node_modules_lingui_react_esm_index_js-node_mod-52e34b.js:35039)
>     at Object.options.factory (main.js:68168)
> ```

me too
