### ISSUE TITLE
Local Harvester Plots : Shifted columns for Status and Action

### ISSUE THREAD

**Issue by dvd101x** [Chia-Network/chia-blockchain-gui#30]
On the table: Local Harvester Plots on the tab for Plots.

For the rows that are in status: plotting or status: queued. The status is in plotting column and actions is in status column. They are one column to the left.

Please put them one column to the right.

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/40

**Comment by seeden** [comment]
PR was merged
