### ISSUE TITLE
FreeBSD - Freenas jail - install-gui.sh throws Error: Platform: "freebsd" is not supported

### ISSUE THREAD

**Issue by Matehias** [Chia-Network/chia-blockchain-gui#302]
Hi,
I followed several times the tuto [here ](https://github.com/Chia-Network/chia-blockchain/wiki/FreeBSD-Install)
I'm sure i did well all steps but when i run `sh install-gui.sh`, i have these errors : 

"(venv) [root@Chia ~/chia-blockchain]# sh install-gui.sh
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent versions of packages are already installed

Running git submodule update --init --recursive.

Running git submodule update.

> cypress@7.1.0 postinstall /root/chia-blockchain/chia-blockchain-gui/node_modules/cypress
> node index.js --exec install

/root/chia-blockchain/chia-blockchain-gui/node_modules/cypress/lib/tasks/state.js:53
      throw new Error(`Platform: "${platform}" is not supported.`);
      ^

Error: Platform: "freebsd" is not supported.
    at getPlatFormBinaryFolder (/root/chia-blockchain/chia-blockchain-gui/node_modules/cypress/lib/tasks/state.js:53:13)
    at Object.getBinaryDir (/root/chia-blockchain/chia-blockchain-gui/node_modules/cypress/lib/tasks/state.js:81:44)
    at Object.start (/root/chia-blockchain/chia-blockchain-gui/node_modules/cypress/lib/tasks/install.js:263:27)
    at Object.<anonymous> (/root/chia-blockchain/chia-blockchain-gui/node_modules/cypress/index.js:16:36)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of react-refresh@>=0.8.3 <0.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN @use-it/event-listener@0.1.6 requires a peer of react@^16.8.0 but noneis installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none isinstalled. You must install peer dependencies yourself.
npm WARN react-scroll-to-bottom@4.1.1-master.2780945 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-simple-code-editor@0.10.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-simple-code-editor@0.10.0 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN use-dark-mode@2.3.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@7.1.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@7.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above."

Thanks in advance for the help and sorry if there are some mistakes, English are not my native language  :)

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/306
