### ISSUE TITLE
[BUG] Ubuntu GUI cannot leave Keys page unless new key created

### ISSUE THREAD

**Issue by siayinshen** [Chia-Network/chia-blockchain-gui#303]
**Describe the bug**
If you click on the 'Keys' tab in the sidebar, it is impossible to return to the main page unless you create a new key.

**To Reproduce**
Click on the Keys tab in the sidebar.

**Expected behavior**
A back button should enable returning to the main menu if keys are present without having to create a new key.

**Comment by tcrminingrocks** [comment]
I've had all kinds of trouble with this.
