### ISSUE TITLE
[BUG] Message "22"

### ISSUE THREAD

**Issue by VaIar** [Chia-Network/chia-blockchain-gui#324]
Windows GUI 1.1.2 shows pop-up message "22" and Ok below on Gui start on Plotting end. Also after plotting finished again message 22 appear and plotted files not appear in GUI. Plotted files can't be added to gui from folder, message 22 appear

Os is Windows Server 2019, with latest updates.

CPU - Intel Xeon. Screenshot attached.

**Comment by seeden** [comment]
In next version you will see this descriptive message:
[Error 22] File not found. Most likely one of the plot folders in your config.yaml has an issue.
