### ISSUE TITLE
[BUG]An error occurred when I ran 'NPM run electron &' during installation

### ISSUE THREAD

**Issue by baojizhineng** [Chia-Network/chia-blockchain-gui#326]
![image](https://user-images.githubusercontent.com/81623635/116364151-7afc7d80-a836-11eb-88f1-251f195b7a3b.png)

My English is not good, please upload the picture directly
Operating system: Ubuntu

**Comment by seeden** [comment]
What is your nodejs version? node --version. The minimum version is 10.14.2

**Comment by Cptn-Reynolds** [comment]
Got the same error but with another library, running Raspbian 64 bit. Node Version is 14.16.1
![Raspian](https://user-images.githubusercontent.com/83375968/116478207-02b9aa80-a87e-11eb-84ac-7e15b0c381df.PNG)

**Comment by sergioxfarias** [comment]
Same issue. Ubuntu 20.10 and Node version 12.18.2

**Comment by alwayserik** [comment]
Same issue.

**Comment by twilightsavant** [comment]
Same Error, Ubuntu 20.04.2 node V10.19.0. Clean install of OS just to get Chia up and running.

**Comment by NipBoss** [comment]
Same issue, CentOS 8.1 CloudLinux+
https://github.com/Chia-Network/chia-blockchain-gui/issues/353

**Comment by robmarano** [comment]
+1 Same issue on Amazon Linux AMI on ARM CPU

**Comment by hoffmang9** [comment]
> +1 Same issue on Amazon Linux AMI on ARM CPU

You can't really run the GUI in an EC2 instance without a tremendous amount of configuration and pain...

**Comment by NipBoss** [comment]
My developer suggested we try to install VNC on the machine for gui support, will be trying this tomorrow. Will update you guys on how that turns out.
