### ISSUE TITLE
[BUG]- Socket Hang Up

### ISSUE THREAD

**Issue by ckhow** [Chia-Network/chia-blockchain-gui#329]
[](url)
![socket error](https://user-images.githubusercontent.com/49635203/116436763-4cef5b80-a87f-11eb-9e6e-224b9041f802.PNG)

**Comment by AV-IO** [comment]
@ckhow, I resolved this by closing another instance of the chia daemon running. I'd recommend checking what processes are using the port.
In Powershell: `Get-Process -Id (Get-NetTCPConnection -LocalPort 55400).OwningProcess`
On Linux: `ss -atp | grep ":55400"`
