### ISSUE TITLE
[BUG] sabotage in code

### ISSUE THREAD

**Issue by inigosola** [Chia-Network/chia-blockchain-gui#339]
There is a sabotage in code in latest version.
In previous version spanish translation for farming was cultivando (it is right), but latest version has a very wrong translation joseando.

Please, review all code because there could be more dangerous sabotages.

**Comment by wwwroth** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/3415#issuecomment-830833029

**Comment by seeden** [comment]
Hi @inigosola  and @wwwroth. Please log in to https://crowdin.com/project/chia-blockchain and vote for correct Spanish translations. It will be used in the next release automatically.
