### ISSUE TITLE
Deleting queued plot triggers plotting to start on remaining queued plot

### ISSUE THREAD

**Issue by sizeight** [Chia-Network/chia-blockchain-gui#34]
Let's say I add 4 plots (not parallel), then I will see the 4 plots added to the list of plots, 1 will indicate **Plotting** and the other 3 will indicate **Queued**.

If I then delete one of the queued plots it will be deleted but one of the other queued plots will immediately start plotting leaving me with 2 plots plotting  and 1 queued instead of 1 plotting and 2 queued.

**Comment by aaronscientiae** [comment]
And this eats up performance and makes it impossible to delete them so I have to crash out the program, with 'connecting wallet' showing, and this loses the plot progress.

**Comment by jespino** [comment]
This is a server problem, not a gui problem, here is the fix Chia-Network/chia-blockchain#1128
