### ISSUE TITLE
Wrong translate

### ISSUE THREAD

**Issue by stepik** [Chia-Network/chia-blockchain-gui#341]
https://github.com/Chia-Network/chia-blockchain-gui/blob/7be627b140a5a670a12e38288c03c51f76e1c2bf/src/locales/ru-RU/messages.po#L1038

Right translate: msgstr "КиБ исх. \ \ вх."

**Comment by seeden** [comment]
@stepik can you change it here https://crowdin.com/project/chia-blockchain and vote for this translation as well?
Thank you

**Comment by seeden** [comment]
Thank you @stepik. I see that you already did it.
