### ISSUE TITLE
Trade tab missing in Windows client

### ISSUE THREAD

**Issue by onillap** [Chia-Network/chia-blockchain-gui#342]
Hello,
my Windows client doesn't show the Trade tab:
![immagine](https://user-images.githubusercontent.com/53819193/116907740-44fa3780-ac42-11eb-8f8f-93ca4101d699.png)
I am using v1.1.3 but the Trade tab was not visible even with earlier releases.
The log files do not seem to contain errors related to this issue.
Is there anything that I could check?

**Comment by seeden** [comment]
We removed it because trading is not working yet. We will add it back when it is ready
