### ISSUE TITLE
Main machine shows harvester linked but does not show harvesters' plot counts

### ISSUE THREAD

**Issue by farmingtonschia** [Chia-Network/chia-blockchain-gui#343]
the same farmer and public pool key was used 

all plots checked (chia plots check)
harvester is showing on main harvester (so port 8447 is connected, UPNP disabled on harvester, CA certificate link, farmer peer setting on harvester all checks ok)
ran all the checks as described in https://github.com/Chia-Network/chia-blockchain/wiki/How-to-Check-If-Everything-is-Working-(or-Not) 
Chia GUI shows synced on both main machine and harvester 
main machine shows under harvester 
harvester shows up under main machine

Harvester's plot count not showing in main machine 

Expected time to win show only based on each machines local plots - is this is a disadvantage?????????????????

I think I started harvester in the CLI
do I need to keep the Chia Gui on the second machine - please clarify?

None of plots have passed plots filter yet (100+ plots) :( 

anyone would respond?

**Comment by royimous** [comment]
This is a known issue: https://github.com/Chia-Network/chia-blockchain/issues/2830

Check the `debug.log` on your harvesters to see if the plots are being checked. You should also see the plots in the Last Attempted Proof section. 

I'm pretty sure your plots are being seen.

**Comment by farmingtonschia** [comment]
The plots are being checked. I see this from the debug logs (checked for plots eligble, etc ) Still NO plots have passed filter

the up/down link between main machine and harvester shows zero 

as well as 

the up/down link between harvester and machine shows zero 

(see GUI image from harvester and image from main machine )

![chia_gui_harvester_view](https://user-images.githubusercontent.com/82891356/117236678-2b4e2100-adf7-11eb-9f3d-9694a796b961.png)

**Comment by Harbourgroup** [comment]
It's quite confusing. I setup similar to below. And I have total 5 peers and 20 plots in total

Main: 172.31.32.12

**Harvester server debug.log:**
![image](https://user-images.githubusercontent.com/77424412/117244513-be28a300-ae6b-11eb-8c2e-b4f7b2ea0792.png)

**Main farming server debug.log:**
![image](https://user-images.githubusercontent.com/77424412/117244322-69852800-ae6b-11eb-8c9f-d586704634bf.png)

The farming should be working. but "chia farm summary"  plot count only shows those plots in the main server. Those in harvester server won't show. 

![image](https://user-images.githubusercontent.com/77424412/117244432-946f7c00-ae6b-11eb-995b-c0bbd732244b.png)
