### ISSUE TITLE
[BUG] bad translation in spanish version

### ISSUE THREAD

**Issue by fga352** [Chia-Network/chia-blockchain-gui#344]
Describe the bug
translation of farming is "cultivando" not "joseando". Joseando doesn't exist in RAE https://www.rae.es/ with this meaning. 

To Reproduce

Go to 'Language'
Click on 'Spanish'
Go to "Parcelas" or "Granja"
See error

Expected behavior
I expect "Cultivando". Joseando doesn't have farming meaning in spanish language. Maybe in latam spanish but not in spanish.

This error is in 1.1.3 version. In 1.1.2 the word is "cultivando".

**Comment by seeden** [comment]
It was already changed to cultivando

**Comment by egmsystems** [comment]
no finish yet.
correct, in the file main.js line 28750 Farming: "Joseando",
in this file should be change Joseando with Cultivando

**Comment by seeden** [comment]
Hi.
It was already fixed and merged a few days ago. Version 1.1.5 is using the old version of the GUI.
There is no "joseando" in the es-ES anymore https://github.com/Chia-Network/chia-blockchain-gui/blob/main/src/locales/es-ES/messages.po
