### ISSUE TITLE
[GUI BUG] Progress bar doesn't work correctly when the bucket size is not 128

### ISSUE THREAD

**Issue by richackard** [Chia-Network/chia-blockchain-gui#354]
With bucket size set to 64, my progress ends at 52% when everything is done.

Pretty sure here's the cause: https://github.com/Chia-Network/chia-blockchain-gui/blob/101c3855e905064cb2047e16ed3b72129983dcd6/src/modules/plotQueue.ts#L11-L13

**Comment by McFlown** [comment]
Exactly, and for bucket size 32 it ended for me at 25%.
