### ISSUE TITLE
About window has version as 0.0

### ISSUE THREAD

**Issue by arvidn** [Chia-Network/chia-blockchain-gui#355]
The about window (found in the "Help > About Chia Blockchain" menu) says the version number is 0.0.

I'm running version 1.1.4, so I was expecting it to say that.

![Screenshot from 2021-05-05 10-40-02](https://user-images.githubusercontent.com/661450/117116339-85ff6280-ad8e-11eb-9c56-78e20d9ddb64.png)

As an aside, this window also does not respect dark mode.

**Comment by hoffmang9** [comment]
Was this from the .dmg installer? git installs do not get the version information as it's an installer building step.

**Comment by arvidn** [comment]
ah, yes. This was from git
