### ISSUE TITLE
Chia not starting keeps on connecting to wallet

### ISSUE THREAD

**Issue by gerardit** [Chia-Network/chia-blockchain-gui#362]
I was creating a plot and my electricity cut so it stopped the plot and when I turn it on and started chia it gets stuck on connecting to wallet I tried to reboot uninstall change version...

**Comment by modmoto** [comment]
I have a similiar thing where this happens from time to time and then the UI just keeps reconnecting. Had to restart a few plots because of this :/ I think it mostly happened when changing tabs or delete building plots, but it is not really reproducible for me.

**Comment by seeden** [comment]
I think it can be related to https://github.com/Chia-Network/chia-blockchain-gui/issues/359

**Comment by gerardit** [comment]
This started happening after my PC shutdown due to a blackout while creating a plot so I suppose is that but I don't understand why if I uninstall it a install it again I continue with the same issue

**Comment by chapas** [comment]
This also happens to me every time I restart the computer (gracefully). This is very annoying there are multiple issues open like this one.
I have been solving this by moving the entire wallet/db folder to another dir and then starting the GUI and letting it resync again.
I wish someone would fix this, I'm not even plotting from the GUI, I'm plotting from the CLI.

**Comment by bitnaughty** [comment]
For me it was an issue with poor PID management.
I closed GUI and removed all PID files in mainnet\run and it started without issues.

**Comment by gerardit** [comment]
Ok thanks I will try it

**Comment by gerardit** [comment]
I try it and it keeps on connecting to wallet

**Comment by mario-j-moreira** [comment]
@gerardit have you tried my approach?

**Comment by chapas** [comment]
@gerardit have you tried my approach?

**Comment by joejordan** [comment]
This still occurs in v1.2.3, as my client also can't get past "Connecting to wallet". The logs are not being updated so I'm not even sure why it's happening, as I have had no crashes of either the app or my system, but this is a continual issue that really needs a higher priority.
