### ISSUE TITLE
Chia GUI needs a launcher icon for Ubuntu

### ISSUE THREAD

**Issue by sizeight** [Chia-Network/chia-blockchain-gui#38]
The image belows shows that Chia Gui needs a **launcher icon** to display in Ubuntu's sidebar. Chia is the last "blank icon" in the image.
![image](https://user-images.githubusercontent.com/232198/108029617-7184b700-7036-11eb-98fa-9ed624a56b16.png)

**Comment by hoffmang9** [comment]
We do not yet make available an electron installer for Linux. We will at some point in the future but until then, the developer build style will not have an icon or a version number.
