### ISSUE TITLE
After update to 11.5 plotting log only shows "loading"

### ISSUE THREAD

**Issue by archerbobby** [Chia-Network/chia-blockchain-gui#380]
OS: Ubuntu

I updated to 11.5 today and followed all the instructions.  After the update and logged back in.  I waiting for it to sync. Once synced I started a new plot.  The plot status never updated and after 30 minutes I checked the log on gui and it was black except for stating "loading".

I restarted the machine multiple times, the terminal, and tried to update again, followed the trouble shooting guide and to no avail. 
![IMG_20210511_195856_02](https://user-images.githubusercontent.com/64240937/117899744-badf4e00-b295-11eb-9b1a-fbaf97a63b4c.jpg)

**Comment by seeden** [comment]
Hi @archerbobby 
Can you verify your debug.log file ~/.chia/mainnet/log/debug.log. Is there any error? 
What OS are you using?
Thanks

**Comment by archerbobby** [comment]
I could not find the debug file.

I am using ubuntu as the OS.

Also, it seems even though there is no progress or information being shown on the "view log" button, it is still plotting.  So it is doing the work but not showing anything going on.
