### ISSUE TITLE
Already connected, not reconnecting error

### ISSUE THREAD

**Issue by dschendt** [Chia-Network/chia-blockchain-gui#383]
My internet disconnected over night. My Chia GUI wouldn't resync so I did a Reload from the View menu. Now I just get a perpetual "Connecting to wallet" in the GUI and the Developer Tool spits out "Already connected, not reconnecting." over and over.

**Comment by dschendt** [comment]
If I use task manager to close everything but the chia.exe processes it appears that I can keep the plots that I had running in progress and reopen the Chia GUI and it'll connect and resync just fine. I just can't see the progress of the plots that are running.

**Comment by gold4boomers** [comment]
This error is terrible. Please let us know how we can fix this in the developer console of the UI itself. There must be some simple way  to re-establish a connection with UI to farm? I know CLI plotting is better and yada yada but many people have to do trial and error in the UI first to understand plotting better before they are ready to go headless.

Please. How fix this with dev tools?

**Comment by Brydandon** [comment]
I am having this same issue. Did anyone discover a way to get the GUI back to normal via developer tools without shutting down everything? I really hope a "resume plots" feature is created in the GUI, because this wouldn't be a problem if GUI needs to be shut down to fix.
