### ISSUE TITLE
Crashing on deleteing plot

### ISSUE THREAD

**Issue by ppsirius** [Chia-Network/chia-blockchain-gui#384]
I using version 1.1.5 on windows 10 and when I try to delete running plot app is crashing. I see then loading wallet info and app don't back to normal work. I need to close app and run again ofcourse my runned plots disappears. Deleteing working on not started plot.

**Comment by seeden** [comment]
I am working on it.

**Comment by leonidcan** [comment]
This and also if delete 2 non active quickly (before UI refresh) it will also crash/hang. Sometimes if click to fast things it might stuck in refresh mode (spinning thing on darker screen).
