### ISSUE TITLE
Connecting to wallet infinitum

### ISSUE THREAD

**Issue by iamaer4fa** [Chia-Network/chia-blockchain-gui#385]
Hi,

I am on Win64 10 64-bit, Ryzen CPU 7 1700, 32Gb RAM, GTX 1050Ti, 4 Plots,  Attempting to run chia, but it will never finish connecting, its been many hours waiting for it to connect. (Using Chia GUI version 1.1.4)

![image](https://user-images.githubusercontent.com/8325058/118219687-93ae9980-b4ac-11eb-9268-09b5e35d975c.png)

![image](https://user-images.githubusercontent.com/8325058/118219777-c0fb4780-b4ac-11eb-875a-78e8ba4ff062.png)

![image](https://user-images.githubusercontent.com/8325058/118219808-d07a9080-b4ac-11eb-90ff-ac0f99af5dbd.png)

**Comment by wjblanke** [comment]
stop chia, delete ~/.chia/mainnet/wallet, reboot, install chia 1.1.5
