### ISSUE TITLE
cannot start npm electron

### ISSUE THREAD

**Issue by tamerin-tech** [Chia-Network/chia-blockchain-gui#387]
Trying on Ubunto 18 and following the installation steps.
After the last command "npm run electron &" I getting this error:

~/chia-blockchain/chia-blockchain-gui$ npm run electron

> chia-blockchain@ electron /home/me/chia-blockchain/chia-blockchain-gui
> electron .

/home/me/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
/home/me/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron exited with signal SIGSEGV
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2021-05-14T14_35_16_734Z-debug.log

from the error log:
cat /home/me/.npm/_logs/2021-05-14T14_35_16_734Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@
6 info lifecycle chia-blockchain@~electron: chia-blockchain@
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/me/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/home/me/chia-blockchain/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle chia-blockchain@~electron: CWD: /home/me/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]
11 silly lifecycle chia-blockchain@~electron: Returned: code: 1  signal: null
12 info lifecycle chia-blockchain@~electron: Failed to exec electron script
13 verbose stack Error: chia-blockchain@ electron: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid chia-blockchain@
15 verbose cwd /home/me/chia-blockchain/chia-blockchain-gui
16 verbose Linux 5.4.0-1047-azure
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "electron"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error chia-blockchain@ electron: `electron .`
22 error Exit status 1
23 error Failed at the chia-blockchain@ electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Tried also to delete package-lock.json and reinstall packages

Any ideas?

**Comment by tamerin-tech** [comment]
update - same error on Ubuntu 20

**Comment by sonpython** [comment]
This is maybe you are trying to run electron inside a ssh session

Try to run that command in an terminal in desktop environment (Gnome) instead.
