### ISSUE TITLE
[BUG] Change Wallet Address in config.yaml don't change address in Wallet tab

### ISSUE THREAD

**Issue by lucalas** [Chia-Network/chia-blockchain-gui#388]
Hi,

I changed my wallet Address to receive Farming rewards following step by step the guide under the wiki [Chia Keys Management](https://github.com/Chia-Network/chia-blockchain/wiki/Chia-Keys-Management).

So i created the new key, I retrieved the new wallet address and I modified config.yaml xch_target_address under farmer and plot groups (then I removed the new key created saving  24 words mnemonic).

I restated the GUI and if I go to Farm tab under "Manage Farming Rewards" i can see the new address but in wallet tab i still see old wallet address and all rewards related to the old address.

**Comment by johnbiggs** [comment]
The wallet can only show the wallet related to the active mnemonic. It does not have the private keys to a cold wallet and can not show that.

**Comment by lucalas** [comment]
> The wallet can only show the wallet related to the active mnemonic. It does not have the private keys to a cold wallet and can not show that.

To show wallet information like amount and transactions we don't need private key, correct?
We probably can't see "pending balance" and "create transaction" tab but I think that they may be disabled if we use a cold wallet
