### ISSUE TITLE
Please help, all ploted plot disappears

### ISSUE THREAD

**Issue by Tototoua** [Chia-Network/chia-blockchain-gui#389]
I have restart my computer and find that all farming plots disappear. Try to find a solution and check the plot using powershell and its all there. Its somehow disappear from my GUI 

![image](https://user-images.githubusercontent.com/84137227/118311619-58e34a80-b51a-11eb-816d-ee185677eb36.jpeg)

![image](https://user-images.githubusercontent.com/84137227/118311633-5c76d180-b51a-11eb-9ade-3c43a051ac14.jpeg)

**Comment by wjblanke** [comment]
Hmm, have you tried rebooting/restarting? If that doesn't work, set logging to INFO in ~/.chia/mainnet/config/config.yaml, restart and look at ~/.chia/mainnet/log/debug.log that will give you more information on why the plots did not load. Maybe the GUI is misreporting things.

**Comment by Tototoua** [comment]
Thank for your reply, Here is what i did and its work. I close the program, delete the whole config file and reopen it again. And it work all plot come back.
