### ISSUE TITLE
Adding several copies of the same plot to the gui shows up as total plot size in error.

### ISSUE THREAD

**Issue by justinengland** [Chia-Network/chia-blockchain-gui#39]
i noticed  in the chia gui. if i copy my plots to another dir and add them again it adds them to my total space number, which i am sure is just a UI bug

The expected behavior here would be for the GUI to only list the total space of unique plots to avoid confusion for less informed users.

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/40

**Comment by seeden** [comment]
PR was merged
