### ISSUE TITLE
[REQ] Allow GUI to shut down without stopping all services.

### ISSUE THREAD

**Issue by krifalk** [Chia-Network/chia-blockchain-gui#398]
Today, when shutting down GUI it submits a **stop service all**, which makes it impossible to combine CLI and GUI. If farming is initiated via CLI (i.e. automatically at server startup) in will be stopped if the GUI is shut down or hangs. It would be a lot more intuitive and useful if the GUI could be used in combination with already running services.

**Comment by chia-farmer-ALBEDO** [comment]
I fully agree with this REQ. Absolutely necessary. Never a GUI must stop services... remember the Viewer-Controller model

**Comment by ThatCoffeeGuy** [comment]
Absolutely. I literally only came here to write a request like this.
