### ISSUE TITLE
GUI White Screen

### ISSUE THREAD

**Issue by csabi944** [Chia-Network/chia-blockchain-gui#403]
Hello Everyone,

My GUI Screen went to full white all of a sudden and I cant do anything.
It seems plotting goes fine, but I cant see any progress or whatever on my screen. (full white)
What can I do? If i close the GUI then all my plotting progress are trashed.
Is the reload function work properly in 1.1.4 or is there any workaround?

Thanks.
![bug](https://user-images.githubusercontent.com/42942682/118695516-96432300-b80d-11eb-8cb7-d050a58268e8.JPG)

**Comment by filipejsbrandao** [comment]
Same here, on Windows. I'm using 1.1.5 GUI. Is there a way to fix this?

**Comment by woodycal** [comment]
Been getting this issue alot on testing pools on dev branch. Appears at least in my case related to connection closed abnormally. 

![20210621_202619](https://user-images.githubusercontent.com/72100197/122819564-8ddd7c80-d2d2-11eb-9b61-e8c77c1479d1.jpg)

As you can see it bricks the gui but the top menus are still usable and doing either reload or force reload gets it back. plots are still plotting in background but i dont think wallet or farming is working.

**Comment by woodycal** [comment]
> 
> 
> Yes but after this error happens and you reload the GUI, after several hours the whole Chia crashes, only the current plots are finishing.

I have had a few system crashes / lockup but i cant really say atm if its chia doing it. Im thinking its more related to power supply on my sbc sharing same bus as my usb3 port which my ssd is plugged in.
