### ISSUE TITLE
GUI not showing plotting tasks if started from console?

### ISSUE THREAD

**Issue by timonoj** [Chia-Network/chia-blockchain-gui#411]
Hi! Due to my headless nature of my Chia server, I'm using the GUI remotely. Which leads to another issue: the GUI shows the local desktop folders as paths for a new plot, not the remote ones the server is seeing, so this will probably crash if attempted. 
Anyway: I'm using the CLI due to this problem, in order to create plots on the chosen remote path on the Chia server. But while these plotting seem to be running perfectly fine in the console, the GUI doesn't seem to react, showing only plotting tasks that have been created from the GUI.

**Comment by zerbrecht** [comment]
Just started plotting a few days ago.  Woohoo!! I also am seeing this same issue.  I am plotting on an NVMe WD AN1500. Using the CLI to plot my drives. I have the GUI pointing to my mounted drives but the GUI is not showing the plotting process.  Using another method via the CLI for the time being but would really appreciate being able to see this in the GUI.
