### ISSUE TITLE
GUI in headless mode shows local folders, not remote ones

### ISSUE THREAD

**Issue by timonoj** [Chia-Network/chia-blockchain-gui#412]
Hi,

Whenever using the GUI on headless mode (a client in my laptop connecting to a headless server running 24/7), whenever I'm trying to add a plot, the GUI will show the local paths I can see in the laptop, not the remote ones the server sees. So I'm pretty sure if I attempt to create a plot in a local path that is not literally mapped exactly the same on the server, it will fail. The GUI should in this case show remote paths contents. Or, at the very least, allow to just manually type the path (at this moment, clicking on the path ALSO launches the file picker window).

**Comment by lewixlabs** [comment]
I confirm this issue
