### ISSUE TITLE
[BUG] Can't delete plot in parallell not started - chia v 1.1.6

### ISSUE THREAD

**Issue by casa10** [Chia-Network/chia-blockchain-gui#414]
**Describe the bug**
When you plan few parallel plots, impossible to delete in the interface the plots who are not started.
The button is ike disabled.

**To Reproduce**
Each creation of plots in parallell

![image](https://user-images.githubusercontent.com/8081413/119144656-2caf5880-ba49-11eb-95d7-b6b408de6adb.png)

**Expected behavior**
Possibility to delete like in previous version

**Desktop (please complete the following information):**

- OS: Windows 10
- Chia version : 1.1.6

**Comment by seeden** [comment]
This is expected behavior for Windows users. We are working on an issue related to deleting plots. The delete button will be disabled until we fix this issue. It is related to running and queued plots as well

**Comment by Faouid** [comment]
Bad news. It was not discribed in the change log too. I can forgive you, if you can add the feature the possibility to freeze a plot under plotting phase. When in parallel, i may want to freeze one when too many plots are active at the same phase.
