### ISSUE TITLE
[BUG] "Connect to other peers": "CANCEL" button is useless

### ISSUE THREAD

**Issue by FSys77** [Chia-Network/chia-blockchain-gui#415]
After I press "CONNECT" the "CANCEL" button is greyed out, there is no way to press it. Hence it is useless.

![image](https://user-images.githubusercontent.com/81809431/119124806-5e1c2a00-ba31-11eb-9753-1a7eb82f359c.png)

**Comment by seeden** [comment]
The cancel button is used for the close dialog. If you are connecting please wait for it. We are still working on improvements
