### ISSUE TITLE
ERR_STREAM_DESTROYED - 1.1.6

### ISSUE THREAD

**Issue by katmai** [Chia-Network/chia-blockchain-gui#417]
![Screenshot from 2021-05-21 19-58-14](https://user-images.githubusercontent.com/1245160/119179536-51b6c200-ba6f-11eb-934d-4f776ac460dd.png)
after upgrading on ubuntu20 to the latest 1.1.6, i keep receiving this error pop-up. the gui still works, shows synced, so no issues there, just this error popup.

**Comment by seeden** [comment]
I will try to replicate it on my computer with ubuntu.

**Comment by katmai** [comment]
i stopped the gui today, did a git pull and install, and this error hasn't popped in about 10 hours now. so it was probably some code fixed meanwhile.
