### ISSUE TITLE
I think a print statement was left in: 'goodbit, failbit, badbit, eofbit: 0402'

### ISSUE THREAD

**Issue by salamanders** [Chia-Network/chia-blockchain-gui#418]
I see a repeating line in the console with 1.1.6
`goodbit, failbit, badbit, eofbit: 0402`

**Comment by victorarthur** [comment]
I had a similar issue. You have failed plots on your farm. It happened to me when I moved plots from the plotting machine to the farming one.

In your console, run this command:

`chia plots check -n 5 -l`

It will check your plots.

Then manually, you have to delete the failed plots.

**Comment by ThatCoffeeGuy** [comment]
~7 months later this it still not fixed, just encountered it.
