### ISSUE TITLE
[BUG] Farming Tab doesn't show harvester connections if you don't have local plots

### ISSUE THREAD

**Issue by eFishCent** [Chia-Network/chia-blockchain-gui#42]
**Describe the bug**
When running a full node with no local plots, the Farming Tab doesn't show harvester connections. It only shows Create plots wizard.

**To Reproduce**
1. Install GUI client on a machine with no local plots
2. Connect harvesters to full node

**Expected behavior**
When harvesters connect to the full node, the Create plots wizard should be removed and show the remote harvester connections: IP address, port, and up/down traffic.

**Desktop (please complete the following information):**

- OS: macOS
- OS Version/Flavor: Catalina 10.15.7

**Comment by seeden** [comment]
@hoffmang9  do you want to see a list of connections when the user has no plots?

**Comment by hoffmang9** [comment]
If harvester > 1 then we should show it below the "wizard"

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/89
