### ISSUE TITLE
Deleting button on queued plots has been disabled too

### ISSUE THREAD

**Issue by RenanSalv** [Chia-Network/chia-blockchain-gui#420]
I've seen the release notes of the last update and it contains "Disabled deletion of running plot for Windows users as the crash/lockup bug has returned.". However, i am using win 10 and the gui doesn't enable the delete button even to queued plots.

Delete button for queued plots had been useful a lot for me. I know that deleting running plots crashes the app but for queued plots used to work like a charm.

Is there a way to delete plots using commands ? tried to find and there's no information about.

Thanks a lot.

![Snap 2021-05-21 at 19 42 58](https://user-images.githubusercontent.com/7558840/119204943-2e8b1300-ba6d-11eb-9ec0-d0847e16b8dc.png)

**Comment by celalanak** [comment]
This is expected behavior for Windows users. We are working on an issue related to deleting plots. The delete button will be disabled until we fix this issue. It is related to running and queued plots as well from @seeden

**Comment by OuedraogoAbdoul** [comment]
I can confirm that the option is still available with Ubuntu 20.04
