### ISSUE TITLE
[Feature Request] save last-used plot and temp storage locations

### ISSUE THREAD

**Issue by sholinaty** [Chia-Network/chia-blockchain-gui#423]
it would be incredibly beneficial if the plotting tool were to save the last-used drives/folders to streamline creation of new plots.

this is for:
Temporary Directory
Final Directory

**Comment by bwenrich** [comment]
Reviving the stale issue. This would provide an improved user experience.

**Comment by sholinaty** [comment]
bumping to keep open, this is still an annoyance
