### ISSUE TITLE
Chia GUI crashes to "Connecting to Wallet" when deleting a plot

### ISSUE THREAD

**Issue by sampellino** [Chia-Network/chia-blockchain-gui#441]
I get the attached error in my debug log when I attempt to remove plots sometimes. It regularly happens if I'm trying to delete a plot that I just made (0%). The GUI will show "connecting to wallet" and will never stop spinning. I've lost a handful of plots at 85%+ because of this bug.

![chia_error](https://user-images.githubusercontent.com/5458241/120073223-845f4c80-c065-11eb-83d0-64932a9cf74e.PNG)

**Comment by wjblanke** [comment]
We disabled delete plots in 1.1.6 to avoid this. 1.1.6 fixes a lot of other things as well so worth upgrading. It should get fixed soon. If the crash corrupted the wallet DB, you can delete ~/.chia/mainnet/wallet and reboot/restart
