### ISSUE TITLE
[REQ] Farming Logs

### ISSUE THREAD

**Issue by DrChrisM** [Chia-Network/chia-blockchain-gui#443]
The plotter logs in the GUI are great for tracking plotting progress,  how about a similar GUI log for farming to help us know that our farms are working and meeting required time constraints.  Thanks for your help with this. 
Chris

**Comment by AndersStruck** [comment]
I agree.
Currently i am using loglevel INFO,
And using powershell to watch how the farming is going.
For now I use this command from the log directory
`Get-Content -Path .\debug.log -Wait | Select-String "plots were"`
Maybe that is a for you solution until a proper solution is implemented.
