### ISSUE TITLE
Enhancement Request: RSS feed in gui for notice of need to upgrade client.

### ISSUE THREAD

**Issue by jeffstokes72** [Chia-Network/chia-blockchain-gui#447]
Seems easy to provide a method for showing "update needed" or some other feed of news of a twitter bot or RSS feed. Outage reports, service things, client updates, etc.

**Comment by seeden** [comment]
Hi @jeffstokes72. Yeah, we want to add this feature as well.

**Comment by jeffstokes72** [comment]
@seeden Great minds :) Glad to hear it!

Yeah I figured the project could use some positive feedback loop enhancement requests.
