### ISSUE TITLE
GUI limited to showing last 5 Attempted Proofs

### ISSUE THREAD

**Issue by StogieC** [Chia-Network/chia-blockchain-gui#449]
On the GUI farm tab the "Last Attempted Proof" is showing only the last 5 results.   It would be useful to return the same number of rows in this section as connected harvesters.

**Comment by Aleksandarmkd** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/85198514/127439651-8d127b18-e420-4262-af3a-a9e10ce02912.png)

What can be the cause for different time attempts as in the screenshot?
The time varies back and forth, how is that possible?
How can the index show such a discrepancy in the challenges? I suppose it follows the challenges, but how can that be after passed time parameter?
Please advice.

**Comment by StogieC** [comment]
Modified since connected harvesters list limitation has been resolved.

**Comment by StogieC** [comment]
Still an issue in 1.2.3
