### ISSUE TITLE
not resolvable dependency building the gui on Ubuntu 20.10

### ISSUE THREAD

**Issue by l-derosa** [Chia-Network/chia-blockchain-gui#474]
despite the listed error the gui builds and seems to work, but I don't' know if there is something broken inside.
the installed react-refresh is 0.10.0, no way to downgrade or remove, the installer always picks and installs 0.10.0

npm ERR! While resolving: chia-blockchain@undefined
npm ERR! Found: react-refresh@0.10.0
npm ERR! node_modules/react-refresh
npm ERR!   dev react-refresh@"^0.10.0" from the root project
npm ERR! 
npm ERR! **Could not resolve dependency:**
npm ERR! **peer react-refresh@">=0.8.3 <0.10.0" from @pmmmwh/react-refresh-webpack-plugin@0.4.3**
npm ERR! node_modules/@pmmmwh/react-refresh-webpack-plugin
npm ERR!   dev @pmmmwh/react-refresh-webpack-plugin@"^0.4.3" from the root project

**Comment by seeden** [comment]
try to use `npm install --legacy-peer-deps`

**Comment by l-derosa** [comment]
> --legacy-peer-deps

no effect, shows the same error

i would try to modify this dependecy but i don't' know where to modify it, I already tried in the modules folder, modifying the json file of the react-refresh-webpack-plugin, but it's not enought, seems that this dependency is also written elsewhere

by the way, the original @pmmmwh/react-refresh-webpack-plugin@0.4.3 at https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/package.json has the right dependency "react-refresh": "^0.10.0", so I guess there is something broken in the package picked from the installer

**Comment by lavarok** [comment]
Same problem on Ubuntu 21.04. Cant run the gui at all.

**Comment by VivaLaRobo** [comment]
I'm also having this issue on Raspberry Pi

**Comment by VivaLaRobo** [comment]
> try to use `npm install --legacy-peer-deps`

@seeden running this results in the following error :
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/legacy-peer-deps - Not found
npm ERR! 404 
npm ERR! 404  'legacy-peer-deps@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-17T16_08_24_326Z-debug.log
```

**Comment by l-derosa** [comment]
the warning is generated by the "npm audit fix || true" command launched before the "npm run build" command at the end of the install-gui.sh script.

the issue seems to come from the json file:
~/chia-blockchain/chia-blockchain-gui/node_modules/@pmmmwh/react-refresh-webpack-plugin/package.json

which contains:
...
  **"version": "0.4.3",**
...
  "peerDependencies": {
    "@types/webpack": "4.x",
    **"react-refresh": ">=0.8.3 <0.10.0",**
    "sockjs-client": "^1.4.0",
    "type-fest": "^0.13.1",
    "webpack": ">=4.43.0 <6.0.0",
    "webpack-dev-server": "3.x",
    "webpack-hot-middleware": "2.x",
    "webpack-plugin-serve": "0.x || 1.x"
  },

the other packages in the chia-blockchain-gui requires **react-refresh": "^0.10.0"** 

what is the effect on node,farming and harvester of the broken dependency on react-refresh-webpack-plugin ?

by the way, the new "version": "0.5.0-rc.2" of the react-refresh-webpack-plugin has the right dependency **"react-refresh": "^0.10.0"**, any way to use this release?
