### ISSUE TITLE
Invalid plots report is inaccurate. User may delete perfectly valid plots.

### ISSUE THREAD

**Issue by merakmarey** [Chia-Network/chia-blockchain-gui#476]
Scenario: Multiple plotters, single or multiple farmers. 
If a plotter start to copy a file to one of the farming directories, the plot file being copied will be reported (correctly) as invalid, since the copy is still in progress. However, after the file copy is completed the plot is now valid, but still reported as invalid. 

Some users may believe file is really invalid and delete the file, losing a perfect valid plot.

A manual refresh to re-validate files only on the invalid list, a manual revalidation of the entire farm. A way to determine if file is still being copied (copy hook) and bypass verification until finished.

**Comment by haowen8905** [comment]
the same problem with u

**Comment by haowen8905** [comment]
my version is build 1.1.797

**Comment by zmej420** [comment]
This happens for me too. Initially, I was restarting my harvesters to fix it, now I am adding .tmp to the target filename until it is completed. You have a good point that some people may accidentally delete a plot that works fine.

**Comment by merakmarey** [comment]
Still no resolution.
