### ISSUE TITLE
Challenges in "Farm" windows under "Last attempted proof" appear in random order

### ISSUE THREAD

**Issue by Oscillator098** [Chia-Network/chia-blockchain-gui#488]
Describe:
Challenges in "Farm" windows under "Last attempted proof" appear in random order

Reproduce:
My computer was plotting and was overwhelming RAM so it took 30 sec to open "Task manager" to see if it froze, but it just took a little more to continue smooth operation.
Afterwards I noticed that Challenger were appearing in random order to catch up for last 45 minutes computer was a little slower.

SS:
![image](https://user-images.githubusercontent.com/47561865/125065359-02296580-e0b2-11eb-9fc2-704f37e071ce.png)

System:
Core i7 11700
32GB RAM
Windows 10
GUI v 1.2.0

**Comment by Oscillator098** [comment]
It still keeps doing it, but computer is running just fine:
![image](https://user-images.githubusercontent.com/47561865/125071528-ad89e880-e0b9-11eb-8860-73be0e42716f.png)

**Comment by temicus** [comment]
Same on my side on both my win 10 computers with 1.2.2 chia client.

It happens every time after few hours running. After that the soft refresh opening "keys" tab and clicking on it generates errors in the log and does not open GUI anymore. So I must restart the chia client every few hours. Never had this problem before. More than that one of the computers was just completely new after the installation of win 10 and still it has this problem. In the log I see that the lookups are running well... but as far as I can understand the GUI is just going wild :)

**Comment by temicus** [comment]
I just see that its somehow connected to plot creation and adding new plots or refreshing manually. If I just farm and do not touch anything it runs without this problem since few hours already.
