### ISSUE TITLE
Full Node Overview not syncing after visit to "Keys" window (only visual)

### ISSUE THREAD

**Issue by Oscillator098** [Chia-Network/chia-blockchain-gui#489]
Describe the bug
Full Node Overview keeps syncing and "Farm window appears as if it is not farming" but when looking at debug.log and PowerShell everything is fine and I'm farming normally.

To Reproduce
I visited "Keys" window and since then it won't show me Full Node Overview numbers just "loading".
I think I did it first time since installing v1.2.0.

Screenshots
![image](https://user-images.githubusercontent.com/47561865/125114991-fefe9b80-e0ea-11eb-82d3-a73438105c21.png)
![image](https://user-images.githubusercontent.com/47561865/125115023-0cb42100-e0eb-11eb-8fc0-861dd0e2ce88.png)
![image](https://user-images.githubusercontent.com/47561865/125115051-19387980-e0eb-11eb-9dfd-81be4deb2e50.png)

Desktop:
OS: Windows 10
CPU: [Intel® Core™ i7-11700 CPU]
RAM: 32GB
GUI v 1.2.0

**Comment by Oscillator098** [comment]
Closing and opening GUI doesn't fix it

**Comment by Oscillator098** [comment]
I managed to fix it:
In PowerShell I stopped every service one by one, then closed GUI, opened GUI again.
It took some time but it showed everything as it should be.

**Comment by seeden** [comment]
Can you close this issue?
