### ISSUE TITLE
Plotting at idle priority and farming at real-time priority reduces the number of late partial proofs

### ISSUE THREAD

**Issue by 125devin** [Chia-Network/chia-blockchain-gui#498]
When plotting is started in a shell running with nicer than normal cpu priority and idle disk I/O priority and the GUI is started for farming with real-time priority, there may be a reduction in late partial proofs for pooling if there were any.

Plotting (Ubuntu):
renice -n 10 -p $$
ionice -c 3 -p $$

Farming (Ubuntu):
renice -n -10 -p $$
ionice -c 1 -p $$

The chia software could be updated to support this automatically for plotting and farming on the same computer.

**Comment by DrRenz** [comment]
Still looks like a worthwhile feature to me.
