### ISSUE TITLE
error: Your local changes to the following files would be overwritten by checkout:

### ISSUE THREAD

**Issue by softwareuser99** [Chia-Network/chia-blockchain-gui#507]
Applies to: Latest Version: 1.2.3 - 2021-07-26
Happens when: upgrading from 1.2.2 to 1.2.3
OS: Ubuntu 20.04 LTS terminal

Comments:
Just FYI when following the "old" upgrade instructions [here](https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian), below error pops up (ubuntu 20.04). Solution is probably just to add this to the below upgrade procedure:

`git checkout -- .
`
```
# The GUI requires you have Ubuntu Desktop or a similar windowing system installed.
# You can not install and run the GUI as root
cd chia-blockchain-gui
git fetch
cd ..
chmod +x ./install-gui.sh
./install-gui.sh

cd chia-blockchain-gui
npm run electron &
```

Installing on Ubuntu 20.04 LTS or newer: Using installed node.js version.
Running git submodule update --init --recursive.

error: Your local changes to the following files would be overwritten by checkout:
	src/locales/ar-SA/messages.po
	src/locales/be-BY/messages.po
	src/locales/bg-BG/messages.po
	src/locales/ca-ES/messages.po
	src/locales/cs-CZ/messages.po
	src/locales/da-DK/messages.po
	src/locales/de-DE/messages.po
	src/locales/el-GR/messages.po
	src/locales/en-AU/messages.po
	src/locales/en-NZ/messages.po
	src/locales/en-PT/messages.po
	src/locales/en-US/messages.po
	src/locales/es-AR/messages.po
	src/locales/es-ES/messages.po
	src/locales/es-MX/messages.po
	src/locales/fa-IR/messages.po
	src/locales/fi-FI/messages.po
	src/locales/fr-FR/messages.po
	src/locales/hr-HR/messages.po
	src/locales/hu-HU/messages.po
	src/locales/id-ID/messages.po
	src/locales/it-IT/messages.po
	src/locales/ja-JP/messages.po
	src/locales/ko-KR/messages.po
	src/locales/nl-NL/messages.po
	src/locales/no-NO/messages.po
	src/locales/pl-PL/messages.po
	src/locales/pt-BR/messages.po
	src/locales/pt-PT/messages.po
	src/locales/ro-RO/messages.po
	src/locales/ru-RU/messages.po
	src/locales/sk-SK/messages.po
	src/locales/sq-AL/messages.po
	src/locales/sr-SP/messages.po
	src/locales/sv-SE/messages.po
	src/locales/tr-TR/messages.po
	src/locales/uk-UA/messages.po
	src/locales/zh-CN/messages.po
	src/locales/zh-TW/messages.po
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout 'bd3f816ef60402717a0c8636888da94abf342b46' in submodule path 'chia-blockchain-gui'

**Comment by seeden** [comment]
Hi. Just discard all /locales/**/messages.po changes and try to run your command again
