### ISSUE TITLE
Pool Contracts Missing

### ISSUE THREAD

**Issue by joaoroman23** [Chia-Network/chia-blockchain-gui#509]
After reinstal Chia Blockchain, and the Full Node Sinced, the Pool Contracts are missing in the Pool tab.
in my case, there were supposed to be 3 contracts
![Capturar](https://user-images.githubusercontent.com/88071121/127260626-a897cf43-070c-453f-a999-8614ee6aa35a.PNG)

Windows 10

**Comment by emlowe** [comment]
Your wallet must also be synced and make sure you are using the correct key if you have multiple keys

**Comment by joaoroman23** [comment]
yes, it's the correct key, the plots are farming

**Comment by joaoroman23** [comment]
I deleted the wallet DB, after resync the pool contracts are showed
