### ISSUE TITLE
BUG,'pool' Tab in the GUI

### ISSUE THREAD

**Issue by fangqiluxatu** [Chia-Network/chia-blockchain-gui#510]
After i've clicked Save button in option 'Edit Payout Insructions',the pop-up window still appears.
![image](https://user-images.githubusercontent.com/12740092/127608384-d0a600b6-7068-4401-8dae-808e849a1a0e.png)

**Comment by seeden** [comment]
Hi @fangqiluxatu. Which version are you using? I will take a look.
