### ISSUE TITLE
config.yaml still not updating Receive Key after creating new Private Key - Today I lost my first 2XCH - check your config.yaml and compare address

### ISSUE THREAD

**Issue by hejz0r** [Chia-Network/chia-blockchain-gui#518]
As in topic - I started farming in April, today I "received" my first 2 XCH. But 0XCH in GUI & explorer.
I checked block info, and my pool public key was matching, but not the Farmer Reward Address - it was different from the GUI address.
I checked config.yaml  ... and there was it .. receive address from my first "test" wallet and private key. Of course I don't have mnemonic, of course GUI was showing different receive address than this in config.yaml - config was not updated to a new private key addresses

Thanks Bram, I was waiting for my first earnings from april, when I finally win something, I don't get it.

**Comment by seeden** [comment]
Hi @hejz0r. Just for clarification. Is your wallet fully synced? Is wallet height  === full node peak height? If not you need to wait for synchronization.
