### ISSUE TITLE
Wallet History has setting for "Rows per page:" = 100, but only shows last 50.

### ISSUE THREAD

**Issue by StogieC** [Chia-Network/chia-blockchain-gui#525]
Reproducible on any wallet with over 50 transactions by selecting 100 rows per page
Either limit to 50 rows per page or change max history limit to display 100 transactions.

**Comment by second-one** [comment]
I really need this feature. The GUI should show ALL transactions. And since they are in the Blockchain anyway, it shouldn't take up any additional space.

**Comment by second-one** [comment]
Any news about this issue? Should be a matter of minutes to fix this.

**Comment by Niko-CZ** [comment]
+1.
This issue makes accounting reporting complicated.
I can see several bugs marked as "closed", but in fact issue still actual in latest version.
Was it really resolved?

**Comment by second-one** [comment]
Thank you very much. Will it be possible to see the whole history or just the last 100 transactions?

**Comment by seeden** [comment]
I already added the ability to see the whole history. If everything goes fine it will be part of next release
