### ISSUE TITLE
GUI not work if large farm size

### ISSUE THREAD

**Issue by nozer0** [Chia-Network/chia-blockchain-gui#528]
The GUI has no response when the connect farm size is large than **8Pb**.
We have a separate machine( i7 10700+16g ram ) to run the GUI program,
and connect to other farm machines in the same LAN, when the total size is close to the 8Pb, the GUI goes down;
even the size is less than 8Pb, it won't go down but still very slow when do the tab switching operation.

**Comment by seeden** [comment]
Thank you. I will try to optimize GUI with prepared mocked data and simulate 8PT.

**Comment by zhangcloud** [comment]
Hi all,
    when My farm Capacity reach 8.8PB, my harvester repeating Reconnecting to farm node;Cause farm capacity to drop too much; restart some harvester node ,cause More farm capacity down; finally, restart farm node software, total farm capacity recovery again; but I Worry about running for a while and then having problems again; Even if the GUI part cannot be displayed, make sure other functions are normal,Don't want to lose the chance to get a prize;

**Comment by jcteng** [comment]
usePlots hook cost too much cpu time. use this version as replacement. should be fine.
https://gitee.com/ext9/ext9-gui/blob/net9.dev/src/hooks/usePlots.ts

**Comment by zhangcloud** [comment]
Hi @jcteng 
    but How do I replace the useplots and take effect when running under Window OS;Can you tell me the replacement steps? Thank you for your help

**Comment by jcteng** [comment]
@zhangcloud  simple replace this .ts file. then rebuild the gui via 
```bash
node winstaller.js
```

**Comment by seeden** [comment]
@jcteng thank you. I will integrate it into our GUI. We are going to add pagination for plots as well in the short run. It will help a lot.

**Comment by jcteng** [comment]
Glad to know that

**Comment by jcteng** [comment]
@seeden  FarmLastAttemptedProof component also need throttle with huge number harvester connected. 
Ext9-gui repo also added throttle for this,

**Comment by emlowe** [comment]
@jcteng please feel free to submit any PRs

**Comment by 0X1231** [comment]
1.7P的我也是很卡！

**Comment by 0X1231** [comment]
此情况目前还是存在，并未得到解决！

**Comment by seeden** [comment]
Already fixed and available in next release 1.3.5
