### ISSUE TITLE
Speed up 100% status

### ISSUE THREAD

**Issue by akmost** [Chia-Network/chia-blockchain-gui#532]
Hey guys,

I wouldn't say this is an issue however I'm not sure where I go to add request sorry new to GitHub.. anyways

Can we add a line of code that checks if the temporary and final destination are on the same drive.

If so, cut and paste to the final directory folder would be amazing as the current process (copy & paste) wastes too much time

I know there's other programs that i can use but for newcomers it will speed the process.

**Comment by hoffmang9** [comment]
Doing this cross platform is a lot harder than you might first imagine. At some point we may add this on a per platform basis but it is not going to be in the next month or two.

If the temp2 and final directory are on the same disk, the OS will generally not do a full copy but will just relink it.
