### ISSUE TITLE
what means: goodbit, failbit, badbit, eofbit: 0402

### ISSUE THREAD

**Issue by Kfagermo** [Chia-Network/chia-blockchain-gui#534]
Been getting close to a 100 plots now, but im often getting this goodbit, failbit, badbit, eofbit: 0402 since the last 10 plots.

When i get to fix it, it seems to only temperarly fix it. Can someone help identify the problem?

Using ubuntu, which is not very coopertative as to permission. chmod 777 seem to only help for a short time...
(Im no linux expert, google myself to most info i need)

**Comment by wjblanke** [comment]
seekg or read is going past the end of a file (failbit and eofbit set). Maybe one of your plots has been truncated? Or maybe it is being farmed while the plot was being copied?

    // Using this method instead of simply seeking will prevent segfaults that would arise when
    // continuing the process of looking up qualities.
    static void SafeSeek(std::ifstream& disk_file, uint64_t seek_location) {
        disk_file.seekg(seek_location);

        if (disk_file.fail()) {
            std::cout << "goodbit, failbit, badbit, eofbit: "
                      << (disk_file.rdstate() & std::ifstream::goodbit)
                      << (disk_file.rdstate() & std::ifstream::failbit)
                      << (disk_file.rdstate() & std::ifstream::badbit)
                      << (disk_file.rdstate() & std::ifstream::eofbit)
                      << std::endl;
            throw std::runtime_error("badbit or failbit after seeking to " + std::to_string(seek_location));
        }
    }

    static void SafeRead(std::ifstream& disk_file, uint8_t* target, uint64_t size) {
        int64_t pos = disk_file.tellg();
        disk_file.read(reinterpret_cast<char*>(target), size);

        if (disk_file.fail()) {
            std::cout << "goodbit, failbit, badbit, eofbit: "
                      << (disk_file.rdstate() & std::ifstream::goodbit)
                      << (disk_file.rdstate() & std::ifstream::failbit)
                      << (disk_file.rdstate() & std::ifstream::badbit)
                      << (disk_file.rdstate() & std::ifstream::eofbit)
                      << std::endl;
            throw std::runtime_error("badbit or failbit after reading size " +
                    std::to_string(size) + " at position " + std::to_string(pos));
        }
    }
