### ISSUE TITLE
Chia gui is constantly frozen after some time of working

### ISSUE THREAD

**Issue by mrgreen1234** [Chia-Network/chia-blockchain-gui#548]
I have been farming chiu for a long time, and every now and then chia gui freezes on its own. Numerous updates for the gui have already come, but none have solved the existing problem. The biggest problem arises when I don’t get a reward for a frozen gui chia reward. Here yesterday were 3 blocks, with two blocks in a row at night. I got from the first block only because of the accumulated points inside the pool, and for the other two blocks I didn't get any rewards because the chia gui froze on its own. This is really unacceptable for a project like this. If we are thinking of building a better future, it is time to start from scratch. Please focus on the basics of this project. It is impossible for miners to mine xch on such a bad chia gui. Thank you.

**Comment by Drakanus** [comment]
Same here.. it is insane to restart GUI each 5-6 hours..
