### ISSUE TITLE
Dates are formatted badly

### ISSUE THREAD

**Issue by phieri** [Chia-Network/chia-blockchain-gui#577]
The date format appears to be hardcoded to American format, giving a bad experience to others.
https://github.com/Chia-Network/chia-blockchain-gui/blob/0b00e701b1efe74e1ae475ab06f32b4153a2534f/src/util/utils.js#L5

**Comment by seeden** [comment]
We already started to use momentjs for dates. Mentioned functionality is deprecated and will be removed soon

**Comment by phieri** [comment]
This is now fixed in Chia 1.3. Closing this issue.
