### ISSUE TITLE
About dialog box opens links inside itself 1.2.11, ok on 1.2.9

### ISSUE THREAD

**Issue by voidxno** [Chia-Network/chia-blockchain-gui#578]
About dialog box window (Menu: Help / About Chia Blockchain), opens links inside itself (1.2.11). On 1.2.9 it opened external/default browser of OS. All other Help menu items on 1.2.11 still opens new/external browser window.

To test (on 1.2.11):
- Open About dialog box windows (Menu: Help / About Chia Blockchain)
- Mouse click on the Chia logo inside window (web-link)
- Web-page is opened inside the About dialog window itself
- On 1.2.9 it opened a new/external browser window

Looks like [commit from 04oct in](https://github.com/Chia-Network/chia-blockchain-gui/commit/56f6c3edcc77abf1b043a1e03e3b5de02655d3a0#diff-79dc0034f3b3eb811f678eaebf47c031291d59254f35809c5bcdeb6e57a1e102) src/electron/main.tsx ('function openAbout()') changed the behavior.

![AboutDialog](https://user-images.githubusercontent.com/53347890/141968733-63b4c00a-46f1-4a4b-a826-cb1678e8a2c0.jpg)

**Comment by seeden** [comment]
Thank you. I will fix it

**Comment by seeden** [comment]
This issue was already fixed. I am closing it
