### ISSUE TITLE
BUG: light wallet UI lag on sending transaction

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain-gui#580]
100% reproducible on M1 Mac client version 257

Send on a transaction, and the UI doesn't immediately update. It shows a spinner on the Send button. To clear this spinner I usually have to switch between wallets such as toggle between XCH and MRMT wallets.  

Expected result: the transaction should immediately appear below in the Transaction list as pending, and a dialog box should show that it has been submitted.

**Comment by seeden** [comment]
This issue was already fixed. I am closing it
