### ISSUE TITLE
Passphrase in incorrect after restarting a computer 

### ISSUE THREAD

**Issue by abdul-jalil** [Chia-Network/chia-blockchain-gui#591]
Hello,
I'm getting the bellow error when I'm trying to lunch CHIA GUI:

<img width="281" alt="image" src="https://user-images.githubusercontent.com/19950003/145061501-4435a4cd-eb7b-4ee0-9c94-dc66e07c90c5.png">

I'm sure about the passphrase. but the error is very confusing.

**Comment by emlowe** [comment]
Note the passphrase is not your 24 words. Do you have your 24 words backup?

Please specify the OS used here.

**Comment by emlowe** [comment]
Stop chia and rename the file `%HOMEDRIVE%%HOMEPATH%/.chia_keys/keyring.yaml` - restart chia.

**Comment by abdul-jalil** [comment]
Will I lose what I farmed?

**Comment by emlowe** [comment]
In all cases, if you have 24 words nothing can be lost.

However, in the case of this is a key you have had for awhile, then that key is also still in the old keyring place and so it will just appear without needing the passphrase.

**Comment by abdul-jalil** [comment]
> In all cases, if you have 24 words nothing can be lost.
> 
> However, in the case of this is a key you have had for awhile, then that key is also still in the old keyring place and so it will just appear without needing the passphrase.

Thanks. I'll give it a shot and get back to you.

**Comment by abdul-jalil** [comment]
> %HOMEDRIVE%%HOMEPATH%/.chia_keys

It works. Thank you so much.
