### ISSUE TITLE
Plotting progress gets lost in GUI after Reload

### ISSUE THREAD

**Issue by raminrahimzada** [Chia-Network/chia-blockchain-gui#605]
This is not a breaking issue but would be great if You fix it :
Plotting progress gets lost and shows zero in GUI/Plots section after - Reload (View->Reload) or Force Reload (View->Force Reload)
But when you open menu (View Log) of ongoing plot you can see the correct progress percent by looking for the latest progress log
When the next progress log appears in logs, progress percent show the correct value, till that it just shows zero
My app version is 1.2.11

**Comment by seeden** [comment]
Hi @raminrahimzada. Thank you. We completely changed how UI is working with this data. It should be fixed in the next release.
