### ISSUE TITLE
[Feature Request] Show last block proof found/won

### ISSUE THREAD

**Issue by dorkmo** [Chia-Network/chia-blockchain-gui#63]
one change that might be nice in the gui would be to have another list on the farm page that shows that last challenge proof that the farmer was awarded a coin for. thanks!

**Comment by hoffmang9** [comment]
![image](https://user-images.githubusercontent.com/30377676/108572773-e15da080-72c7-11eb-8713-ae20b2f26aac.png)

That's what this does.

**Comment by dorkmo** [comment]
lol oh duh. sorry about that
