### ISSUE TITLE
Offer - Cancel on blockchain fee warning (beta1.3-dev284)

### ISSUE THREAD

**Issue by loppefaaret** [Chia-Network/chia-blockchain-gui#633]
Chia beta 1.3 (dev284)
When the mempool is filled, and users want to cancel an offer on blockchain, they are warned by using a 0.00005 XCH fee:
![Screen Shot 2022-02-22 at 7 17 22 AM](https://user-images.githubusercontent.com/32275244/155176651-ecff9e4f-4de8-46ef-8958-60f97a0a5b91.png)

Whether there should be a warning at that level, a different message, or moving the warning threshold im not sure. But it does seem a bit out of place in its current form.

**Comment by seeden** [comment]
I changed the threshold value to 100,000,000,000 mojos until we add fee estimator
