### ISSUE TITLE
Expected tabbing behavior is broken on the nemonic screen.

### ISSUE THREAD

**Issue by sethjenks** [Chia-Network/chia-blockchain-gui#645]
### What happened?

The expected behavior is that when a word is being typed the list will select whichever word it thinks is closest. If the user wants to select that word they will hit tab or **enter** to select it and move to the next field. This is not the case currently. 

### Version

1.2.12

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by lipalong** [comment]
Fixed with PR #652
