### ISSUE TITLE
Farm stats reset to 0 on update to 1.3.0

### ISSUE THREAD

**Issue by nanciog** [Chia-Network/chia-blockchain-gui#651]
I just updated to version 1.3.0 and noticed that the FARM stats have reset to 0 (zero). The wallet still has all my coins and the command-line farm summary still shows the correct farm stats. This was before the db upgrade but I am upgrading the db now.

Same issue found on flax 0.1.6 which is based on chia 1.3.0 so I guess there is something off in the GUI.

![Screen Shot 2022-03-09 at 3 58 01 PM](https://user-images.githubusercontent.com/63633033/157397633-60b2b72e-ac82-413d-b7e6-30d09084f175.png)

**Comment by ChiaMineJP** [comment]
Try the following:
1. Click Wallets tab
2. Select CH21 then revert to XCH
  ![image](https://user-images.githubusercontent.com/84098616/157443017-04afecf2-1cca-47ce-a33c-85e27071e6e0.png)
3. Click Farm tab and check Farmed amount shows correct value.

**Comment by nanciog** [comment]
I did as adviced above but that did not work either.

However, I decided to close the GUI and restart it and it now shows the correct farm stats. I don't know if the advice above was instrumental to have it work or if the restart was all that was necessary or if the db upgrade (which I performed earlier)  was. All I know is that after restarting the GUI it now shows the correct stats.

Thanks for the advice anyway :)

**Comment by seeden** [comment]
I will check if we are invalidating cache correctly for these values

**Comment by nanciog** [comment]
Just in case cross-referencing would help, I mentioned above that this also occurred on Flax 0.1.6 which is based on Chia 1.3.0. Flax had no option for a different CAT wallet but after restarting the GUI it also showed the correct farm stats.

**Comment by seeden** [comment]
I created PR which will refresh these values https://github.com/Chia-Network/chia-blockchain-gui/pull/653
