### ISSUE TITLE
Is it possible to improve the display panel of the harvester 

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain-gui#666]
Is it possible to improve the display panel of the harvester to display the working status of each harvester and the corresponding capacity.

**Comment by germanfidalgo** [comment]
I also think this is a good adition. Since last update to 1.3.1 i cant any longer remove a harvester to force it reconnect (if i detect my total plot number has gone lower than spected i have to guess which harvester is not sending its data, as they all appear as normally conected)

**Comment by germanfidalgo** [comment]
not an stale-issue

**Comment by seeden** [comment]
Whole plotting page was changed via https://github.com/Chia-Network/chia-blockchain-gui/pull/713

**Comment by seeden** [comment]
Merged
