### ISSUE TITLE
Farming reward target address 1.3.3 Windows

### ISSUE THREAD

**Issue by loppefaaret** [Chia-Network/chia-blockchain-gui#674]
Chia 1.3.3 (and 1.3.1)
Windows 10

When inputting a wallet receive address from an imported key, the GUI warns that "No private keys..." despite that this address is from a wallet under a key imported on system.
![image](https://user-images.githubusercontent.com/32275244/161421340-040447f8-5aac-427d-8b3c-3670099ae5d0.png)

**Comment by alnuweiri** [comment]
I am having the same problem!

**Comment by seeden** [comment]
It should be fixed in the latest version. Please reopen this issue if you still see this issue
