### ISSUE TITLE
1.3.2.dev156 - GUI - "Connected" indicator at top right is ???

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain-gui#685]
It's a bit confusing as to what the "Connected" box at the top right of the GUI is supposed to represent. I've heard that it represents the wallet connections, but I've had it show `Not connected` when that wasn't true, and also show `3` when that wasn't true either.

It isn't visible in the video below, but I checked my wallet connections in the CLI, and my wallet was only connected to my local trusted node. Forcing a refresh seems to make it show accurate info, but the number also updates frequently enough that it doesn't quite seem to indicate that it's stuck, and in need of a refresh.

https://user-images.githubusercontent.com/8990544/163346669-f297676b-01dc-41fc-b6c8-aeb489ded225.mp4

**Comment by seeden** [comment]
I fixed Not Connected problem via https://github.com/Chia-Network/chia-blockchain-gui/pull/692.
It is little bit confusing but: number (3) means number of wallet connections and not "full node" connections. I will work with @sethjenks on improvements

**Comment by seeden** [comment]
Fix was merged already
