### ISSUE TITLE
1.3.4 - Windows - Farming Tab displays Errors with large number of plots/directories 

### ISSUE THREAD

**Issue by rkroelin** [Chia-Network/chia-blockchain-gui#695]
Seeing some issues with the new windows UI. (love the design though)  It almost seems like the UI gets disconnected from the underlying services/daemon.  

At first start of the appl, clicking on the Farming tabs goes to "connecting to daemon" when trying to load the farm tab.  Eventually it loads and shows several errors:
![image](https://user-images.githubusercontent.com/53322426/164129096-3c1b82bd-65f1-4184-a682-507c5e2c9248.png)

The log is updating merrily with all the expected entries but the UI farmer page shows error on the categories, says plots are unavailable etc.

10,628 plots spread across a 60 bay JBOD and an 84 bay JBOD.  Initially had ~300 folders specified in the config, many of which were empty.

Pruned the folder list to 200 with no changes.

Further pruned to 168 folders, with zero empty and it works fine now except browsing to the Plots or Farming tab is exceedingly slow.  Will create a different issue for that.

Thanks!

**Comment by rkroelin** [comment]
Also, chia farm summary shows the correct data.  Eventually also noticed that the pools tab goes blank and the full node tab says error instead of connected.

**Comment by seeden** [comment]
Can you add also error which you can see in the tooltip? This issue is probably related to to the backend.

**Comment by StogieC** [comment]
This is the associated log error:

> 2022-04-21T07:44:45.163 daemon main                   : ERROR    Unexpected exception trying to send to websocket: Cannot write to closing transport Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 239, in incoming_connection
  File "aiohttp\web_ws.py", line 300, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 650, in sendframe
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport

**Comment by StogieC** [comment]
At least on my system...  The Plots and Farming tabs load very very slowly (~45 sec.), but without erroring, with up to 9,999 plots online.

**Comment by seeden** [comment]
We are going to add pagination for list of the plots and harvesters.

**Comment by seeden** [comment]
We are working on improvements related to this problem
https://github.com/Chia-Network/chia-blockchain-gui/tree/harvesters_pagination

**Comment by seeden** [comment]
Updated plotting page was merged
