### ISSUE TITLE
1.3.4 - Windows - Plots and Farming tabs take 30+ Seconds to load with a large number of plots/directories

### ISSUE THREAD

**Issue by rkroelin** [Chia-Network/chia-blockchain-gui#696]
With 10,628 plots and 168 directories the Farming and Plots tabs take 30+ seconds to load.  This does not include initial startup, this occurs every time the user clicks on one of the tabs.  Other tabs operate lickity split.  Farming works as expected.

Thanks!

**Comment by seeden** [comment]
We are working on improvements related to this problem
https://github.com/Chia-Network/chia-blockchain-gui/tree/harvesters_pagination

**Comment by seeden** [comment]
Fixed with https://github.com/Chia-Network/chia-blockchain-gui/pull/713
