### ISSUE TITLE
1.3.4 - GUI on Ubuntu 20.04 LTS extremely non-responsive and instable

### ISSUE THREAD

**Issue by softwareuser99** [Chia-Network/chia-blockchain-gui#703]
### What happened?

First, I updated 1.3.3. to 1.3.4 (3 farmers, then the node, all Ubuntu 20.04 LTS). The GUI was acting up. So I zipped the chia-blockchain folder and renamed it. Then fresh install of 3.3.4 from source per the instrucsions on the github INSTALL from source section.

GUI is very slow, when you click on icons in the left taskbar (node has 24 cores and 32GB ram so not a resource problem for sure). Previous versions were fine. If you click too much, the screen of the GUI goes white and everything freezes.

Please advise what diagnostic data you would need me to provide.

### Version

1.3.4

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
please advise what you need, happy to update the ticket.
```

**Comment by BigSilverOrb** [comment]
How many plots total in the farm?

**Comment by seeden** [comment]
Probably fixed with https://github.com/Chia-Network/chia-blockchain-gui/pull/713

**Comment by BigSilverOrb** [comment]
Update all harvesters, I presume?

**Comment by seeden** [comment]
Merged

**Comment by BigSilverOrb** [comment]
The problem does not appear to have been fixed...
