### ISSUE TITLE
Share on DEX is defaulted to cancel [enhancement]

### ISSUE THREAD

**Issue by ects-io** [Chia-Network/chia-blockchain-gui#711]
### What happened?

When you create an offer, after saving the offer file, you get the dialog to share the offer to dexes. There the CANCEL button is highlightened in green and the SHARE button is not. I think it should be the other way round. And on the dialog before where you can choose on which DEX you want to post you can post an offer twice on the same DEX without a hint from the GUI, one could change this as well.
There is the Create an Offer screen. There should be the fee shown in Mojo below the Fee editbox just for convenience and to prevent misscounting of the zeros.
Everything else looks pretty well gj!
A horizontal scrollbar(or a hide tokenlist) on the tokentab/Transactions could be handy. My 2022 steam deck doesn't have a high enough resolution to show all informations without marking the text to scroll to the right, but the first two issues are of a  more general interrest I guess.

### Version

3.4.5

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
These issues should be addressed with the new designs and changes that have gone. If there's still anything else outstanding, please submit a new issue for us to track
