### ISSUE TITLE
Need UI hints or tooltips for basic info

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain-gui#72]
Users are confused about these three points:
- Transactions are not available within the first 10k blocks (it will be more in mainnet). Maybe gray out the "Create Transaction" pane?
- What is the transaction fee to use? (it can be set to 0 or something really low like 0.001
- How long do transactions take? (Maybe add this in the confirmation message or in a tooltip)

**Comment by seeden** [comment]
@mariano54 what is a good description for "How long do transactions take?"

**Comment by hoffmang9** [comment]
It can take 55 to 65 seconds for a next transaction. Maybe just say "On average there is one minute between each transaction block. Unless there is congestion you can expect your transaction to be included in less than a minute."

**Comment by etr2460** [comment]
It looks like this hasn't been addressed yet, I'm going to try taking some of it on since it's labeled as "good first issue"

**Comment by seeden** [comment]
PR already merged. I am closing
