### ISSUE TITLE
[Bug] The capacity exceeds the 1PBGUI and runs very slowly.

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain-gui#720]
### What happened?

The capacity exceeds the 1PBGUI and runs very slowly.

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
It will be fixed in next release 1.3.5

**Comment by 0X1231** [comment]
> 它将在下一个版本 1.3.5 中修复

非常感谢
