### ISSUE TITLE
[Bug] GUI shows error, but tx was submitted

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain-gui#733]
### What happened?

When submitting a transaction, the wallet submits to multiple nodes.
The GUI then calls getTransaction, which will return the TX with all the results
Let's say one node responded but it was an error (NO_TRANSACTIONS_WHILE_SYNCING).
At this point, the GUI just displays the error. It appears the transaction failed. This caused me to retry, and i actually ended up making 2 identical transactions
Suggested fix: If getTransaction returns a transaction that has some errors, show the errors, but also show: Transaction will be retried, and might succeed in the future
also we can retry for several seconds in case another node responds and sets the status

### Version

main

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by mariano54** [comment]
Any progress on this @seeden ?

**Comment by mariano54** [comment]
Bump @seeden

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/1004
