### ISSUE TITLE
Starting multiple plots delayed only delays one.

### ISSUE THREAD

**Issue by mondrus** [Chia-Network/chia-blockchain-gui#75]
Start plotting multiples. Delay for some time. Observe that only one plot is delayed while rest start immediately

**Comment by seeden** [comment]
@mondrus  can you share more details from "add a plot" page?

**Comment by mondrus** [comment]
I can't screen shot right now, but here's how you replicate (or at least how it happened to me).

Have 2 plots running. Add 2 more plots, specify parallel, time delay of 120 min.

Observe, 3 plots now running, 1 plot delayed. Should be 2 plots delayed.

I'll guess the code that delays plots defaults to 1 rather than n. 

Does that help?

**Comment by seeden** [comment]
@hoffmang9 I think this is expected behavior. Do you want to change it?

**Comment by hoffmang9** [comment]
For now, the delay is between the plots started together and not yet a pipeline of sorts.

Closing as we'll address this soon.
