### ISSUE TITLE
restore smart wallets page missing from crowdin

### ISSUE THREAD

**Issue by ordtrogen** [Chia-Network/chia-blockchain-gui#79]
I can't find these text messages for translation in Crowdin

(see next comment)

**Comment by ordtrogen** [comment]
![Skärmavbild 2021-02-22 kl  19 51 32](https://user-images.githubusercontent.com/15184875/108755680-d9ac2f00-7547-11eb-9651-04bcbd3bde7d.png)

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/88
