### ISSUE TITLE
Suggestion: change "Create Trade" to "Create Offer"

### ISSUE THREAD

**Issue by ordtrogen** [Chia-Network/chia-blockchain-gui#80]
I think the left column should have 

Trade Overview
Create Offer
View Offer

It looks more symmetrical that way, and when you select "Create Offer" the right pane says "Create Trade Offer" which makes sense. Also, click on "Trade Overview" and you'll see "Offers Created" which supports that left column should have "Create Offer" instead of "Create Trade"

![Skärmavbild 2021-02-22 kl  20 04 12](https://user-images.githubusercontent.com/15184875/108756713-2f350b80-7549-11eb-96b6-798a8f943d73.png)

Also 2:  The right pane of Trade Overview under Offers Created should maybe say "Offers will show up here" instead of "Trades will show up here". And have Offer ID instead of Trade ID in header

![Skärmavbild 2021-02-22 kl  20 06 02](https://user-images.githubusercontent.com/15184875/108756909-70c5b680-7549-11eb-8c3e-4d614ca6f977.png)

**Comment by hoffmang9** [comment]
Also in https://github.com/Chia-Network/chia-blockchain-gui/pull/82
