### ISSUE TITLE
Change "Select coin type" to "Select coin colour" in Create Trade Offer

### ISSUE THREAD

**Issue by ordtrogen** [Chia-Network/chia-blockchain-gui#81]
Enter an arbitrary amount and press the Add button

![Skärmavbild 2021-02-22 kl  20 14 15](https://user-images.githubusercontent.com/15184875/108757820-a0c18980-754a-11eb-8a2c-24207fa69f86.png)

Popup dialog says "Please select coin type". I think it should say "Please select coin colour" as that is what is being requested

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain-gui/pull/82

Have an unrelated issue but that will address it
