### ISSUE TITLE
[Bug] Force reload required to see NFTs

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain-gui#820]
### What happened?

I just accepted my first NFT offer. I guess that created the NFT wallet. However nothing showed up in the NFT walet until i force reloaded
Main branch 4a69bc16135dcb36cf153f6c13924de6c681afec

### Version

main

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/1730 it will be part of 1.8.1
