### ISSUE TITLE
[Bug] GUI contains untranslated elements, despite 100% translation reported on Crowdin

### ISSUE THREAD

**Issue by atomsymbol** [Chia-Network/chia-blockchain-gui#822]
### What happened?

For example, the following Chia wallet screenshots contain a mixture of English and Slovak words/terms, but all instances of the word "Send" are translated at Crowdin.

![Screenshot_20220630_070055](https://user-images.githubusercontent.com/22368256/176596686-5ca22aa4-3243-4c3a-ba3c-a7c9c488eb37.png)

![Screenshot_20220630_070112](https://user-images.githubusercontent.com/22368256/176596689-c6476f9e-187b-46ff-993d-ac3d7bac2b0a.png)

### Version

1.3.6.dev1020

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
chia-blockchain: git commit 4a69bc16135dcb36cf153f6c13924de6c681afec
chia-blockchain-gui: git commit f62c216cce6b89ef23a1b2b0a2dd6fc2a439649a
```

**Comment by seeden** [comment]
We are merging translations from 3 packages, and unused translations override correct translations. Therefore, I will remove unused translations after merge next week.

**Comment by seeden** [comment]
I am closing this issue. Fix was merged already

**Comment by atomsymbol** [comment]
https://crowdin.com/project/chia-blockchain/sk: 100% translated now.
