### ISSUE TITLE
[Bug] NFT with an image that does not match the on-chain hash is not being flagged with the "Image Hash Mismatch" overlay

### ISSUE THREAD

**Issue by sargonas** [Chia-Network/chia-blockchain-gui#828]
### What happened?

I have an NFT that was mistakenly minted with the same image hash of the NFT minted before it, which therefore does not match the hash of the image itself in the URI.

Expect Result: The NFT, in my wallet view, will have a grey bubble over it that says "Image Hash Mismatch".
Actual Result: The NFT looks normal.

The NFT using the wrong hash:
Entrance to Endor
NFT ID: `nft1eym5c5ck0yapdqsxwq3mu4uqnaksld9j9urh38lg2j3vlzqv7hkqlmwf57`
Image URI: `https://qqhbaojbnaludo6ghdrpkuqjstcnkadfqsh3lkrrku5o7c3zdi.arweave.net/hA4QOSFoF0G7x_jji9VIJlMTVAGWEj7WqMVU674t5Gs`
Invalid Image Hash on chain: 0x1af9e2e8d989591a37cc88438e653686e437973752f22c7ff84998ed61631e01

The NFT with this correct hash
Washington Square Park
NFT ID:`nft1r9dk7ccgs09q2fqnaga2mp33hw452y2f8634udpemfvkjxe5zdyq7a548y`
Image URI: `https://hvm7rlix4a7zdxryk6frfr2dtjz4zabvq4ho23a6eq35lqd33e.arweave.net/PVn4rRfgP5HeOFeLEsdDmnPMgDWHDu1sHiQ31_cB72U`
Valid Image Hash on chain: 0x1af9e2e8d989591a37cc88438e653686e437973752f22c7ff84998ed61631e01

<img width="1170" alt="Screen Shot 2022-07-04 at 09 58 47" src="https://user-images.githubusercontent.com/45463/177195935-b349c556-bf41-49be-b9e1-a1dea254e724.png">
<img width="1313" alt="Screen Shot 2022-07-04 at 09 49 10" src="https://user-images.githubusercontent.com/45463/177195945-fe48e00f-324c-46fd-b590-866e95b048e4.png">
<img width="459" alt="Screen Shot 2022-07-04 at 09 48 42" src="https://user-images.githubusercontent.com/45463/177195949-e331193f-9657-4cc0-9bec-d5fdac5752a8.png">

### Version

1.4

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by sargonas** [comment]
@wallentx *cough*

**Comment by paninaro** [comment]
Nice catch. Only occurs with NFT content > the auto-preview size threshold (10 MB currently). When "Show Preview" was clicked, we were proceeding to load the content without validating the hash. The fix ensures that we validate the hash in this case.
