### ISSUE TITLE
[Bug] Wallet connection count does not update

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain-gui#830]
### What happened?

I had 4 connections on my wallet, since my full node was not synced. The GUI shows: CONNECTED (4).

However, my full node got synced, and then the wallet closed a few connections and now is only connected to one node.
However the GUI still shows CONNECTED (4).

When I do a force refresh, it shows CONNECTED (1).

### Version

main

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
Already fixed in 1.5.
