### ISSUE TITLE
[Bug] Windows - Double clicking the "Pending Offer" icon on the Offers tab results in a crash

### ISSUE THREAD

**Issue by rkroelin** [Chia-Network/chia-blockchain-gui#857]
### What happened?

Double clicking the below icon in the offers tab of Windows version 1.5 of the chia client results in a error message and crash
![image](https://user-images.githubusercontent.com/53322426/181355100-bc277dca-f1ed-4cf8-90ec-1715213ed3e2.png)

![image](https://user-images.githubusercontent.com/53322426/181352649-3693b311-34b0-4d23-914e-1caa935c0437.png)

### Version

1.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/855
