### ISSUE TITLE
The estimate for time to farm a block must take into account block speed

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain-gui#87]
Currently, it assumes a network-wide block time of 18.75 seconds. This is not always the case, because there might be a lot of new farmers, but the difficulty is still low, so we could see 10 second block times. Therefore we must check like the last 200 blocks to see the average block time, when computing the farming time estimate.

**Comment by seeden** [comment]
@mariano54 can you send me this value with other values from the backend side? It is related to https://github.com/Chia-Network/chia-blockchain-gui/issues/69

**Comment by mariano54** [comment]
This is just a UI displayed value, this is not generated by the backend.

**Comment by seeden** [comment]
@mariano54  Do you really want to read the last 200 blocks on the UI side for this one value? I think that the better way is to compute it on the backend side and just ask for it from the UI. We are going to compute other values from this screen on the backend side as well.

**Comment by mariano54** [comment]
You can just fetch height - 200 and compare the timestamps.

I don't think this is something that is relevant to the backend, it's just nice way to display your farming time. Also, the farmer and the node are two separate services, we cannot calculate this value in either one

**Comment by seeden** [comment]
@mariano54 that makes sense. I will update it
