### ISSUE TITLE
GUI: CAT TAIL hover box overlaps "Search on Tail Database" link making it difficult to click the link

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain-gui#909]

**Comment by wallentx** [comment]
![2022-08-13_20-59](https://user-images.githubusercontent.com/8990544/184519406-8603fdfb-eed2-4eaa-9ca4-42e5e3d8f406.png)
Example

**Comment by paninaro** [comment]
The latest fix makes this a bit better
