### ISSUE TITLE
Farm tab shows negative TXCH User Transaction Fees

### ISSUE THREAD

**Issue by michaelmattig** [Chia-Network/chia-blockchain-gui#92]
Farm tab shows negative TXCH User Transaction Fees, while Wallet shows positive incoming amounts

![grafik](https://user-images.githubusercontent.com/10283892/109073287-76143400-76f6-11eb-89ff-c2240d27c006.png)

**Comment by seeden** [comment]
It is probably related to https://github.com/Chia-Network/chia-blockchain-gui/issues/69

**Comment by seeden** [comment]
Fix already merged
