### ISSUE TITLE
[Bug] Create Transaction screen locked after send

### ISSUE THREAD

**Issue by Rigidity** [Chia-Network/chia-blockchain-gui#949]
### What happened?

When you send a transaction, it locks the fields and spins for a long time, even after it has been confirmed on-chain. If you switch over to the summary tab and back it will stop spinning and update the balance, but the UI is still locked and prevents further transactions.

You have to completely switch screens, for example which asset you are viewing in order to clear it. Some sort of React state getting stuck.

### Version

1.5.1452

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
When you do this, it actually locks up all the "Send" screens for all the CATs. You have to click the XCH view to make it go away

**Comment by wallentx** [comment]
Still happening as of 1.6.1rc2

**Comment by paninaro** [comment]
Fixed by https://github.com/Chia-Network/chia-blockchain/pull/13748
