### ISSUE TITLE
Maybe change "Delete" to "Disconnect"

### ISSUE THREAD

**Issue by ordtrogen** [Chia-Network/chia-blockchain-gui#95]
On the connections page, the rightmost column says "Delete" which to seems a bit too final or definitive. How about "Disconnect", instead? Matches the "Connect to other peers" section below the table. If you have a "disconnect" icon for the column, taht would be nice, but the trash bin isn't too bad

![Skärmavbild 2021-02-25 kl  08 39 12](https://user-images.githubusercontent.com/15184875/109120277-0cbc1180-7746-11eb-8775-d85c1256a300.png)

**Comment by seeden** [comment]
@ordtrogen I already did few improvements related to this. Let me know if you want to change something :) thanks
I will try to use the disconnect icon as well in the short run but material-ui has no support for the disconnect icon.
