### ISSUE TITLE
[Bug] Asset ID not shown when accepting offer

### ISSUE THREAD

**Issue by cameroncooper** [Chia-Network/chia-blockchain-gui#950]
### What happened?

When accepting an offer for an Unknown CAT, I am told to verify the Asset ID but it is not shown.

![image](https://user-images.githubusercontent.com/898689/185700830-1179e8dd-0db5-493c-aefb-93b7600dd877.png)

### Version

1.5.1.dev452

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Fix is in main. Needs to be included in 1.6.0

**Comment by paninaro** [comment]
Fixed in 1.6.1 with new offer builder
