### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'className')

### ISSUE THREAD

**Issue by mor** [Chia-Network/chia-blockchain-gui#954]
### What happened?

Looking at the offers tab. There's only one offer in the list. Clicked on Show Details. Boom. Error screen, reload required.

### Version

1.5.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'className')

URL
#/dashboard/offers/view

Stacktrace
at webpack://@chia/gui/node_modules/@mui/material/Tooltip/Tooltip.js:507:52 popperRef.current.update
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:176:259 useOpaqueIdentifier
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:271:399 d=b.pendingProps;e=b.memoizedState;e=null!==e?e.element:null;yg(a,b);Cg(b,d,null,c);d=b.memoizedState.element;if(d===e)sh(),b=hi(a,b,c);else{e=b.stateNode;if(f=e.hydrate)kh=rf(b.stateNode.containerInfo.firstChild),jh=b,f=lh=!0;if
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:123:114 jg
at webpack://@chia/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
```

**Comment by paninaro** [comment]
Can you share any details about the offer (or can you share the offer itself?). Was it an offer you created or one you accepted? What type of offer? NFT/XCH/CAT?

**Comment by mor** [comment]
That offer has been accepted and confirmed, and the error/crash still occurs when trying to view the details of the 'Confirmed' trade... I've added new offers and the same thing always happens. It crashes on a click to 'Show Details'.  They're all CAT -> CAT trades. I can do 'Display Offer Data' without a crash:

offer1qqz83wcsltt6wcmqvpsxygqqlsvpneul2j49794ueqcmh5z0kd2jpxrfevykualakzjswxh9taehpsk5cxdkpgc4md5v2dj6kxx4vm9rzhdk330k07qz5djguxlvqlxlu7z80tvdcmd7v3jxfhyr6ykthqlvql8wmtqt38vptkakke9442sv5fnw7r78yvl0x2f73gvsde8w80ck0t4ld2t5th0pfg8kh3qlekehxd8ks4gp4hd5deu2cyvzfvlqgn084taym2t88z7kaue0h4l3lv6v88la3lmlw0q0uvyfq78hgy6q4x87zexzae2eeej7puy6t7lt0klk48e0xmytn4dlxdlu82actst9nky3t6l0laxhuzjy9qp4nw8u0h4wf5r48lmgtthke8m0s7njs7shqywr5uestmr85m7wzdxlw4e30fuljn6m6f83trtle45dr7njljpcv4txp9wa5d0xzed34fvjkf0m8xj2rsn7vx62jvk62svkm25vxe25dxe2vzcarfs283c07rlk569xgerfdu4vl7h0zwltmkrzkrh05kvtjz23dfv8ym0nulnxm6f3vk0mqp59tq2ucyx70fw5vzpnwdqahne8ws32lvn5zf0tfhe34ack96clalplxah08ny5hx9308jawk463uqsj0xfurzl49d9vj0tn8gjrrxgfkvqvjxmahlcyhv0rjfaamcda0hac5m9cglx8xtqaurcj7fmrllu3tp7k75w4elulm907nwv9llpx4sxxgfk3xkumd5ay5a6rzz7ljp5rmtmq7dyy7m9v6twkngc0x0fgyre00qv7lnqrxgx235lxl7pl456j9ecevkedmm8mnuzl2uqlxyyem86dr3axuunfua3mamhwc9aup25vhlhlsdvt79tw8evmmz775taxr34h2y20pf875w2fdt8khh0l2ucu8jh6any95haluz7cjm2lqtwmhtsyr3denz268x60y7vpdvqf6nw4a5njfr34axwemkrhll30dpd3ewnx2mjg0a79g4aj7mdt3naewvtylh40w2sadvcud4v0ruxhl50lh7vheg2rc0lsfnl78ma4xf8ndz6gflwvd3pxhe3xrdkkwllut27mz20kkm0wlrp603t5pjcfknrlut3q653l4hk907sgz2yn442t4dh4hsxvjnyjhycclwl4l9zcgddj3fmeflm745majf6g9wrx5rkyy3gzjnzu7lmvkval2smgtdevvzd2ykp0xwh6e48q5nwc7zsfgutlykdvutzn5edxhj0v55k9wla8pz805mlluruynm9ashd5n57d9fvplh6kvayll0k4ks77g3x4h4ew7zu5qu9xlkf5ut52eg322al6ffke5ceufhmunuqvqpva4qxckxnqz8

**Comment by mor** [comment]
> Can you share any details about the offer (or can you share the offer itself?). Was it an offer you created or one you accepted? What type of offer? NFT/XCH/CAT?

That offer has been accepted and confirmed, BUT the error/crash still occurs when trying to view the details of the 'Confirmed' trade... I've created new offers and the same thing always happens. It crashes on a click to 'Show Details'. They're all CAT -> CAT trades. I can do 'Display Offer Data' without a crash:

offer1qqz83wcsltt6wcmqvpsxygqqlsvpneul2j49794ueqcmh5z0kd2jpxrfevykualakzjswxh9taehpsk5cxdkpgc4md5v2dj6kxx4vm9rzhdk330k07qz5djguxlvqlxlu7z80tvdcmd7v3jxfhyr6ykthqlvql8wmtqt38vptkakke9442sv5fnw7r78yvl0x2f73gvsde8w80ck0t4ld2t5th0pfg8kh3qlekehxd8ks4gp4hd5deu2cyvzfvlqgn084taym2t88z7kaue0h4l3lv6v88la3lmlw0q0uvyfq78hgy6q4x87zexzae2eeej7puy6t7lt0klk48e0xmytn4dlxdlu82actst9nky3t6l0laxhuzjy9qp4nw8u0h4wf5r48lmgtthke8m0s7njs7shqywr5uestmr85m7wzdxlw4e30fuljn6m6f83trtle45dr7njljpcv4txp9wa5d0xzed34fvjkf0m8xj2rsn7vx62jvk62svkm25vxe25dxe2vzcarfs283c07rlk569xgerfdu4vl7h0zwltmkrzkrh05kvtjz23dfv8ym0nulnxm6f3vk0mqp59tq2ucyx70fw5vzpnwdqahne8ws32lvn5zf0tfhe34ack96clalplxah08ny5hx9308jawk463uqsj0xfurzl49d9vj0tn8gjrrxgfkvqvjxmahlcyhv0rjfaamcda0hac5m9cglx8xtqaurcj7fmrllu3tp7k75w4elulm907nwv9llpx4sxxgfk3xkumd5ay5a6rzz7ljp5rmtmq7dyy7m9v6twkngc0x0fgyre00qv7lnqrxgx235lxl7pl456j9ecevkedmm8mnuzl2uqlxyyem86dr3axuunfua3mamhwc9aup25vhlhlsdvt79tw8evmmz775taxr34h2y20pf875w2fdt8khh0l2ucu8jh6any95haluz7cjm2lqtwmhtsyr3denz268x60y7vpdvqf6nw4a5njfr34axwemkrhll30dpd3ewnx2mjg0a79g4aj7mdt3naewvtylh40w2sadvcud4v0ruxhl50lh7vheg2rc0lsfnl78ma4xf8ndz6gflwvd3pxhe3xrdkkwllut27mz20kkm0wlrp603t5pjcfknrlut3q653l4hk907sgz2yn442t4dh4hsxvjnyjhycclwl4l9zcgddj3fmeflm745majf6g9wrx5rkyy3gzjnzu7lmvkval2smgtdevvzd2ykp0xwh6e48q5nwc7zsfgutlykdvutzn5edxhj0v55k9wla8pz805mlluruynm9ashd5n57d9fvplh6kvayll0k4ks77g3x4h4ew7zu5qu9xlkf5ut52eg322al6ffke5ceufhmunuqvqpva4qxckxnqz8

**Comment by mor** [comment]
Here is an addendum. Since I opened this Issue, I've seen that the problem affects all my wallets, and all my offers, including XCH, CAT, and NFT. Not only a crash, but wallet db corruption. Disappearing CATs and NFTs, wrong balances. Etc.  I might be talking out my ass, but it seems there is a missing step in the CAT2 reissue, where instead of simply upgrading to 1.5.0 to get a _r1_ wallet and begin using CAT2s, but you should instead delete all your .sqlite files and rebuild each fingerprint from scratch under 1.5.0. It's a lot of work to cxl offers, rebuild the database, resubmit offers, re-enter all the CAT names, etc. But I did this and it seems to be working like normal now. Fingers crossed. This might be a tip of the same iceberg as a quirk/gotcha found in the CAT2 reissue procedure, whereby you couldn't just run 1.5.0 and fund an existing wallet with a big enough coin to reissue, but had to create a brand new fingerprint keypair under 1.5.0 and use that to run the reissue process.

**Comment by mor** [comment]
Okay, nevermind the 'I think I fixed it' apects of the prior post. I did manage to create a brand new offer in a newly rebuilt 1.5.0 wallet that did yet again crash the gui exactly as noted in the first post. And presumably just re-corrupted the wallet. Ergo, this bug makes the GUI completely unusable. The problems I mentioned with XCH and NFT may only appear AFTER the wallet is corrupted by this crash, which seems only to happen in a cleanly rebuilt wallet when offering CATs... Please have a look at this! Here is the latest Offer Data that crashes my GUI when I click on 'Show Details':

`offer1qqz83wcsltt6wcmqvpsxygqq73ljk00crzuwp3x4y5k4vuc0rmjtvd66w5hw3dxt3s8uuvvudfnjvwwr6nqekc9rzhdk33fkt2cc64nv5v2ak6x97elcq23kfrsmasrumlncgaad3hrdhejxgexus0gjewurasruamdvpwyas9wmk6mykk42pjjw3xh7nr88pm3ed0ns8wla96lh33pmxa87c5uyj9ghh33de9hjcqc3kkj4gr4md5devgcqdjfvwzfhy97fwrllzvk2y2hx8pnjgrvewza43l84nu44wmv3wfa0vham5x4gusgw0pqk76lsugg2lm4hd8lf8cafzd0gwdvqed75xtqmlm7kg3lquyl6mlx8ccgzz84yqdnk48ds5lcgumx86764la04fcwjtu8e6ds9fj7m359qua7yuvtr0pmewjmlmm9dlwnmefj28k25lu7zkn8mxaq47mt8hmpu78y95v8dlmh587zmg4y5x4rdk24rdk2ardk2dpdktd9dqgtpkmdtcqpl0lmqd74kcw3re5dmr0zqnzpk8fw67m8vqss9n6cvauk4l65nt9k3fx4mh3t8gw4s4eq2dcu2lfgxrw72ralp59s2adune64lqdh5mr8rd2hnmpl8nj3n695l0huunqndht3q03xt0h9363f6a5fx8rpwe77nqa43eyxmxqxep3kmluzmk83ey67a7x7km7u60j5y0hrr9sw7puf0xa37l6g4jltw282ul70ajhlehxzllsn6crryymgrgxlppjv7we2ndueulhd7v0j7w7c47esemjccaw63dhtay23nnsmgl2xl7n0jpeqf2dhlzuzd0mvt3am0d90uwl442enmum3qjq5t6ff8vk6dnhmmx3282k4l33nw5q40hlcte3x75m79f45de79tajktezke4yw2axr83u0a69lq6qmwtwag4hdt2xyjamljlx9w74ddc38qfj023n8uwt0rxhzm97hela4r72ukwngnja7v5dgnpxsyn77khs70pckuq6dclyhwxwfdjhs6ddne5klunlldfe7pxmm6xje56ntg8e5drtlzl5r3ts3lflx8m9j6h2a9yk3edn64vdakqhd78x0nmnjttankt7w9xvk5pwcgxhrluteq6ss0hhayps4g4zfsd8mahwg90ge207xjxjewf8qwd4n5jvwnarv756dr5fctgc77hm7tmxgsjdqgrvrwvm0mudv2ftllv4hsqex4j809xjlhthdhdkd8h9ldh97w7gth6d09ruwl2d3w5mh7dltw7z8n2j7wajxqzza75g0nvhae5rw8xemm7w9de4u5cj22yfaf4frp2u5dxehm7vdnlfghy6285hxfeau37w6ekkwr64c9qrydsdkgyl7qwe`

**Comment by seeden** [comment]
This issue was already fixed. Please upgrade to 1.5.1
