### ISSUE TITLE
Wallet with DID, NFT wallets, CATs getting inconsistent wallet sync from 0 results

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain-gui#960]
### What happened?

After deleting the wallet DB for a wallet that has a variety of items, such as CATs, a DID, a DID-linked NFT wallet, a regular NFT wallet, and several NFTs belonging to the various wallets, I am seeing inconsistent sync results.
Sometimes it never syncs the DID, but will sync the various wallets. Regardless of what I try, it seems to never be able to sync the DID unless I delete the DB and try again.
In my most recent attempt, it synced the DID, but the GUI won't show my wallets. The CLI does show my NFT wallets.

### Version

1.5.1 dev454

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by trepca** [comment]
Does CLI show both DID and NFT wallets?

**Comment by wallentx** [comment]
Yessir

**Comment by paninaro** [comment]
Using this uber bug to track the specific GUI repro wherein NFT wallets (and NFTs) don't appear in the GUI on a fresh sync if waiting on the NFT gallery screen during sync.

**Comment by paninaro** [comment]
Izumi has already submitted a backend fix for `state_changed()` messages not being delivered to the GUI. The remaining work is to properly refresh the GUI when NFT wallets are created.

**Comment by wallentx** [comment]
I'll try another sync from 0 on latest main and report back

**Comment by trepca** [comment]
@wallentx did you manage try this?
