### ISSUE TITLE
[Bug] When running the GUI, the debug logs are being spammed 

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain-gui#961]
### What happened?

The GUI is causing the daemon debug logs to send an excessive amount of `WSMessage is_running` messages, at least one every second. When launching the services from the CLI, no such messages are being seen.

### Version

1.5.1 dev454

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
This is actually by design, but I think we can back off on the once-a-second polling. @seeden do you see any reason why we can't back this off to maybe every 5 seconds or so?

**Comment by seeden** [comment]
PR ready. Closing it
