### ISSUE TITLE
GUI option to start DataLayer services at app launch

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain-gui#963]
Add a new "Data Layer" tab to Settings

Options to:
"Enable Data Layer" --> Starts the DL RPC service
"Enable Data Propagation Server" (subordinate to the enable DL checkbox)

**Comment by emlowe** [comment]
This merged - at least the single option. The Propagation server piece is delayed due to delays in the under laying service - Creating tracker for that
